### ISSUE TITLE
Getting following error, 1001770908 => Local4 | {'cmd': 'info'}

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [AlexxIT/SonoffLAN#1005]
Since I replaced my TH16's with TH316's I get regular the following error in my logs

This error originated from a custom integration.

Logger: custom_components.sonoff.core.ewelink.local
Source: custom_components/sonoff/core/ewelink/local.py:257
Integration: Sonoff (documentation, issues)
First occurred: 22:46:44 (1 occurrences)
Last logged: 22:46:44

1001770908 => Local4 | {'cmd': 'info'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/yarl/_url.py", line 166, in __new__
    port = val.port
  File "/usr/local/lib/python3.10/urllib/parse.py", line 178, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as ':7a21:84ff:febb:d194:8081'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 422, in _request
    url = self._build_url(str_or_url)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 356, in _build_url
    url = URL(str_or_url)
  File "/usr/local/lib/python3.10/site-packages/yarl/_url.py", line 168, in __new__
    raise ValueError(
ValueError: Invalid URL: port can't be converted to integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/local.py", line 257, in send
    r = await self.session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 424, in _request
    raise InvalidURL(str_or_url) from e
aiohttp.client_exceptions.InvalidURL: http://fe80::7a21:84ff:febb:d194:8081/zeroconf/info

**Comment by sipimokus** [comment]
I think this is duplicated issue: https://github.com/AlexxIT/SonoffLAN/issues/1000

**Comment by smarthomefamilyverrips** [comment]
> I think this is duplicated issue: #1000

Is a similar error indeed, I only not am using IPV6 anywhere myself so not seems that this issue is related to that

**Comment by smarthomefamilyverrips** [comment]
I am still receiving same error on regular basis

**Comment by AlexxIT** [comment]
Should be fixed https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.4.0

**Comment by smarthomefamilyverrips** [comment]
Thanks @AlexxIT !!! 👍🏻👍🏻👍🏻
