### ISSUE TITLE
Cloud WS exception (error 406)

### ISSUE THREAD

**Issue by hanskiepl** [AlexxIT/SonoffLAN#1011]
i have got latest version of your pllugin
Generally it works but i dont know why it ocasionally stops working on every single day.
eWelink app works fine when homeasistatnt stops reading data.

```
Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/core/ewelink/cloud.py:318
Integration: Sonoff (documentation, issues)
First occurred: 14:28:49 (5 occurrences)
Last logged: 14:50:07

Cloud WS exception
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 318, in connect
    raise Exception(resp)
Exception: {'error': 406, 'apikey': 'xxxxxxxxxxxxxxxxxx', 'sequence': '166600000029875', 'actionName': 'userOnline'}

Issues link looks like below 


2022-10-24 00:40:13 [D] 100168ba28 <= Cloud3 | {'power': '46.21', 'voltage': '228.75', 'current': '0.26'} | None
2022-10-24 00:41:03 [E] Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 318, in connect|    raise Exception(resp)|Exception: {'error': 406, 'apikey': '3c104dcf-90690000000-3180fb1f80ef', 'sequence': '1666564863386', 'actionName': 'userOnline'}|
2022-10-24 00:41:03 [D] CLOUD True => False
2022-10-24 00:41:03 [D] Cloud connection retrying in 15 seconds
2022-10-24 00:41:19 [E] Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 318, in connect|    raise Exception(resp)|Exception: {'error': 406, 'apikey': '3c104dcf-9069-⁰00000007-3180fb1f80ef', 'sequence': '1666564878993', 'actionName': 'userOnline'}|
2022-10-24 00:41:19 [D] CLOUD False => False
2022-10-24 00:41:19 [D] Cloud connection retrying in 60 seconds
2022-10-24 00:42:19 [E] Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 318, in connect|    raise Exception(resp)|Exception: {'error': 406, 'apikey': '3c104dcf-9069-0000000-3180fb1f80ef', 'sequence': '1666564939347', 'actionName': 'userOnline'}|
2022-10-24 00:42:19 [D] CLOUD False => False
2022-10-24 00:42:19 [D] Cloud connection retrying in 300 seconds
2022-10-24 00:47:19 [E] Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 318, in connect|    raise Exception(resp)|Exception: {'error': 406, 'apikey': '3c104dcf-9069-0000000-3180fb1f80ef', 'sequence': '1666565239961', 'actionName': 'userOnline'}|
2022-10-24 00:47:20 [D] CLOUD False => False
2022-10-24 00:47:20 [D] Cloud connection retrying in 900 seconds
2022-10-24 01:02:20 [E] Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 318, in connect|    raise Exception(resp)|Exception: {'error': 406, 'apikey': '3c104dcf-9069-00000000-3180fb1f80ef', 'sequence': '1666566140417', 'actionName': 'userOnline'}|
2022-10-24 01:02:20 [D] CLOUD False => False
2022-10-24 01:02:20 [D] Cloud connection retrying in 3600 seconds
2022-10-24 02:02:20 [E] Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 318, in connect|    raise Exception(resp)|Exception: {'error': 406, 'apikey': '3c104dcf-9069-00⁰000000-3180fb1f80ef', 'sequence': '1666569740881', 'actionName': 'userOnline'}|
2022-10-24 02:02:20 [D] CLOUD False => False
2022-10-24 02:02:20 [D] Cloud connection retrying in 3600 seconds
2022-10-24 03:02:21 [E] Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 318, in connect|    raise Exception(resp)|Exception: {'error': 406, 'apikey': '3c104dcf-9069-0000000-3180fb1f80ef', 'sequence': '1666573341784', 'actionName': 'userOnline'}|
2022-10-24 03:02:21 [D] CLOUD False => False
2022-10-24 03:02:21 [D] Cloud connection retrying in 3600 seconds
```

**Comment by yurtaevalex** [comment]
ver. v3.3.1
Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/core/ewelink/cloud.py:318
Integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: 30 октября 2022 г., 12:42:06 (51 occurrences)
Last logged: 12:06:11

Cloud WS exception
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 318, in connect
    raise Exception(resp)
Exception: {'error': 406, 'apikey': '85bd12d3-4cad-4439-b6bf-b07ce89c2dbd', 'sequence': '1667115726272', 'actionName': 'userOnline'}

**Comment by AlexxIT** [comment]
Is problem still actual?

**Comment by yurtaevalex** [comment]
> Проблема еще актуальна?

Yes, the problem is real

**Comment by hanskiepl** [comment]
> Is problem still actual?

Yes, still the same problem. Sometime once sometime a few times daily :-(

**Comment by phantomdez** [comment]
I have this issue as well.  I am unable to add new devices to home assistant it seems.  Existing devices are working normally.  The new device is working in the eWelink app but I cannot see it in Home assistant.

**Comment by pauldanieltudor** [comment]
I get the same error but in my case it is after some 2-3 days of working perfectly and if I restart HA it works fine again, the problem ony manifests on devices that are connected via cloud only (not in my home LAN) Any fix on this?

Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 318, in connect|    raise Exception(resp)|Exception: {'error': 406, 'apikey':
'actionName': 'userOnline'

**Comment by mjburton** [comment]
I have the same issue after upgrading to the latest HA and 3.3.1, yet the debug log suggests it has found the one device I have:

        ],
        "level": "WARNING",
        "source": [
          "custom_components/sonoff/core/ewelink/cloud.py",
          192
        ],
        "timestamp": 1670769011.3212235,
        "exception": "Traceback (most recent call last):\n  File \"/config/custom_components/sonoff/__init__.py\", line 199, in internal_normal_setup\n    devices = await registry.cloud.get_devices(homes)\n  File \"/config/custom_components/sonoff/core/ewelink/cloud.py\", line 192, in get_devices\n    raise Exception(resp[\"msg\"])\nException: cannot found access token info\n",
        "count": 1,
        "first_occurred": 1670769011.3212235
      },
      {
        "name": "custom_components.sonoff.core.ewelink.cloud",
        "message": [
          "Cloud WS exception"
        ],
        "level": "ERROR",
        "source": [
          "custom_components/sonoff/core/ewelink/cloud.py",
          318
        ],
        "timestamp": 1670769387.9991748,
        "exception": "Traceback (most recent call last):\n  File \"/config/custom_components/sonoff/core/ewelink/cloud.py\", line 318, in connect\n    raise Exception(resp)\nException: {'error': 406, 'apikey': 'xxxxxxxxxxx', 'sequence': '1670769011661', 'actionName': 'userOnline'}\n",
        "count": 4,
        "first_occurred": 1670769011.688297
      }

**Comment by fuzzybear62** [comment]
Same issue, version 3.3.1 HA 2023.1.0

This is the output log:
2023-01-05 16:17:00.639 ERROR (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud WS exception
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 318, in connect
    raise Exception(resp)
Exception: {'error': 406, 'apikey': 'XXXXXXXX', 'sequence': 'XXXXX', 'actionName': 'userOnline'}

**Comment by mjburton** [comment]
To resolve this I created another Sonoff account and shared the device with
it. Looks to be an issue with being logged in two places (app on phone,
Hass)

**Comment by AlexxIT** [comment]
This is authorization error from cloud. I don't know how to reproduce it. And don't know how to fix it.
Make sure you using latest integration version with latest version for cloud API

**Comment by pauldanieltudor** [comment]
It seems a year passed, many updates since then, problem persists: Cloud devices go permanently offline (unavailable) after 2-4 days, sometimes they work fine for 2-3 weeks, just had a record of almost a month, so it is indeed a rare occurance. Reloading the integration does not help, only HA restart fixes the issue but it does fix it every single time. I do get a cloud authentification error in logs but it does not help much: 

Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 323, in connect|    raise Exception(resp)|Exception: {'error': 406, 'reason': 'Authentication Failed', 'apikey': 'sequence': '1695612246995', 'actionName': 'userOnline'}
CLOUD False => False

Devices in LAN never fail, only those outside of my LAN have this issue, they are actually in a subnet of my LAN but same thing: not in my LAN. Each time I find the offline in HA I check the ewelink app and there they are always working.

Not sure it helps but in older versions (2022-ish) reloading the integration used to work to fix this issue, sadly since oct 2022 (could be off by 6 months) reloading stopped helping and now requires HA restart.

**Comment by pauldanieltudor** [comment]
Also quick reload does not fix the issue either, anything (including updates to core or Supervisor) that involves HA restart will bring them right back up.

**Comment by farmerkz** [comment]
The same problem, I won’t tell you the exact time it appeared, but it seems that after the HAOS update a few days ago.

```
2023-10-06 00:40:37.825 ERROR (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud WS exception
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 323, in connect
    raise Exception(resp)
Exception: {'error': 406, 'reason': 'Authentication Failed', 'apikey': 'xxxxxxxxxxxxxxxx', 'sequence': 'dddddddddd', 'actionName': 'userOnline'}
```

A quick reload does not solve the problem; after rebooting HAOS, the problem disappears for about a day.

**Comment by eduardoit** [comment]
I live day after day with the same problem. I have all the updates up to date.

Este error se originó a partir de una integración personalizada.

Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/core/ewelink/cloud.py:323
Integration: Sonoff (documentation, issues)
First occurred: 9 de noviembre de 2023, 23:59:09 (15 occurrences)
Last logged: 10:21:02

Cloud WS exception
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 323, in connect
    raise Exception(resp)
Exception: {'error': 406, 'reason': 'Authentication Failed', 'apikey': 'xxxxxxxxxxxxx', 'sequence': 'xxxxxxxxxxxx', 'actionName': 'userOnline'}

I reload the integration and it works again for a couple of hours.

**Comment by marinus61** [comment]
Hi AlexxIT, thks works now, appriciate the great work you done for this great integration

**Comment by AlexxIT** [comment]
I didn't do anything about this issue. As I said earlier, it's a cloud error.

**Comment by marinus61** [comment]
Anyway happy that your great integration is working again. Thks for your swift "support", maybe you have magical skills :)

**Comment by AlexxIT** [comment]
PS. "Authentication Failed" can be if you logged in with same account from another place.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.7.0
