### ISSUE TITLE
Erratic and fluctuating values from THR316 (Port could not be cast to integer)

### ISSUE THREAD

**Issue by pberswe** [AlexxIT/SonoffLAN#1085]
I have a Sonoff THR316 with temperature probe attached, and in home assistant the temperature values are constantly fluctuating alotand it fills the database with loads of data and makes automations unusable. This is only in homeassistant, if i look in the ewelink app temperature is stable. Also, the diagnostic files says it's 27 degrees but the sensor says its 23.1.

See the error in the diagnostic info, not sure  how or if its related but it seems od.  Please see attatched inof bellow, not sure what more i could/should include.

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/26113833/212574385-2370c213-2ef7-4b34-a8a0-63b5f570050b.png">

<img width="541" alt="image" src="https://user-images.githubusercontent.com/26113833/212574639-f308bd56-875a-437e-b135-6a51cbf0e852.png">

> {
>   "home_assistant": {
>     "installation_type": "Home Assistant OS",
>     "version": "2023.1.4",
>     "dev": false,
>     "hassio": true,
>     "virtualenv": false,
>     "python_version": "3.10.7",
>     "docker": true,
>     "arch": "aarch64",
>     "timezone": "Europe/Stockholm",
>     "os_name": "Linux",
>     "os_version": "5.15.76-v8",
>     "supervisor": "2022.12.1",
>     "host_os": "Home Assistant OS 9.4",
>     "docker_version": "20.10.19",
>     "chassis": "embedded",
>     "run_as_root": true
>   },
>   "custom_components": {
>     "dwains_dashboard": {
>       "version": "3.3.0",
>       "requirements": []
>     },
>     "tapo_control": {
>       "version": "4.2.1",
>       "requirements": [
>         "pytapo==2.8",
>         "onvif-zeep-async==1.2.0"
>       ]
>     },
>     "hacs": {
>       "version": "1.29.0",
>       "requirements": [
>         "aiogithubapi>=22.10.1"
>       ]
>     },
>     "nordpool": {
>       "version": "0.0.9",
>       "requirements": [
>         "nordpool>=0.2"
>       ]
>     },
>     "sonoff": {
>       "version": "3.3.1",
>       "requirements": [
>         "pycryptodome>=3.6.6"
>       ]
>     }
>   },
>   "integration_manifest": {
>     "domain": "sonoff",
>     "name": "Sonoff",
>     "config_flow": true,
>     "documentation": "https://github.com/AlexxIT/SonoffLAN",
>     "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
>     "codeowners": [
>       "@AlexxIT"
>     ],
>     "dependencies": [
>       "http",
>       "zeroconf"
>     ],
>     "requirements": [
>       "pycryptodome>=3.6.6"
>     ],
>     "version": "3.3.1",
>     "iot_class": "local_push",
>     "is_built_in": false
>   },
>   "data": {
>     "version": "b20e33c",
>     "cloud_auth": true,
>     "config": null,
>     "options": {
>       "mode": "auto",
>       "debug": false
>     },
>     "errors": [
>       {
>         "name": "custom_components.sonoff.core.ewelink.local",
>         "message": [
>           "1001770c07 => Local4 | {'switch': 'on', 'mainSwitch': 'on', 'deviceType': 'normal'}",
>           "1001770c07 => Local4 | {'switch': 'off', 'mainSwitch': 'off', 'deviceType': 'normal'}"
>         ],
>         "level": "ERROR",
>         "source": [
>           "custom_components/sonoff/core/ewelink/local.py",
>           257
>         ],
>         "timestamp": 1673826157.0734766,
>         "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/yarl/_url.py\", line 166, in __new__\n    port = val.port\n  File \"/usr/local/lib/python3.10/urllib/parse.py\", line 178, in port\n    raise ValueError(message) from None\nValueError: Port could not be cast to integer value as ':7a21:84ff:febb:d168:8081'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/aiohttp/client.py\", line 422, in _request\n    url = self._build_url(str_or_url)\n  File \"/usr/local/lib/python3.10/site-packages/aiohttp/client.py\", line 356, in _build_url\n    url = URL(str_or_url)\n  File \"/usr/local/lib/python3.10/site-packages/yarl/_url.py\", line 168, in __new__\n    raise ValueError(\nValueError: Invalid URL: port can't be converted to integer\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/config/custom_components/sonoff/core/ewelink/local.py\", line 257, in send\n    r = await self.session.post(\n  File \"/usr/local/lib/python3.10/site-packages/aiohttp/client.py\", line 424, in _request\n    raise InvalidURL(str_or_url) from e\naiohttp.client_exceptions.InvalidURL: http://fe80::7a21:84ff:febb:d168:8081/zeroconf/switch\n",
>         "count": 178,
>         "first_occurred": 1673745398.7842739
>       }
>     ],
>     "device": {
>       "uiid": 181,
>       "params": {
>         "bindInfos": "***",
>         "version": 8,
>         "ssid": "***",
>         "bssid": "***",
>         "fwVersion": "1.1.0",
>         "switch": "off",
>         "startup": "on",
>         "pulseConfig": {
>           "pulse": "off",
>           "switch": "off",
>           "pulseWidth": 500
>         },
>         "sledOnline": "on",
>         "tempUnit": 0,
>         "sensorType": "DS18B20",
>         "currentTemperature": "27.1",
>         "currentHumidity": "unavailable",
>         "rssi": -45,
>         "staMac": "***",
>         "autoControl": [],
>         "autoControlEnabled": 0,
>         "uiActive": 60,
>         "timeZone": 1,
>         "mainSwitch": "off",
>         "deviceType": "normal",
>         "only_device": {
>           "ota": "success",
>           "ota_fail_reason": 0
>         },
>         "tempCorrection": 0,
>         "humCorrection": 0,
>         "tempHumiType": 1
>       },
>       "model": "THR316",
>       "online": true,
>       "localtype": "th_plug",
>       "deviceid": "1001770c07"
>     }
>   }
> }

**Comment by Masterz69** [comment]
Probably logs from Settings->Integrations->Sonoff->Known issues can be useful 
- to see what device send over network to HA.

Have one, but with AM3201 sensor. It reports model as THR316D. 
As well see no issues with reported data in eWelink App & HA.

**Comment by pberswe** [comment]
> Probably logs from Settings->Integrations->Sonoff->Known issues can be useful
> 
> * to see what device send over network to HA.

I'm sorry if i am thick but  Settings->Integrations->Sonoff->Known issues just leads me to this page https://github.com/AlexxIT/SonoffLAN/issues

**Comment by Masterz69** [comment]
Probably need to Enable debug pane first, as described in doc:

**Debug page**
Enable debug page in integration options. Reload integrations page. Open: Integraion > Menu > Known issues.

**Comment by pberswe** [comment]
ok I figured it out I assume, I had to go Settings->Integrations->Sonoff->enable debug logging and then when i disabled debug logging the log was downloaded. 

The log is basically an endless repeat of;
`
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 422, in _request
    url = self._build_url(str_or_url)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 356, in _build_url
    url = URL(str_or_url)
  File "/usr/local/lib/python3.10/site-packages/yarl/_url.py", line 168, in __new__
    raise ValueError(
ValueError: Invalid URL: port can't be converted to integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/local.py", line 257, in send
    r = await self.session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 424, in _request
    raise InvalidURL(str_or_url) from e
aiohttp.client_exceptions.InvalidURL: http://fe80::7a21:84ff:febb:d168:8081/zeroconf/switch
2023-01-20 15:44:17.139 ERROR (MainThread) [custom_components.sonoff.core.ewelink.local] 1001770c07 => Local4 | {'switch': 'on', 'mainSwitch': 'on', 'deviceType': 'normal'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/yarl/_url.py", line 166, in __new__
    port = val.port
  File "/usr/local/lib/python3.10/urllib/parse.py", line 178, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as ':7a21:84ff:febb:d168:8081'
`

**Comment by Masterz69** [comment]
```fe80::7a21:84ff:febb:d168``` is a IPv6 address.
Do You using IPv6 in Your network ? As component not actually supporting IPv6 - so far I see in code.
Suggest to disable IPv6 on HA server and monitor then.

Can use "Bonjour Browser" to see zeroconf information, broadcasting on Your network.
Would be nice to check - is actually device 1001770c07 sending IPv6 address !?

**Comment by AlexxIT** [comment]
You need to collect debug logs:
https://github.com/AlexxIT/SonoffLAN#debug-page

IPv6 is another issue. I'll try to fix it
