### ISSUE TITLE
Cloud processing error - KeyError: 'color'

### ISSUE THREAD

**Issue by esmaele** [AlexxIT/SonoffLAN#1090]
Hi 
I need help or hint to resolve this issue 

```
Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/light.py:380
Integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: January 23, 2023 at 8:21:58 PM (13 occurrences)
Last logged: 3:41:18 AM

Cloud processing error
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 286, in run_forever
    await self._process_ws_msg(resp)
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 346, in _process_ws_msg
    self.dispatcher_send(SIGNAL_UPDATE, data)
  File "/config/custom_components/sonoff/core/ewelink/base.py", line 59, in dispatcher_send
    handler(*args, **kwargs)
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 188, in cloud_update
    self.dispatcher_send(did, params)
  File "/config/custom_components/sonoff/core/ewelink/base.py", line 59, in dispatcher_send
    handler(*args, **kwargs)
  File "/config/custom_components/sonoff/core/entity.py", line 108, in internal_update
    self.set_state(params)
  File "/config/custom_components/sonoff/light.py", line 380, in set_state
    state = params[effect]
KeyError: 'color'
```
[config_entry-sonoff-6f4ae13b1f29098437b73ca3a8fc0897.json (4).txt](https://github.com/AlexxIT/SonoffLAN/files/10506864/config_entry-sonoff-6f4ae13b1f29098437b73ca3a8fc0897.json.4.txt)

Thanks

**Comment by AlexxIT** [comment]
I think problem same as https://github.com/AlexxIT/SonoffLAN/issues/1093
