### ISSUE TITLE
B05-BL - Cloud processing error, cloud connection stops functioning

### ISSUE THREAD

**Issue by rkistner** [AlexxIT/SonoffLAN#1093]
I'm getting a "Cloud processing error" when changing the state of my B05-BL light. Shortly after this happens (within minutes), the cloud connection seems to stop functioning, with only local mode working, until I reload the integration. The cloud connection not functioning is the biggest issue to me here - it feels like that shouldn't happen because of a bug in the processing code.

Home assistant logs:

```
2023-01-30 11:58:38.675 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud processing error
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 285, in run_forever
    await self._process_ws_msg(resp)
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 345, in _process_ws_msg
    self.dispatcher_send(SIGNAL_UPDATE, data)
  File "/config/custom_components/sonoff/core/ewelink/base.py", line 59, in dispatcher_send
    handler(*args, **kwargs)
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 190, in cloud_update
    self.dispatcher_send(did, params)
  File "/config/custom_components/sonoff/core/ewelink/base.py", line 59, in dispatcher_send
    handler(*args, **kwargs)
  File "/config/custom_components/sonoff/core/entity.py", line 110, in internal_update
    self.set_state(params)
  File "/config/custom_components/sonoff/light.py", line 435, in set_state
    state = params[effect]
KeyError: 'nightLight'
...
2023-01-30 12:00:06.495 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud processing error
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 285, in run_forever
    await self._process_ws_msg(resp)
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 345, in _process_ws_msg
    self.dispatcher_send(SIGNAL_UPDATE, data)
  File "/config/custom_components/sonoff/core/ewelink/base.py", line 59, in dispatcher_send
    handler(*args, **kwargs)
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 190, in cloud_update
    self.dispatcher_send(did, params)
  File "/config/custom_components/sonoff/core/ewelink/base.py", line 59, in dispatcher_send
    handler(*args, **kwargs)
  File "/config/custom_components/sonoff/core/entity.py", line 110, in internal_update
    self.set_state(params)
  File "/config/custom_components/sonoff/light.py", line 435, in set_state
    state = params[effect]
KeyError: 'leisure'
```

SonoffLAN logs:
```
2023-01-30 11:58:36 [D] 10016c3439 <= Local3 | {'switch': 'off', 'ltype': 'nightLight', 'white': {'br': 70, 'ct': 29}, 'color': {'br': 22, 'r': 255, 'g': 215, 'b': 139}, 'bright': {'br': 100, 'ct': 100}, 'goodNight': {'br': 5, 'ct': 0}, 'read': {'br': 100, 'ct': 50}, 'nightLight': {'br': 1, 'ct': 0}, 'party': {'br': 45, 'r': 254, 'g': 132, 'b': 0, 'tf': 1, 'sp': 1}, 'leisure': {'br': 55, 'r': 0, 'g': 40, 'b': 254, 'tf': 1, 'sp': 1}, 'soft': {'br': 20, 'r': 38, 'g': 254, 'b': 0, 'tf': 1, 'sp': 1}, 'colorful': {'br': 100, 'r': 255, 'g': 0, 'b': 0, 'tf': 1, 'sp': 1}, 'fwVersion': '1.5.1'} | 363
2023-01-30 11:58:36 [D] 10016c3439 => Local4 | {'switch': 'off'} <= {'sequence': '1675079916000', 'encrypt': True, 'seq': 363, 'error': 0}
2023-01-30 11:58:36 [D] 10016c3439 <= Cloud3 | {'switch': 'off', 'ltype': 'nightLight'} | 1675079916000
2023-01-30 11:58:36 [W] Cloud processing error|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 285, in run_forever|    await self._process_ws_msg(resp)|KeyError: 'nightLight'|
2023-01-30 11:58:38 [D] CLOUD True => True
2023-01-30 11:58:38 [D] abd80009aa <= Cloud3 | {'bleAddr': '700E0F2A', 'outlet': 0, 'key': 0, 'count': 1089, 'actionTime': '2023-01-30T11:58:38.288Z'} | None
2023-01-30 11:58:38 [D] 10016c3439 => Local4 | {'switch': 'on'} <= {'sequence': '1675079918000', 'encrypt': True, 'seq': 364, 'error': 0}
2023-01-30 11:58:38 [D] 10016c3439 <= Local3 | {'switch': 'on', 'ltype': 'nightLight', 'white': {'br': 70, 'ct': 29}, 'color': {'br': 22, 'r': 255, 'g': 215, 'b': 139}, 'bright': {'br': 100, 'ct': 100}, 'goodNight': {'br': 5, 'ct': 0}, 'read': {'br': 100, 'ct': 50}, 'nightLight': {'br': 1, 'ct': 0}, 'party': {'br': 45, 'r': 254, 'g': 132, 'b': 0, 'tf': 1, 'sp': 1}, 'leisure': {'br': 55, 'r': 0, 'g': 40, 'b': 254, 'tf': 1, 'sp': 1}, 'soft': {'br': 20, 'r': 38, 'g': 254, 'b': 0, 'tf': 1, 'sp': 1}, 'colorful': {'br': 100, 'r': 255, 'g': 0, 'b': 0, 'tf': 1, 'sp': 1}, 'fwVersion': '1.5.1'} | 364
2023-01-30 11:58:38 [D] 10016c3439 <= Cloud3 | {'switch': 'on', 'ltype': 'nightLight'} | 1675079918000
2023-01-30 11:58:38 [W] Cloud processing error|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 285, in run_forever|    await self._process_ws_msg(resp)|KeyError: 'nightLight'|
2023-01-30 11:58:39 [D] CLOUD True => True
...
2023-01-30 12:00:04 [D] 10016c3439 <= Local3 | {'switch': 'on', 'ltype': 'leisure', 'white': {'br': 70, 'ct': 29}, 'color': {'br': 22, 'r': 255, 'g': 215, 'b': 139}, 'bright': {'br': 100, 'ct': 100}, 'goodNight': {'br': 5, 'ct': 0}, 'read': {'br': 100, 'ct': 50}, 'nightLight': {'br': 1, 'ct': 0}, 'party': {'br': 45, 'r': 254, 'g': 132, 'b': 0, 'tf': 1, 'sp': 1}, 'leisure': {'br': 55, 'r': 0, 'g': 40, 'b': 254, 'tf': 1, 'sp': 1}, 'soft': {'br': 20, 'r': 38, 'g': 254, 'b': 0, 'tf': 1, 'sp': 1}, 'colorful': {'br': 100, 'r': 255, 'g': 0, 'b': 0, 'tf': 1, 'sp': 1}, 'fwVersion': '1.5.1'} | 374
2023-01-30 12:00:04 [D] 10016c3439 => Local4 | {'cmd': 'dimmable', 'ltype': 'leisure', 'leisure': {'r': 0, 'g': 40, 'b': 254, 'br': 55, 'tf': 1, 'sp': 1}} <= {'sequence': '1675080003000', 'encrypt': True, 'seq': 374, 'error': 0}
2023-01-30 12:00:04 [D] 10016c3439 <= Cloud3 | {'switch': 'on', 'ltype': 'leisure', 'leisure': {'br': 55, 'r': 0, 'g': 40, 'b': 254, 'tf': 1, 'sp': 1}} | 1675080003000
2023-01-30 12:00:06 [D] abd80009aa <= Cloud3 | {'bleAddr': '700E0F2A', 'outlet': 3, 'key': 0, 'count': 1112, 'actionTime': '2023-01-30T12:00:06.106Z'} | None
2023-01-30 12:00:06 [D] 10016c3439 => Local4 | {'switch': 'off'} <= {'sequence': '1675080006000', 'encrypt': True, 'seq': 375, 'error': 0}
2023-01-30 12:00:06 [D] 10016c3439 <= Local3 | {'switch': 'off', 'ltype': 'leisure', 'white': {'br': 70, 'ct': 29}, 'color': {'br': 22, 'r': 255, 'g': 215, 'b': 139}, 'bright': {'br': 100, 'ct': 100}, 'goodNight': {'br': 5, 'ct': 0}, 'read': {'br': 100, 'ct': 50}, 'nightLight': {'br': 1, 'ct': 0}, 'party': {'br': 45, 'r': 254, 'g': 132, 'b': 0, 'tf': 1, 'sp': 1}, 'leisure': {'br': 55, 'r': 0, 'g': 40, 'b': 254, 'tf': 1, 'sp': 1}, 'soft': {'br': 20, 'r': 38, 'g': 254, 'b': 0, 'tf': 1, 'sp': 1}, 'colorful': {'br': 100, 'r': 255, 'g': 0, 'b': 0, 'tf': 1, 'sp': 1}, 'fwVersion': '1.5.1'} | 375
2023-01-30 12:00:06 [D] 10016c3439 <= Cloud3 | {'switch': 'off', 'ltype': 'leisure'} | 1675080006000
2023-01-30 12:00:06 [W] Cloud processing error|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 285, in run_forever|    await self._process_ws_msg(resp)|KeyError: 'leisure'|
2023-01-30 12:00:08 [D] CLOUD True => True

# From here on, I'm not getting any state updates via the cloud connection anymore.

2023-01-30 12:04:54 [D] 10016c3439 <= Local3 | {'switch': 'on', 'ltype': 'leisure', 'white': {'br': 70, 'ct': 29}, 'color': {'br': 22, 'r': 255, 'g': 215, 'b': 139}, 'bright': {'br': 100, 'ct': 100}, 'goodNight': {'br': 5, 'ct': 0}, 'read': {'br': 100, 'ct': 50}, 'nightLight': {'br': 1, 'ct': 0}, 'party': {'br': 45, 'r': 254, 'g': 132, 'b': 0, 'tf': 1, 'sp': 1}, 'leisure': {'br': 55, 'r': 0, 'g': 40, 'b': 254, 'tf': 1, 'sp': 1}, 'soft': {'br': 20, 'r': 38, 'g': 254, 'b': 0, 'tf': 1, 'sp': 1}, 'colorful': {'br': 100, 'r': 255, 'g': 0, 'b': 0, 'tf': 1, 'sp': 1}} | 376
2023-01-30 12:04:54 [D] 10016c3439 <= Local3 | {'switch': 'on', 'ltype': 'leisure', 'white': {'br': 70, 'ct': 29}, 'color': {'br': 22, 'r': 255, 'g': 215, 'b': 139}, 'bright': {'br': 100, 'ct': 100}, 'goodNight': {'br': 5, 'ct': 0}, 'read': {'br': 100, 'ct': 50}, 'nightLight': {'br': 1, 'ct': 0}, 'party': {'br': 45, 'r': 254, 'g': 132, 'b': 0, 'tf': 1, 'sp': 1}, 'leisure': {'br': 55, 'r': 0, 'g': 40, 'b': 254, 'tf': 1, 'sp': 1}, 'soft': {'br': 20, 'r': 38, 'g': 254, 'b': 0, 'tf': 1, 'sp': 1}, 'colorful': {'br': 100, 'r': 255, 'g': 0, 'b': 0, 'tf': 1, 'sp': 1}} | 377
2023-01-30 12:04:56 [D] 10016c3439 <= Local3 | {'switch': 'off', 'ltype': 'leisure', 'white': {'br': 70, 'ct': 29}, 'color': {'br': 22, 'r': 255, 'g': 215, 'b': 139}, 'bright': {'br': 100, 'ct': 100}, 'goodNight': {'br': 5, 'ct': 0}, 'read': {'br': 100, 'ct': 50}, 'nightLight': {'br': 1, 'ct': 0}, 'party': {'br': 45, 'r': 254, 'g': 132, 'b': 0, 'tf': 1, 'sp': 1}, 'leisure': {'br': 55, 'r': 0, 'g': 40, 'b': 254, 'tf': 1, 'sp': 1}, 'soft': {'br': 20, 'r': 38, 'g': 254, 'b': 0, 'tf': 1, 'sp': 1}, 'colorful': {'br': 100, 'r': 255, 'g': 0, 'b': 0, 'tf': 1, 'sp': 1}} | 378
2023-01-30 12:04:56 [D] 10016c3439 <= Local3 | {'switch': 'off', 'ltype': 'leisure', 'white': {'br': 70, 'ct': 29}, 'color': {'br': 22, 'r': 255, 'g': 215, 'b': 139}, 'bright': {'br': 100, 'ct': 100}, 'goodNight': {'br': 5, 'ct': 0}, 'read': {'br': 100, 'ct': 50}, 'nightLight': {'br': 1, 'ct': 0}, 'party': {'br': 45, 'r': 254, 'g': 132, 'b': 0, 'tf': 1, 'sp': 1}, 'leisure': {'br': 55, 'r': 0, 'g': 40, 'b': 254, 'tf': 1, 'sp': 1}, 'soft': {'br': 20, 'r': 38, 'g': 254, 'b': 0, 'tf': 1, 'sp': 1}, 'colorful': {'br': 100, 'r': 255, 'g': 0, 'b': 0, 'tf': 1, 'sp': 1}} | 379
2023-01-30 12:05:09 [D] 10016c3439 <= Local3 | {'switch': 'on', 'ltype': 'leisure', 'white': {'br': 70, 'ct': 29}, 'color': {'br': 22, 'r': 255, 'g': 215, 'b': 139}, 'bright': {'br': 100, 'ct': 100}, 'goodNight': {'br': 5, 'ct': 0}, 'read': {'br': 100, 'ct': 50}, 'nightLight': {'br': 1, 'ct': 0}, 'party': {'br': 45, 'r': 254, 'g': 132, 'b': 0, 'tf': 1, 'sp': 1}, 'leisure': {'br': 55, 'r': 0, 'g': 40, 'b': 254, 'tf': 1, 'sp': 1}, 'soft': {'br': 20, 'r': 38, 'g': 254, 'b': 0, 'tf': 1, 'sp': 1}, 'colorful': {'br': 100, 'r': 255, 'g': 0, 'b': 0, 'tf': 1, 'sp': 1}} | 380
2023-01-30 12:05:09 [D] 10016c3439 <= Local3 | {'switch': 'on', 'ltype': 'leisure', 'white': {'br': 70, 'ct': 29}, 'color': {'br': 22, 'r': 255, 'g': 215, 'b': 139}, 'bright': {'br': 100, 'ct': 100}, 'goodNight': {'br': 5, 'ct': 0}, 'read': {'br': 100, 'ct': 50}, 'nightLight': {'br': 1, 'ct': 0}, 'party': {'br': 45, 'r': 254, 'g': 132, 'b': 0, 'tf': 1, 'sp': 1}, 'leisure': {'br': 55, 'r': 0, 'g': 40, 'b': 254, 'tf': 1, 'sp': 1}, 'soft': {'br': 20, 'r': 38, 'g': 254, 'b': 0, 'tf': 1, 'sp': 1}, 'colorful': {'br': 100, 'r': 255, 'g': 0, 'b': 0, 'tf': 1, 'sp': 1}} | 381
2023-01-30 12:05:10 [D] 10016c3439 <= Local3 | {'switch': 'off', 'ltype': 'leisure', 'white': {'br': 70, 'ct': 29}, 'color': {'br': 22, 'r': 255, 'g': 215, 'b': 139}, 'bright': {'br': 100, 'ct': 100}, 'goodNight': {'br': 5, 'ct': 0}, 'read': {'br': 100, 'ct': 50}, 'nightLight': {'br': 1, 'ct': 0}, 'party': {'br': 45, 'r': 254, 'g': 132, 'b': 0, 'tf': 1, 'sp': 1}, 'leisure': {'br': 55, 'r': 0, 'g': 40, 'b': 254, 'tf': 1, 'sp': 1}, 'soft': {'br': 20, 'r': 38, 'g': 254, 'b': 0, 'tf': 1, 'sp': 1}, 'colorful': {'br': 100, 'r': 255, 'g': 0, 'b': 0, 'tf': 1, 'sp': 1}} | 382
2023-01-30 12:05:10 [D] 10016c3439 <= Local3 | {'switch': 'off', 'ltype': 'leisure', 'white': {'br': 70, 'ct': 29}, 'color': {'br': 22, 'r': 255, 'g': 215, 'b': 139}, 'bright': {'br': 100, 'ct': 100}, 'goodNight': {'br': 5, 'ct': 0}, 'read': {'br': 100, 'ct': 50}, 'nightLight': {'br': 1, 'ct': 0}, 'party': {'br': 45, 'r': 254, 'g': 132, 'b': 0, 'tf': 1, 'sp': 1}, 'leisure': {'br': 55, 'r': 0, 'g': 40, 'b': 254, 'tf': 1, 'sp': 1}, 'soft': {'br': 20, 'r': 38, 'g': 254, 'b': 0, 'tf': 1, 'sp': 1}, 'colorful': {'br': 100, 'r': 255, 'g': 0, 'b': 0, 'tf': 1, 'sp': 1}} | 383

```

Workaround - I put an `if effect in params:` guard around this block:

https://github.com/AlexxIT/SonoffLAN/blob/d9227bb637941cbed013b0b9f1082a1044ea4161/custom_components/sonoff/light.py#L435-L449

This solves the issue for me, but I'm not sure if it causes other issues.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.4.0

**Comment by rkistner** [comment]
Thanks!
