### ISSUE TITLE
IPv6 from mDNS

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/SonoffLAN#1098]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/yarl/_url.py", line 166, in __new__
    port = val.port
  File "/usr/local/lib/python3.10/urllib/parse.py", line 178, in port
    raise ValueError(message) from None
    ValueError: Port could not be cast to integer value as ':c6de:e2ff:fe11:1cac:8081'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 422, in _request
    url = self._build_url(str_or_url)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 356, in _build_url
    url = URL(str_or_url)
  File "/usr/local/lib/python3.10/site-packages/yarl/_url.py", line 168, in __new__
    raise ValueError(
    ValueError: Invalid URL: port can't be converted to integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/local.py", line 257, in send
    r = await self.session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 424, in _request
    raise InvalidURL(str_or_url) from e
    aiohttp.client_exceptions.InvalidURL: http://fe80::c6de:e2ff:fe11:1cac:8081/zeroconf/info
```

from this https://github.com/AlexxIT/SonoffLAN/issues/1090

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.4.0
