### ISSUE TITLE
Sonoff RF error: 'NoneType' object has no attribute 'bus'

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/SonoffLAN#1101]
```
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/local.py", line 221, in _process_zeroconf
    self.dispatcher_send(SIGNAL_UPDATE, msg)
  File "/config/custom_components/sonoff/core/ewelink/base.py", line 59, in dispatcher_send
    handler(*args, **kwargs)
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 242, in local_update
    self.dispatcher_send(did, params)
  File "/config/custom_components/sonoff/core/ewelink/base.py", line 59, in dispatcher_send
    handler(*args, **kwargs)
  File "/config/custom_components/sonoff/core/entity.py", line 108, in internal_update
    self.set_state(params)
  File "/config/custom_components/sonoff/remote.py", line 143, in set_state
    self.hass.bus.async_fire("sonoff.remote", data)
    AttributeError: 'NoneType' object has no attribute 'bus'
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.4.0
