### ISSUE TITLE
Integration still requires reloading after 3.4 release

### ISSUE THREAD

**Issue by madchap** [AlexxIT/SonoffLAN#1108]
Hello,

After the new [release](https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.4.0), hopes were up that it would [fix](https://github.com/AlexxIT/SonoffLAN/issues/1072#issuecomment-1418472295) my reload issues, but it didn't :-( So I am opening this issue to try to provide the right amount of details, even though it seems I don't have much to give at this point.

## General info

I am running the following on a RaspberryPi3.
```
OS Version:               Home Assistant OS 9.5
Home Assistant Core:      2023.2.2
```

This issue arose all of a sudden some time ago; [This issue](https://github.com/AlexxIT/SonoffLAN/issues/1072) was the one I saw already opened. None of the devices in the impacted list below had any firmware upgrade between the time it worked and the time it didn't anymore. However, Home Assistant updates happened fairly regularly, and sadly, I didn't write down HA versions :-/

Devices impacted by this issue are, all on latest firmwares:
- SonOff [ZBBridge](https://sonoff.tech/product/gateway-and-sensors/zbbridge/)
- 3 devices connected to the above:
  - 1 SonOff temperature sensor SNZB-02
  - 2 SonOff motion sensors SNZB-03 (ultimately driving lights)

## Subpar workaround

My current workaround, which is not perfect as it impedes some other automation, is the following automation to reload the integration every 2 minutes. Very often, the integration ceases to update within that time period:

```
alias: HACK - Force reload of SonOff integration
description: Force SonOff reloading
trigger:
  - platform: time_pattern
    minutes: /2
action:
  - service: shell_command.reload_sonoff_integration
    data: {}
mode: single
``` 

With the following shell script
```
#!/bin/bash
set -e

[[ -z $1 ]] && exit 1
INTEGRATION_ENTRY=$1
source /config/script_secrets
curl -XPOST -H "Authorization: Bearer ${BEARER_TOKEN}" http://192.168.10.168:8123/api/config/config_entries/entry/${INTEGRATION_ENTRY}/reload
```

## Update to 3.4

I updated this morning to 3.4 and restart HA. I disabled my workaround, but the same symptoms appeared immediately.

The diagnostic for the integration does not indicate anything special, except what seems to be a one-time error upon HA restart after the update. I'll still put it here, might be my weak raspberrypi could not cope with the restart load and processing the response... There is not any more occurence of it and if the integration is in "cloud" mode only, it goes and fetches with no error the devices from the cloud (even in auto mode, see below... but wanted to make sure it didn't get them locally by forcing the mode).

```
2023-02-06 15:26:04.001 WARNING (MainThread) [custom_components.sonoff] Can't login with mode: auto
Traceback (most recent call last):
  File "/config/custom_components/sonoff/__init__.py", line 198, in async_setup_entry
    await registry.cloud.login(username, password)
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 132, in login
    r = await self.session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 893, in start
    with self._timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
2023-02-06 15:26:04.023 WARNING (MainThread) [homeassistant.config_entries] Config entry 'xxxxxx@dxxxxxx.com' for sonoff integration not ready yet: None; Retrying in background
```

## Auto mode

I enabled debug more for the integration. A typical restart shows the following, no error:
```
2023-02-06 22:04:00 [D] CLOUD True => None
2023-02-06 22:04:01 [D] 18 devices loaded from Cloud
2023-02-06 22:04:01 [D] a480045bf0 UIID 1770 | {'subDevId': 'b4e4ce22004b12001770', 'parentid': '100155ebc5', 'battery': 100, 'supportPowConfig': 1, 'trigTime': '1675711617104', 'ASYNC': 2, 'temperature': '2222', 'humidity': '3256', 'switch': 'off', 'timeZone': 1}
2023-02-06 22:04:01 [D] a480045b42 UIID 2026 | {'subDevId': '8de8b423004b12002026', 'parentid': '100155ebc5', 'motion': 0, 'trigTime': '1675716235570', 'battery': 61, 'supportPowConfig': 1}
2023-02-06 22:04:01 [D] 100139e6ba UIID 0137 | {'version': 8, 'init': 1, 'fwVersion': '1000.2.1050', 'switch': 'off', 'colorR': 255, 'colorG': 0, 'colorB': 0, 'mode': 1, 'bright': 1, 'light_type': 1, 'timeZone': 1, 'lineSequence': {'1': 'b', '2': 'g', '3': 'r'}, 'speed27': 50, 'bright27': 50, 'speed28': 50, 'bright28': 50, 'speed29': 50, 'bright29': 50, 'speed30': 50, 'bright30': 50}
2023-02-06 22:04:01 [D] 100139ef32 UIID 0137 | {'version': 8, 'init': 1, 'fwVersion': '1000.2.1050', 'switch': 'off', 'colorR': 0, 'colorG': 0, 'colorB': 255, 'mode': 1, 'bright': 30, 'light_type': 1, 'speed27': 50, 'bright27': 50, 'speed28': 50, 'bright28': 50, 'speed29': 50, 'bright29': 50, 'speed30': 50, 'bright30': 50, 'timeZone': 1, 'lineSequence': {'1': 'b', '2': 'g', '3': 'r'}, 'NO_SEND_TO_APP': 0, 'speed14': 40, 'bright14': 50, 'speed07': 30, 'bright07': 70, 'speed18': 50, 'bright18': 50, 'speed20': 60, 'bright20': 85}
2023-02-06 22:04:01 [D] 1000cabd0f UIID 0001 | {'version': 8, 'sledOnline': 'on', 'switch': 'off', 'fwVersion': '2.9.0', 'rssi': -58, 'startup': 'off', 'init': 1, 'pulse': 'off', 'pulseWidth': 500}
2023-02-06 22:04:01 [D] 1001100395 UIID 0059 | {'version': 8, 'only_device': {'ota': 'success'}, 'sledOnline': 'on', 'rssi': -70, 'fwVersion': '3.4.3', 'switch': 'on', 'light_type': 1, 'colorR': 255, 'colorG': 96, 'colorB': 175, 'bright': 82, 'mode': 1, 'speed': 100, 'sensitive': 10}
2023-02-06 22:04:01 [D] a480037c1a UIID 2026 | {'subDevId': 'bdf81b25004b12002026', 'parentid': '100155ebc5', 'motion': 0, 'trigTime': '1675716238599', 'battery': 100, 'supportPowConfig': 1}
2023-02-06 22:04:01 [D] 1000bfaed8 UIID 0001 | {'version': 8, 'sledOnline': 'on', 'switch': 'off', 'fwVersion': '3.5.1', 'rssi': -70, 'startup': 'off', 'init': 1, 'pulse': 'off', 'pulseWidth': 500, 'only_device': {'ota': 'success'}}
2023-02-06 22:04:01 [D] 100155ebc5 UIID 0066 | {'version': 8, 'subDevNum': 3, 'subDevMaxNum': 32, 'sledOnline': 'on', 'zled': 'off', 'fwVersion': '1.7.0', 'subDevices': [{'subDevId': 'bdf81b25004b12002026', 'deviceid': 'a480037c1a', 'uiid': '2026', 'index': 0}, {'subDevId': '8de8b423004b12002026', 'deviceid': 'a480045b42', 'uiid': '2026', 'index': 0}, {'subDevId': 'b4e4ce22004b12001770', 'deviceid': 'a480045bf0', 'uiid': '1770', 'index': 0}], 'rssi': -75, 'only_device': {'ota': 'success'}, 'addSubDevState': 'off', 'addDevTime': 180, 'timeZone': 1}
2023-02-06 22:04:01 [D] 1000dc0dbb UIID 0077 | {'version': 8, 'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'lock': 0, 'sledOnline': 'on', 'rssi': -69, 'fwVersion': '3.7.1', 'senMode': {'enabled': 0, 'dTime': 10, 'tUnit': 's', 'outlets': [0, 1, 2, 3], 'effectives': [{'outlet': 0, 'enabled': 0, 'days': [0, 1, 2, 3, 4, 5, 6], 'effIndex': [{'index': 0, 'enabled': 1, 'from': '00:00', 'to': '23:59'}, {'index': 1, 'enabled': 0, 'from': '00:00', 'to': '23:59'}]}, {'outlet': 1, 'enabled': 0, 'days': [0, 1, 2, 3, 4, 5, 6], 'effIndex': [{'index': 0, 'enabled': 1, 'from': '00:00', 'to': '23:59'}, {'index': 1, 'enabled': 0, 'from': '00:00', 'to': '23:59'}]}, {'outlet': 2, 'enabled': 0, 'days': [0, 1, 2, 3, 4, 5, 6], 'effIndex': [{'index': 0, 'enabled': 1, 'from': '00:00', 'to': '23:59'}, {'index': 1, 'enabled': 0, 'from': '00:00', 'to': '23:59'}]}, {'outlet': 3, 'enabled': 0, 'days': [0, 1, 2, 3, 4, 5, 6], 'effIndex': [{'index': 0, 'enabled': 1, 'from': '00:00', 'to': '23:59'}, {'index': 1, 'enabled': 0, 'from': '00:00', 'to': '23:59'}]}]}, 'savMode': {'enabled': 0, 'dTime': 1, 'tUnit': 'm', 'outlets': [0, 1, 2, 3]}, 'alertMode': {'enabled': 0}, 'selfApikey': '2dd39e99-e9af-4341-afdd-3b4a6d32fc4d'}
[... removed Hue stuff ...]
2023-02-06 22:04:01 [D] AUTO mode start
2023-02-06 22:04:01 [D] 1000bfaed8 <= Local3 | {'switch': 'off', 'startup': 'off', 'pulse': 'off', 'pulseWidth': 500, 'rssi': -70} | 26
2023-02-06 22:04:01 [D] 1000cabd0f <= Local3 | {'switch': 'off', 'startup': 'off', 'pulse': 'off', 'sledOnline': 'on', 'pulseWidth': 500, 'rssi': -58} | 4
2023-02-06 22:04:01 [D] CLOUD None => True
2023-02-06 22:04:01 [D] Add 35 entities
```

As I've just tested it, there appears to be no error in the HA log nor the debug log of the integration now... :-/
It all just fails silently.

## Cloud mode
Same symptoms as auto mode.

## Local mode
I guess the first weird thing to me is that, upon enabling this mode, it still goes to load from cloud anyways, before "LOCAL mode start".

Outside of that, the devices show as "unavailable".

```
2023-02-06 22:29:13 [D] CLOUD True => None
2023-02-06 22:29:14 [D] 18 devices loaded from Cloud
2023-02-06 22:29:14 [D] a480045bf0 UIID 1770 | {'subDevId': 'b4e4ce22004b12001770', 'parentid': '100155ebc5', 'battery': 100, 'supportPowConfig': 1, 'trigTime': '1675718815574', 'ASYNC': 2, 'temperature': '2202', 'humidity': '3148', 'switch': 'off', 'timeZone': 1}
2023-02-06 22:29:14 [D] a480045b42 UIID 2026 | {'subDevId': '8de8b423004b12002026', 'parentid': '100155ebc5', 'motion': 0, 'trigTime': '1675716235570', 'battery': 61, 'supportPowConfig': 1}
2023-02-06 22:29:14 [D] 100139e6ba UIID 0137 | {'version': 8, 'init': 1, 'fwVersion': '1000.2.1050', 'switch': 'off', 'colorR': 255, 'colorG': 0, 'colorB': 0, 'mode': 1, 'bright': 1, 'light_type': 1, 'timeZone': 1, 'lineSequence': {'1': 'b', '2': 'g', '3': 'r'}, 'speed27': 50, 'bright27': 50, 'speed28': 50, 'bright28': 50, 'speed29': 50, 'bright29': 50, 'speed30': 50, 'bright30': 50}
2023-02-06 22:29:14 [D] 100139ef32 UIID 0137 | {'version': 8, 'init': 1, 'fwVersion': '1000.2.1050', 'switch': 'off', 'colorR': 0, 'colorG': 0, 'colorB': 255, 'mode': 1, 'bright': 30, 'light_type': 1, 'speed27': 50, 'bright27': 50, 'speed28': 50, 'bright28': 50, 'speed29': 50, 'bright29': 50, 'speed30': 50, 'bright30': 50, 'timeZone': 1, 'lineSequence': {'1': 'b', '2': 'g', '3': 'r'}, 'NO_SEND_TO_APP': 0, 'speed14': 40, 'bright14': 50, 'speed07': 30, 'bright07': 70, 'speed18': 50, 'bright18': 50, 'speed20': 60, 'bright20': 85}
2023-02-06 22:29:14 [D] 1000cabd0f UIID 0001 | {'version': 8, 'sledOnline': 'on', 'switch': 'off', 'fwVersion': '2.9.0', 'rssi': -58, 'startup': 'off', 'init': 1, 'pulse': 'off', 'pulseWidth': 500}
2023-02-06 22:29:14 [D] 1001100395 UIID 0059 | {'version': 8, 'only_device': {'ota': 'success'}, 'sledOnline': 'on', 'rssi': -70, 'fwVersion': '3.4.3', 'switch': 'on', 'light_type': 1, 'colorR': 255, 'colorG': 96, 'colorB': 175, 'bright': 82, 'mode': 1, 'speed': 100, 'sensitive': 10}
2023-02-06 22:29:14 [D] a480037c1a UIID 2026 | {'subDevId': 'bdf81b25004b12002026', 'parentid': '100155ebc5', 'motion': 1, 'trigTime': '1675718892117', 'battery': 100, 'supportPowConfig': 1}
2023-02-06 22:29:14 [D] 1000bfaed8 UIID 0001 | {'version': 8, 'sledOnline': 'on', 'switch': 'off', 'fwVersion': '3.5.1', 'rssi': -70, 'startup': 'off', 'init': 1, 'pulse': 'off', 'pulseWidth': 500, 'only_device': {'ota': 'success'}}
2023-02-06 22:29:14 [D] 100155ebc5 UIID 0066 | {'version': 8, 'subDevNum': 3, 'subDevMaxNum': 32, 'sledOnline': 'on', 'zled': 'off', 'fwVersion': '1.7.0', 'subDevices': [{'subDevId': 'bdf81b25004b12002026', 'deviceid': 'a480037c1a', 'uiid': '2026', 'index': 0}, {'subDevId': '8de8b423004b12002026', 'deviceid': 'a480045b42', 'uiid': '2026', 'index': 0}, {'subDevId': 'b4e4ce22004b12001770', 'deviceid': 'a480045bf0', 'uiid': '1770', 'index': 0}], 'rssi': -75, 'only_device': {'ota': 'success'}, 'addSubDevState': 'off', 'addDevTime': 180, 'timeZone': 1}
2023-02-06 22:29:14 [D] 1000dc0dbb UIID 0077 | {'version': 8, 'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'lock': 0, 'sledOnline': 'on', 'rssi': -69, 'fwVersion': '3.7.1', 'senMode': {'enabled': 0, 'dTime': 10, 'tUnit': 's', 'outlets': [0, 1, 2, 3], 'effectives': [{'outlet': 0, 'enabled': 0, 'days': [0, 1, 2, 3, 4, 5, 6], 'effIndex': [{'index': 0, 'enabled': 1, 'from': '00:00', 'to': '23:59'}, {'index': 1, 'enabled': 0, 'from': '00:00', 'to': '23:59'}]}, {'outlet': 1, 'enabled': 0, 'days': [0, 1, 2, 3, 4, 5, 6], 'effIndex': [{'index': 0, 'enabled': 1, 'from': '00:00', 'to': '23:59'}, {'index': 1, 'enabled': 0, 'from': '00:00', 'to': '23:59'}]}, {'outlet': 2, 'enabled': 0, 'days': [0, 1, 2, 3, 4, 5, 6], 'effIndex': [{'index': 0, 'enabled': 1, 'from': '00:00', 'to': '23:59'}, {'index': 1, 'enabled': 0, 'from': '00:00', 'to': '23:59'}]}, {'outlet': 3, 'enabled': 0, 'days': [0, 1, 2, 3, 4, 5, 6], 'effIndex': [{'index': 0, 'enabled': 1, 'from': '00:00', 'to': '23:59'}, {'index': 1, 'enabled': 0, 'from': '00:00', 'to': '23:59'}]}]}, 'savMode': {'enabled': 0, 'dTime': 1, 'tUnit': 'm', 'outlets': [0, 1, 2, 3]}, 'alertMode': {'enabled': 0}, 'selfApikey': '2dd39e99-e9af-4341-afdd-3b4a6d32fc4d'}
[ ... hue stuff ... ]
2023-02-06 22:29:14 [D] LOCAL mode start
2023-02-06 22:29:14 [D] 1000cabd0f <= Local3 | {'switch': 'off', 'startup': 'off', 'pulse': 'off', 'sledOnline': 'on', 'pulseWidth': 500, 'rssi': -58} | 4
2023-02-06 22:29:14 [D] 1000cabd0f <= Local3 | {'switch': 'off', 'startup': 'off', 'pulse': 'off', 'sledOnline': 'on', 'pulseWidth': 500, 'rssi': -58} | 4
2023-02-06 22:29:14 [D] 1000bfaed8 <= Local3 | {'switch': 'off', 'startup': 'off', 'pulse': 'off', 'pulseWidth': 500, 'rssi': -70} | 26
2023-02-06 22:29:14 [D] 1000bfaed8 <= Local3 | {'switch': 'off', 'startup': 'off', 'pulse': 'off', 'pulseWidth': 500, 'rssi': -70} | 26
2023-02-06 22:29:17 [D] Add 35 entities
```

If there is anything more I can do to provide information, please let me know how, I'll definitely get to it.

Cheers.

**Comment by roscio1975** [comment]
Same here with 3 ZIGBEE_DOOR_AND_WINDOW_SENSOR

**Comment by EyalRotem** [comment]
I have the same issue with a temperature sensor connected to TH10. local mode.

**Comment by ZainAjam** [comment]
I haven't noticed this until today when I put my Home Assistant Raspberry Pi on a mini UPS that keeps it powered on all the time. I have multiple power outs per day in my country and I put the Pi on UPS so that I didn't have to wait each time for the Pi to boot up to get control of my sonoff lights and devices when power restores. Now the problem is that power restores and my sonoff devices get power and go online, it does not inform home assistant that its state changed from unavailable to on. Previously when I wasn't using a UPS on the Pi, the Pi would power on alongside the sonoff devices and presumably would run the integration reload on boot so I it would always refresh on each Pi boot. Now that my Pi stays on 24/7, the sonoff reload not working is obvious

**Comment by roscio1975** [comment]
After 2 days I could say that that problem is quite different apart the error that is the same:
        ```
"exception": "Traceback (most recent call last):\n  File \"/config/custom_components/sonoff/core/ewelink/cloud.py\", line 318, in connect\n    raise Exception(resp)\nException: {'error': 406, 'apikey': 'b1552c13-f6d1-4993-b7b8-fe81f07407a0', 'sequence': '1675840624863', 'actionName': 'userOnline'}\n",
        "count": 3,
        "first_occurred": 1675840624.8961823
      }
    ],
    "device": {
      "uiid": 3026,
      "params": {
        "bindInfos": "***",
        "subDevId": "87ae9028004b12003026",
        "parentid": "1001703423",
        "lock": 0,
        "trigTime": "1675837586829",
        "battery": 100,
        "supportPowConfig": 1
      },
      "model": "ZIGBEE_DOOR_AND_WINDOW_SENSOR",
      "online": true,
      "localtype": null,
      "host": null,
      "deviceid": "a48004640f"
    }
```
The issue occurs only after a restart and, restarting again it works fine

**Comment by EyalRotem** [comment]
> have

This is actually something I encounter too. Many power outages caused a lot of issues so I put a ups as well and am seeing the Sensor unavailable until reloading the integration

**Comment by AlexxIT** [comment]
ZBBridge works only via cloud. There may be a problem with automatically reconnecting to the cloud if the cloud returns errors. I will check this point.

**Comment by bax137** [comment]
I think I have the same problem since the upgrade to the v3.4.0 I did yesterday.
Approximately 1 hour after the restart of the integration, the entities are suddenly no more available (I have a RF Bridge 433 and a remote) and I found that in the debug log:
2023-02-08 10:10:32 [D] 1000f22239 <= Local0 | {'online': False} | 
2023-02-08 10:10:43 [D] 1000f22239 => Local4 | {'cmd': 'info'} !! Timeout 10
2023-02-08 10:10:43 [D] 1000f22239 !! Local4 | Device offline

and in the config-entry file, the ip in the host field is replaced by "null" (the ip is correct after the restart):
        "model": "RFBridge433",
        "online": true,
        "localtype": "rf",
        "host": null

I have to reload the integration, but 1 hour after the problem occurs again.

(I did also a firmware upgrade of the bridge yesterday, but with no impact on the problem)

**Comment by madchap** [comment]
@AlexxIT if you tell me what debug statements to put in `cloud.py` or others, I'll update the scripts manually to help out.

**Comment by malatg** [comment]
I have the same issue. Before latest upgrade the sonoff integration was rock solid but now I have to restart it all the time to reconnect to all my devices. I only run in local mode.

**Comment by CatalinPuscoci** [comment]
I have it configured in local mode and they always go unresponsive after 10-15 minutes until I toggle a device in the app. Reloading also works if cloud is enabled, but not with local. Local only cares if you recently used the ewelink phone app.

It's hella weird

**Comment by Cippo2019** [comment]
Hi @AlexxIT  do you have some news about this strange problem ? or did you have change to check the errors ? just to know if the problem is for all and you suggest to wait before install to latest release or if we can go ahed due to only some installation are afftected.
wbr

**Comment by rumianoesa** [comment]
I have the same issue after updating to 3.4.0. I roll back to 3.3.1, and it works fine.

**Comment by KaportsevIA** [comment]
А у меня после обновления стала отваливаться реле RE5V1C. Причем спонтанно. Пробовал и авто режим, и локальный. Время до отвала от 10 минут до 1,5часов.

**Comment by Sergeyss2022** [comment]
> I have the same issue after updating to 3.4.0. I roll back to 3.3.1, and it works fine.

How to roll back correctly so as not to break it?

**Comment by heidricha** [comment]
I didn't have this issue with the previous version. I mean not in the last few months (when I started using the whole Sonoff stuff, I experienced it a few times). It is unusable at the moment, the heating fails at least once every day.

I use one 4ch and one 4chpro, local, or auto mode.

Considering rolling back one minor version at least.

**Comment by heidricha** [comment]
OMG! Issue is still with me after downgrading to 3.3.1

My devices run with factory firmware. It has been upgraded the other day to 3.6 - but the issue appeared with SonoffLAN 3.4 with the same (3.5.1) fw version on the devices

It is getting worse, as I see...

:(

**Comment by heidricha** [comment]
Just a small question: how many of the affected users use fixed IP address for the Sonoff devices?

I just fixed the IPs for the 4ch-r3 devices in the router, and no unavailability issue occurred since then. It hasn't been a long ago, so it't way too early to say, this was the solution, but I'm interested in your configuration.

**Comment by ZainAjam** [comment]
I don't fix my IP addresses

**Comment by heidricha** [comment]
I got disconnected with 3.3.1 version and fix IP addresses too. ewelink app doesn't complain a word, but it doesn't look like an integration version issue to me.

**Comment by CatalinPuscoci** [comment]
manually downgrading to 3.3.0 seems to have fixed most issues for me so far (auto mode with mDNS working)

**Comment by chemelli74** [comment]
Hi,

using HACS to downgrade to 3.3.1 fixed the issue here for more than 48hours but now is unavailable again.

Cheers,

Simone

**Comment by andrewbeyou88** [comment]
Mine are becoming unavailable every 2 hours since Home Assistant 2023.2.5 update.

**Comment by Cippo2019** [comment]
> Hi @AlexxIT do you have some news about this strange problem ? or did you have change to check the errors ? just to know if the problem is for all and you suggest to wait before install to latest release or if we can go ahed due to only some installation are afftected. wbr

@AlexxIT sorry for my second question, but just to know if it is better wait for a fix :-)
thanks a lot fr your effort on that. :-)

**Comment by heidricha** [comment]
after I deleted the integraton (id didn't actually delete it, just the configuration), the device data got refreshed, now I have got the home selection part. after I selected the home, I have no getting online errors.

devices doesn't always work in auto mode, go off-sync from the cloud state (uncontrollable from HA, while works in the eWelink app...), but it's ok using LAN mode, so I thing this solved the current issue for me (it was last afternoon, so fingers crossed)

**Comment by barto64** [comment]
I remove the integration and add it again. After a few hours all devices seem to be working fine. Even the missing option to check the home appeared. So far so good ....

**Comment by wheeller123** [comment]
I had the same issue with my zigby thermometer. Using the homeassistant.reload_config_entry service I am able force an update every 10 minutes. Hope it helps 

alias: "Update Office Thermometer "
description: Every 10 mins
trigger:
  - platform: time_pattern
    minutes: "10"
condition: []
action:
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      entity_id: sensor.sonoff_a48004e00b_temperature
mode: single

**Comment by heidricha** [comment]
I'm desperate now... This bug makes the whole system unusable. It is off-sync right now, shows one switch On, while it's off... Ewelink status is ok. Sometimes just doesn't do the required operation, leaves heater on/off, doesn't show operations in the log...

I try to reload the config on schedule, but have no idea what's next.

**Comment by andrewbeyou88** [comment]
Just download v3.3.0 version, this will fix the problems for now until is gonna fix it. Mine is working ok now.

**Comment by CatalinPuscoci** [comment]
> Just download v3.3.0 version, this will fix the problems for now until is gonna fix it. Mine is working ok now.

That's what fixed it for me

**Comment by heidricha** [comment]
> Just download v3.3.0 version, this will fix the problems for now until is gonna fix it. Mine is working ok now.

Thanks, I'll try it. Again... once I already thougth I did it (HACS: reinstall with selected version), but looks like I have to
- remove the configuration
- remove the integration
- install the selected version
Now it is 3.3.0 as it is shown in the debug log (also HACS alerts me, that there are upgrades), let's see, what's about to happen!

**Comment by andrewbeyou88** [comment]
I pressed download version 3.3.0, no changes no headache

**Comment by heidricha** [comment]
> 

good for you. 
:)

it was different for me.

**Comment by madchap** [comment]
Reverting back to 3.3.0 seems to be positive for me too... it's been a few hours now that I didn't have to reload and things seems to still work.

**Comment by Sergeyss2022** [comment]
Также перешёл на 3.3.0. Всё работает.

**Comment by heidricha** [comment]
Also got a falso offline with 3.3.0. Never happened before I tried 3.4

**Comment by Sergeyss2022** [comment]
Уже 3 дня полёт нормальный. Удалил интеграцию со всеми сущностями. Заново установил и всё.

**Comment by wheeller123** [comment]
Issue hasn't happened to me for 3 days now since changing to 3.3.0 thanks 👍

**Comment by madchap** [comment]
Still on 3.3.0, since my last comment no issue. Just updated HA to 2023.3.1 a few hours ago… and the problem is back. 100% correlation.

**Comment by madchap** [comment]
I am notvsure why it would make a difference honestly, but updated to 3.4.0, restarted HA, downgraded back to 3.3.0, restarted HA, and it seems it just held the night.

**Comment by thefunkygibbon** [comment]
hey all, a great workaround since this issue doesn't appear to be being worked on,  is to create an automation to monitor a sonoff device and restart the service automatically.  its not a perfect solution but hopefully it should make the devices work for "most" of the time. 
https://github.com/AlexxIT/SonoffLAN/issues/1138#issuecomment-1478580171

**Comment by AlexxIT** [comment]
@madchap you need to collect more logs. Few seconds are not very helpful.

**Comment by AlexxIT** [comment]
@bax137 you have this problem https://github.com/AlexxIT/SonoffLAN/issues/1126

**Comment by AlexxIT** [comment]
@roscio1975 some problems with cloud servers, integration can't do anything about it
https://coolkit-technologies.github.io/eWeLink-API/#/en/APICenterV2?id=general-error-codes

**Comment by AlexxIT** [comment]
@heidricha you have auto mode, but cloud doesn't work for you for some reason. Anyway v3.5.0 should helps in this situation.

**Comment by jopen-ux** [comment]
Issue always there !! Currently in 3.5.3 (hass.io integration) . I have to reload the integration from time to time. Works sometimes during 3 days, then stop, reload, stop again 4 hours after, reload,...

**Comment by 70nyIT** [comment]
If there's a way I could help let me know. I have the same issue - noted with SNZB-03 (sensor movement) that after a while stays in "no detection" mode forever

**Comment by AlexxIT** [comment]
The cloud can constantly drop your connection when you use one account in 2 places. Two Hass. Or Hass and some other software.

**Comment by 70nyIT** [comment]
I think that best suggestion is what I've already read here (or somewhere else): if you have already devices set up in one account, create a second eWeLink account and share the devices with that.
