### ISSUE TITLE
Versions > 3.2.0 broken: keep loosing connection to devices

### ISSUE THREAD

**Issue by unlucio** [AlexxIT/SonoffLAN#1138]
Hello,
thanks for the great work as this integration worked like a charm for years, yet it's having a bit of troubled last versions:

Every release in the last ~6-to-7 months has had the unfortunate yet annoying issue of randomly loosing connection to all, or some, of my sonoff-mini (I have no other sonoff stuff in my house), and the only way to get them back is to restart the whole `HA` instance.

Every time I update I have to rollback to 3.2, or I have to keep restarting HA (not a good option, imho) in order to be able to use my house, which is a bit suboptimal 😅

Here are the the latest error logs from 3.4:

```
2023-03-15 18:40:55.964 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.display_center: Skipping sensor setup Model not found in library (manufacturer: Govee, model: H6110)
2023-03-15 18:40:55.971 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.display_center: Skipping sensor setup: Model not found in library (manufacturer: Govee, model: H6110)
2023-03-15 18:40:55.973 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.display_left: Skipping sensor setup Model not found in library (manufacturer: Govee, model: H6110)
2023-03-15 18:40:55.975 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.display_left: Skipping sensor setup: Model not found in library (manufacturer: Govee, model: H6110)
2023-03-15 18:40:55.976 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.display_right: Skipping sensor setup Model not found in library (manufacturer: Govee, model: H6110)
2023-03-15 18:40:55.978 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.display_right: Skipping sensor setup: Model not found in library (manufacturer: Govee, model: H6110)
2023-03-15 18:40:55.980 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.piano_table: Skipping sensor setup Model not found in library (manufacturer: Govee, model: H6159)
2023-03-15 18:40:55.981 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.piano_table: Skipping sensor setup: Model not found in library (manufacturer: Govee, model: H6159)
2023-03-15 18:40:55.991 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.sonoff_mini_anteroom: Skipping sensor setup Model not found in library (manufacturer: SONOFF, model: MINI)
2023-03-15 18:40:55.992 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.sonoff_mini_anteroom: Skipping sensor setup: Model not found in library (manufacturer: SONOFF, model: MINI)
2023-03-15 18:40:55.994 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.sonoff_mini_bathroom: Skipping sensor setup Model not found in library (manufacturer: SONOFF, model: MINI)
2023-03-15 18:40:55.995 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.sonoff_mini_bathroom: Skipping sensor setup: Model not found in library (manufacturer: SONOFF, model: MINI)
2023-03-15 18:40:55.997 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.sonoff_mini_bedroom_parentheses: Skipping sensor setup Model not found in library (manufacturer: SONOFF, model: MINI)
2023-03-15 18:40:55.999 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.sonoff_mini_bedroom_parentheses: Skipping sensor setup: Model not found in library (manufacturer: SONOFF, model: MINI)
2023-03-15 18:40:56.000 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.sonoff_mini_entrance: Skipping sensor setup Model not found in library (manufacturer: SONOFF, model: MINI)
2023-03-15 18:40:56.002 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.sonoff_mini_entrance: Skipping sensor setup: Model not found in library (manufacturer: SONOFF, model: MINI)
2023-03-15 18:40:56.003 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.sonoff_mini_kitchen_center: Skipping sensor setup Model not found in library (manufacturer: SONOFF, model: MINI)
2023-03-15 18:40:56.005 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.sonoff_mini_kitchen_center: Skipping sensor setup: Model not found in library (manufacturer: SONOFF, model: MINI)
2023-03-15 18:40:56.006 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.sonoff_mini_kitchen_columns: Skipping sensor setup Model not found in library (manufacturer: SONOFF, model: MINI)
2023-03-15 18:40:56.008 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.sonoff_mini_kitchen_columns: Skipping sensor setup: Model not found in library (manufacturer: SONOFF, model: MINI)
2023-03-15 18:40:56.010 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.sonoff_mini_livingroom_led_row_1: Skipping sensor setup Model not found in library (manufacturer: SONOFF, model: MINI)
2023-03-15 18:40:56.011 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.sonoff_mini_livingroom_led_row_1: Skipping sensor setup: Model not found in library (manufacturer: SONOFF, model: MINI)
2023-03-15 18:40:56.013 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.sonoff_mini_livingroom_led_row_2: Skipping sensor setup Model not found in library (manufacturer: SONOFF, model: MINI)
2023-03-15 18:40:56.014 ERROR (MainThread) [custom_components.powercalc.sensors.power] light.sonoff_mini_livingroom_led_row_2: Skipping sensor setup: Model not found in library (manufacturer: SONOFF, model: MINI)
2023-03-15 18:40:58.558 ERROR (MainThread) [homeassistant.components.binary_sensor] rpi_power: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 732, in async_device_update
    await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/rpi_power/binary_sensor.py", line 52, in update
    value = self._under_voltage.get()
AttributeError: 'NoneType' object has no attribute 'get'
```

I'd be awesome if it'd be back to be reliable, and thus being able to safely update again.

**Comment by unlucio** [comment]
Actually neither 3.2.0 works, I just had to downgrade to 3.1 :(

**Comment by federicosantolini** [comment]
Same issue here but I cannot downgrade to 3.1. It just fails to work

**Comment by unlucio** [comment]
Actually now I'm having the same problem with 3.1 as well.
And nothing useful in the logs: grepping for "sonoff" it only gives what I'v already posted, and it has nothing to do with this.

This is getting a bit of a pickle since I've to keep checking and restarting HA to get the lights back up, and my family is getting (understandably) very very frustrated by lights randomly not working.

Suggestions form someone of the team would be greatly appreciated.

**Comment by unlucio** [comment]
@Darren-Hill that's def a good idea for a momentary patch (and I just put it in place for ease of life).
But still I think there's a bug somewhere that unfortunately no log seems to evidence.

**Comment by thefunkygibbon** [comment]
this is great and needs to be more visible over the numerous posts on this issue. 
Its a little concerning that none of the devs have piped up and commented on any of them over the few months this has been an issue. 
but this is a lifesaver.  I didn't know you could restart the service if it was detected unavailable, but of course that makes perfect sense! thank you so much, I can now have a nice warm office in the mornings again.

**Comment by AlexxIT** [comment]
@unlucio all your log not related to this integration. Snow device diagnostics from any sonoff device.
