### ISSUE TITLE
Bad status line 'Invalid method encountered

### ISSUE THREAD

**Issue by pniewiadowski** [AlexxIT/SonoffLAN#1193]
Few days back my Sonoff Micro stoped working. Once I reload integration this appear in HA logs:

```
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:403
First occurred: 9:57:06 PM (60 occurrences)
Last logged: 10:02:03 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"

```
Is it only me, or anybody else also encounter that issue?

**Comment by AlexxIT** [comment]
This code not related to integration
