### ISSUE TITLE
Sonoff after restart HA fail to configure

### ISSUE THREAD

**Issue by liamlain** [AlexxIT/SonoffLAN#1202]
The Sonoff intergation was no problem until i restart my HA ,it showing RECONFIGURE
But when when login my id and pwd it showing like pic i attatched below:
![image](https://github.com/AlexxIT/SonoffLAN/assets/93088569/f6dd3d55-c418-457c-a673-ef787007dd1a)

Attached log:

This error originated from a custom integration.

Logger: custom_components.sonoff
Source: custom_components/sonoff/core/ewelink/cloud.py:150
Integration: Sonoff (documentation, issues)
First occurred: 1:12:38 PM (1 occurrences)
Last logged: 1:12:38 PM

Can't login with mode: auto
Traceback (most recent call last):
  File "/config/custom_components/sonoff/__init__.py", line 206, in async_setup_entry
    await registry.cloud.login(username, password)
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 150, in login
    raise AuthError(resp["msg"])
custom_components.sonoff.core.ewelink.cloud.AuthError: appid is unauthorized! KOBxGJna5qkk3JLXw3LHLX3wSNiPjAVi

Logger: homeassistant.config_entries
Source: config_entries.py:414
First occurred: 1:12:38 PM (1 occurrences)
Last logged: 1:12:38 PM

Config entry 'Sonoff' for sonoff integration could not authenticate: appid is unauthorized! KOBxGJna5qkk3JLXw3LHLX3wSNiPjAVi

**Comment by gregcsw** [comment]
Also getting exactly the same error.

**Comment by yousaf465** [comment]
getting same error after restart.

**Comment by csc003** [comment]
Just had the same issue.

DId the line changing edit (line 107 and 157) in the /custom_components/sonoff/core/ewelink/cloud.py restarted HA and all good now

 https://github.com/AlexxIT/SonoffLAN/issues/887

**Comment by jordisco** [comment]
You have to reconfigure the addon using only your email, leave the password blank, it has worked for me.

**Comment by liamlain** [comment]
after edited line 107 and 157) in the /custom_components/sonoff/core/ewelink/cloud.py restarted HA
my devices become Unavailable like pic show 

![image](https://github.com/AlexxIT/SonoffLAN/assets/93088569/95b7f8c3-2c72-4897-ba5c-3509159b2593)

**Comment by liamlain** [comment]
2023-07-26 14:50:58 [D] SysInfo: {'installation_type': 'Home Assistant OS', 'version': '2023.7.1', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.11.4', 'docker': True, 'arch': 'aarch64', 'timezone': ', 'os_name': 'Linux', 'os_version': '6.1.21-v8', 'user': 'root', 'supervisor': '2023.07.1', 'host_os': 'Home Assistant OS 10.3', 'docker_version': '23.0.6', 'chassis': 'embedded', 'sonoff_version': '3.5.1 (5b48a81)'}
2023-07-26 14:51:09 [D] 0 devices loaded from Cloud
2023-07-26 14:51:20 [D] AUTO mode start
2023-07-26 14:51:21 [D] CLOUD None => True
2023-07-26 14:51:24 [D] 10016bb404 !! skip setup for encrypted device
2023-07-26 15:00:14 [D] CLOUD True => None
2023-07-26 15:00:14 [W] Can't load devices|  File "/config/custom_components/sonoff/__init__.py", line 242, in internal_normal_setup|    devices = await registry.cloud.get_devices(homes)|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^|Exception: cannot found access token info|
2023-07-26 15:00:14 [D] AUTO mode start
2023-07-26 15:00:14 [D] 10016bb404 !! skip setup for encrypted device
2023-07-26 15:00:14 [E] Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 322, in connect|    raise Exception(resp)|Exception: {'error': 406, 'reason': 'Authentication Failed', 'apikey': '1ad9b710-c23d-44a6-8eb9-7803b327db1b', 'sequence': '1690354814904', 'actionName': 'userOnline'}|
2023-07-26 15:00:14 [D] CLOUD None => False
2023-07-26 15:00:14 [D] Cloud connection retrying in 15 seconds
2023-07-26 15:00:30 [E] Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 322, in connect|    raise Exception(resp)|Exception: {'error': 406, 'reason': 'Authentication Failed', 'apikey': '1ad9b710-c23d-44a6-8eb9-7803b327db1b', 'sequence': '1690354830103', 'actionName': 'userOnline'}|
2023-07-26 15:00:30 [D] CLOUD False => False
2023-07-26 15:00:30 [D] Cloud connection retrying in 60 seconds
2023-07-26 15:01:30 [E] Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 322, in connect|    raise Exception(resp)|Exception: {'error': 406, 'reason': 'Authentication Failed', 'apikey': '1ad9b710-c23d-44a6-8eb9-7803b327db1b', 'sequence': '1690354890314', 'actionName': 'userOnline'}|
2023-07-26 15:01:30 [D] CLOUD False => False
2023-07-26 15:01:30 [D] Cloud connection retrying in 300 seconds
2023-07-26 15:06:30 [E] Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 322, in connect|    raise Exception(resp)|Exception: {'error': 406, 'reason': 'Authentication Failed', 'apikey': '1ad9b710-c23d-44a6-8eb9-7803b327db1b', 'sequence': '1690355190794', 'actionName': 'userOnline'}|
2023-07-26 15:06:30 [D] CLOUD False => False
2023-07-26 15:06:30 [D] Cloud connection retrying in 900 seconds
2023-07-26 15:06:31 [D] CLOUD False => None
2023-07-26 15:06:31 [W] Can't load devices|  File "/config/custom_components/sonoff/__init__.py", line 242, in internal_normal_setup|    devices = await registry.cloud.get_devices(homes)|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^|Exception: cannot found access token info|
2023-07-26 15:06:31 [D] AUTO mode start
2023-07-26 15:06:31 [E] Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 322, in connect|    raise Exception(resp)|Exception: {'error': 406, 'reason': 'Authentication Failed', 'apikey': '1ad9b710-c23d-44a6-8eb9-7803b327db1b', 'sequence': '1690355191586', 'actionName': 'userOnline'}|
2023-07-26 15:06:31 [D] CLOUD None => False
2023-07-26 15:06:31 [D] Cloud connection retrying in 15 seconds
2023-07-26 15:06:34 [D] 10016bb404 <= Local0 | Can't get zeroconf info
2023-07-26 15:06:34 [D] 10016bb404 !! skip setup for encrypted device
2023-07-26 15:06:46 [E] Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 322, in connect|    raise Exception(resp)|Exception: {'error': 406, 'reason': 'Authentication Failed', 'apikey': '1ad9b710-c23d-44a6-8eb9-7803b327db1b', 'sequence': '1690355206805', 'actionName': 'userOnline'}|
2023-07-26 15:06:46 [D] CLOUD False => False
2023-07-26 15:06:46 [D] Cloud connection retrying in 60 seconds
2023-07-26 15:07:47 [E] Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 322, in connect|    raise Exception(resp)|Exception: {'error': 406, 'reason': 'Authentication Failed', 'apikey': '1ad9b710-c23d-44a6-8eb9-7803b327db1b', 'sequence': '1690355267241', 'actionName': 'userOnline'}|
2023-07-26 15:07:47 [D] CLOUD False => False
2023-07-26 15:07:47 [D] Cloud connection retrying in 300 seconds

**Comment by laverdone** [comment]
same error here

**Comment by smarthomefamilyverrips** [comment]
> You have to reconfigure the addon using only your email, leave the password blank, it has worked for me.

@jordisco I did the same and it removed the request for reconfigure, but if I check my system information my devices are not available through cloud... are they available  you?

**Comment by jordisco** [comment]
> > You have to reconfigure the addon using only your email, leave the password blank, it has worked for me.
> 
> @jordisco I did the same and it removed the request for reconfigure, but if I check my system information my devices are not available through cloud... are they available you?

I can indeed control them with the eWeLink app without any problems and from Home Assistant, do you have your devices configured for "LAN control"?

**Comment by smarthomefamilyverrips** [comment]
> > > You have to reconfigure the addon using only your email, leave the password blank, it has worked for me.
> > 
> > 
> > @jordisco I did the same and it removed the request for reconfigure, but if I check my system information my devices are not available through cloud... are they available you?
> 
> I can indeed control them with the eWeLink app without any problems and from Home Assistant, do you have your devices configured for "LAN control"?

@jordisco I can control them through my ewelink app, also the devices are available in HA through local control, only they are not available if you configure the integration to use cloud instead of auto or lan.... also if you check system information in HA it shows 0/10 cloud devices are online

**Comment by fbarahonad** [comment]
> > You have to reconfigure the addon using only your email, leave the password blank, it has worked for me.
> 
> @jordisco I did the same and it removed the request for reconfigure, but if I check my system information my devices are not available through cloud... are they available you?

I followed the same steps and get the same: no error but SonOff still not working on HA (but working on eWeLink app)

**Comment by laverdone** [comment]
work for me

**Comment by smarthomefamilyverrips** [comment]
> 

@laverdone are your devices also available when you configure cloud instead of auto or local.... and do your devices show up as online cloud devices in system information?

**Comment by jordisco** [comment]
I have it in auto mode and not in cloud, this option is fine for me.

**Comment by liamlain** [comment]
i set in auto mode,but stil the same.
in eWelink app are fine ,can control the device.

**Comment by smarthomefamilyverrips** [comment]
> I have it in auto mode and not in cloud, this option is fine for me.

@jordisco I also have it in auto and I can control my devices the thing is only that my devices can not be reached by cloud anymore and not show as online cloud device in HA system information... so actually this not solves the problem it just solves the part of the error not showing up but it not connect to the cloud to check your devices falling back to your last known list stored in config/.storage and neither you have cloud control..... MEANING IF YOU ADD A NEW DEVICE TO YOUR EWELINK APP IT WILL NOT BE ADDED TO THE INTEGRATION

**Comment by basirmuhamedkulov** [comment]
> 

same behavior

**Comment by yousaf465** [comment]
energy data is also gathered from cloud I think .which is not available with LAN control.

**Comment by eriklysoe** [comment]
Same error here

**Comment by smarthomefamilyverrips** [comment]
This shows now in my system information

Version | 3.5.1 (122751c)
Cloud devices online | 0 / 10
Local devices online | 10 / 10

**Comment by Bastiencc** [comment]
same error here

**Comment by Bastiencc** [comment]
> Did the line changing edit (line 107 and 157) in the /custom_components/sonoff/core/ewelink/cloud.py restarted HA and all good now
> 
> https://github.com/AlexxIT/SonoffLAN/issues/887

**Comment by eriklysoe** [comment]
This worked :-)

Changing the /config/custom_components/sonoff/core/ewelink/cloud.py in line 158 from

async def login(self, username: str, password: str, app=0) -> bool:

to

async def login(self, username: str, password: str, app=1) -> bool:

https://github.com/AlexxIT/SonoffLAN/issues/887#issuecomment-1175897133

**Comment by smarthomefamilyverrips** [comment]
@eriklysoe and @Bastiencc can you confirm that your devices also show online within your system information under the Sonoff section at "cloud devices online"

**Comment by eriklysoe** [comment]
> @eriklysoe and @Bastiencc can you confirm that your devices also show online within your system information under the Sonoff section at "cloud devices online"

Yes, devices are again online in ha.

Only need to change line 108

**Comment by smarthomefamilyverrips** [comment]
> > Did the line changing edit (line 107 and 157) in the /custom_components/sonoff/core/ewelink/cloud.py restarted HA and all good now
> > #887

This also worked for me! 

@jordisco and anyone else letting the password field blank (DIY), doing so only removes the error but not let you connect to cloud to get device updates, if you use the above quoted solution ONLY THEN all works like it did before again.... you can change the lines and re-authentificate the integration (just add integration again using same login credentials as you original used)

**Comment by dpgh947** [comment]
I'm having this problem. I have tried the edit fix, and I have tried reconfiguring without password. Both methods allow the integration to start, and both give me control of a couple of basic R2 switches, but I also have a 4-way relay, and trying both methods, that device is found, but there are no working entities, the previous switches for the 4 relays are now unavailable.

**Comment by marioedani** [comment]
+1

**Comment by smarthomefamilyverrips** [comment]
> I'm having this problem. I have tried the edit fix, and I have tried reconfiguring without password. Both methods allow the integration to start, and both give me control of a couple of basic R2 switches, but I also have a 4-way relay, and trying both methods, that device is found, but there are no working entities, the previous switches for the 4 relays are now unavailable.

yes I actually find out that at me also not all devices bacame available again :( ..... so seems both "fixes" only partly fix this issue

**Comment by dpgh947** [comment]
> > I'm having this problem. I have tried the edit fix, and I have tried reconfiguring without password. Both methods allow the integration to start, and both give me control of a couple of basic R2 switches, but I also have a 4-way relay, and trying both methods, that device is found, but there are no working entities, the previous switches for the 4 relays are now unavailable.
> 
> yes I actually find out that at me also not all devices bacame available again :( ..... so seems both "fixes" only partly fix this issue

in debug log I get
```
2 devices loaded from Cache
```
for the 2 switches that work, and
```
!! skip setup for encrypted device
```
for the 4-way that does not work.

**Comment by fbarahonad** [comment]
> 

It works! (I'm using a simple R2). Thank you!.

**Comment by AlexxIT** [comment]
#1201

**Comment by ChapayTv** [comment]
> This also worked for me! Only at me the changes had to be done in line 108 and line 157.

Can you please tell me how can I log in again with a password without deleting the integration?

**Comment by eriklysoe** [comment]
> > This also worked for me! Only at me the changes had to be done in line 108 and line 157.
> 
> Can you please tell me how can I log in again with a password without deleting the integration?

Just delete and add again

**Comment by ChapayTv** [comment]
> delete and add again

And the name of the objects and the use of these objects in automations do not follow?

**Comment by smytangel** [comment]
same error here

**Comment by smarthomefamilyverrips** [comment]
> > This also worked for me! Only at me the changes had to be done in line 108 and line 157.
> 
> Can you please tell me how can I log in again with a password without deleting the integration?

@ChapayTv just add the integration again from within UI without deleting the old integration

**Comment by msavazzi** [comment]
I used the workaround and removed the second API key. It worked but I have only original Sonoff devices

**Comment by smarthomefamilyverrips** [comment]
@msavazzi just update to latest version, it has the fix for this issue.

**Comment by msavazzi** [comment]
@smarthomefamilyverrips thank you!
