### ISSUE TITLE
I started getting an error: appid is unauthorized! 

### ISSUE THREAD

**Issue by msavazzi** [AlexxIT/SonoffLAN#1206]
2023-07-28 18:55:55.090 WARNING (MainThread) [custom_components.sonoff] Can't login with mode: auto
Traceback (most recent call last):
  File "/config/custom_components/sonoff/__init__.py", line 206, in async_setup_entry
    await registry.cloud.login(username, password)
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 150, in login
    raise AuthError(resp["msg"])
custom_components.sonoff.core.ewelink.cloud.AuthError: appid is unauthorized! KOBxGJna5qkk3JLXw3LHLX3wSNiPjAVi
2023-07-28 18:55:55.092 WARNING (MainThread) [homeassistant.config_entries] Config entry 'xxx' for sonoff integration could not authenticate: appid is unauthorized! KOBxGJna5qkk3JLXw3LHLX3wSNiPjAVi

Can you help me?

**Comment by kennethpangky** [comment]
Yup, getting it after a reboot of HA. Control of devices still seems to work.

**Comment by AlexxIT** [comment]
#1201
