### ISSUE TITLE
FamilyList

### ISSUE THREAD

**Issue by WernerFettke** [AlexxIT/SonoffLAN#1207]
Hi, I hope someone is able to assit, I had an issue with the unauthorised API Key, which I resolved by downloading the lastest version of https://github.com/AlexxIT/SonoffLAN/releases, how ever I now I started receiving the following:

[2023-07-29 12:11:58,744][ INFO](Main.MQTT           ) subscribing to: /ewelink_command/#
[2023-07-29 12:12:03,196][ERROR](Main.EwelinkClient  ) 'familyList'
Traceback (most recent call last):
  File "/home/pi/eWeLink-mqtt/ewelink.py", line 298, in start_connection
    homes = await self.get_homes()
  File "/home/pi/eWeLink-mqtt/custom_components/sonoff/core/ewelink/cloud.py", line 179, in get_homes
    return {i["id"]: i["name"] for i in resp["data"]["familyList"]}
KeyError: 'familyList'

I have tried a fresh install, as well as updating my current version, but the same error.

Any assitance would really be appreciated.

Regards

Werner

**Comment by joseap** [comment]
Same issue here.

Regards

**Comment by joseap** [comment]
Solved aftrer updating sonoff on hacs

**Comment by WernerFettke** [comment]
Awesome ! HACS ? Could you point meinthe right direction ?

**Comment by joseap** [comment]
Well, the sonoff lan integration is on Hacs tab. Yesterday I had a new update on Sonoff. The update mention that the key is changed.

 

De: Werner Fettke ***@***.***> 
Enviado el: domingo, 30 de julio de 2023 9:50
Para: AlexxIT/SonoffLAN ***@***.***>
CC: joseap ***@***.***>; Comment ***@***.***>
Asunto: Re: [AlexxIT/SonoffLAN] FamilyList (Issue #1207)

 

Awesome ! HACS ? Could you point meinthe right direction ?

**Comment by gugaspinto** [comment]
I updated to v352 with hacs... I still have issues with 4 channel relay 3th party brand. Something I need to do? Any one have the same issue? Thanks.

**Comment by WernerFettke** [comment]
I updated my HACS also to 352, but still the same issue, I have a feeling your setup might be different to mine.......been looking at the code in cloud.py as well as what it is supposed to be returning.... eWelink's documentation says:

API End Point - GET@/v2/family 
Name = Get home and room List
Description - There is at least 1 family under the user account

I have gone through my room set up on the app, added and removed rooms, adding and removing under 'manage homes', but it does not make a difference.

I don't understand what the description means (There is at least 1 family under the user account) ?

I'm assuming I have not set something up correctly under my app / ewelink account, hence the error..... i.e. There is no familyList set up......

Something else I noticed, after upgrading HACS, I was receiving a COLOR_MODE_ONOFF Error, I added it to light.py in the HomeAssistance/ light.py file, as COLOR_MODE_ONOFF = None (Which then resolved the error), after this change I started receiving the familyList error.

Any assistance would be appreciated here.

Many thanks !

**Comment by AlexxIT** [comment]
Show device diagnostics

**Comment by borazslo** [comment]
I added a line afte L178 to eWeLink-mqtt/custom_components/sonoff/core/ewelink/cloud.py :    
```
        print(resp)
```
The result was as follows:
```
{'error': 407, 'msg': 'the path of request is not allowed with appid:4s1FXKC9FaGfoqXhmXSJneb3qcm1gOak', 'data': {}}
```
So I added a `#` sign to the beginning of the L41 so as to use an other appId.

And now it works. :D

**Comment by WernerFettke** [comment]
Borazslo, You are a rock star !!! All working again here as well ! Thank you !
