### ISSUE TITLE
Hass 2024.1 error: _attr_device_class

### ISSUE THREAD

**Issue by scooper1** [AlexxIT/SonoffLAN#1277]
after updating to 2024.1 beta, I am getting the following errors 

```
2023-12-28 02:49:59.969 WARNING (MainThread) [custom_components.sonoff.core.ewelink] 1001875bc0 !! can't setup device
Traceback (most recent call last):
File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 57, in setup_devices
entities += [cls(self, device) for cls in get_spec(device)]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 57, in <listcomp>
entities += [cls(self, device) for cls in get_spec(device)]
^^^^^^^^^^^^^^^^^
File "/config/custom_components/sonoff/sensor.py", line 83, in __init__
self._attr_device_class = DEVICE_CLASSES.get(default_class)
^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by scooper1** [comment]
this problem only happens on the powr320d
this device shows up ok in Ewelink app

but does not show in LAN or Internet mode

**Comment by wvdb0** [comment]
Same problem. The device is no longer detected since a couple of days

**Comment by taljaardwp** [comment]
Same issue after updating to version 2024.1.0 

2024-01-04 13:02:52.443 WARNING (MainThread) [custom_components.sonoff.core.ewelink] 10017fbc03 !! can't setup device
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 57, in setup_devices
    entities += [cls(self, device) for cls in get_spec(device)]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 57, in <listcomp>
    entities += [cls(self, device) for cls in get_spec(device)]
                 ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sonoff/sensor.py", line 83, in __init__
    self._attr_device_class = DEVICE_CLASSES.get(default_class)
    ^^^^^^^^^^^^^^^^^^^^^^^

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.5.4
