### ISSUE TITLE
After 2024.1 Sonoff S31 WiFi Smart plug, Historical Consumption not reporting 

### ISSUE THREAD

**Issue by kwkid** [AlexxIT/SonoffLAN#1294]
After installing 2024.1, my Sonoff S31 smart plugs are not reporting historical consumption information. The current energy/pow/consumption seems to be working fine, it's the historical stuff that's not reporting. The eWeLink app is fine, it's an issue with the addon / Home Assistant. Reverting back to 2023.12.4 resolves the issue. 

To enable the historical data, the following lines need to be added to configuration.yaml.

sonoff:
  devices:
    1001xxxxxx: 
      reporting:
        energy: [600, 30] # update interval (seconds), history size (days)

Once added, the historical data values are added as an attribute ("history") under sensor.sonoff_1001xxxxxx_energy

Logs:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 247, in add_to_platform_start
    if self.unique_id is None or self.device_class is None:
                                 ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/backports/functools.py", line 70, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 328, in device_class
    if hasattr(self, "_attr_device_class"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 338, in _getter
    return getattr(o, private_attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 338, in _getter
    return getattr(o, private_attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 338, in _getter
    return getattr(o, private_attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 981 more times]
RecursionError: maximum recursion depth exceeded

**Comment by kwkid** [comment]
btw...I tried the fix [#1288](https://github.com/AlexxIT/SonoffLAN/issues/1288) both after the install of 2024.1 as well as rolling back to 2023.12.4, applying the fix and then upgrading. In both instances the historical attribute was not available under sensor.sonoff_1001xxxxxx_energy

**Comment by lordwizzard** [comment]
That is what I wrote up also. Anything energy related is not reporting

**Comment by kwkid** [comment]
Closed following [#1288](https://github.com/AlexxIT/SonoffLAN/issues/1288)

**Comment by AlexxIT** [comment]
#1285
