### ISSUE TITLE
Fix T5 actions error in some cases

### ISSUE THREAD

**Issue by haade-administrator** [AlexxIT/SonoffLAN#1328]
Hello i have tested Sonoff TX-Ultimate T5-C2-86 in local mode, 
all functions works but not actions slide_1 and slide_2
is it possible to improve this function to support ?

**Mode Auto:** All works with modif lights.py with issue [1247](https://github.com/AlexxIT/SonoffLAN/issues/1247)
**Mode Cloud:** All works with modif lights.py with issue [1247](https://github.com/AlexxIT/SonoffLAN/issues/1247)
**Mode LAN(local):** all functions works but not actions slide_1 and slide_2

**Error:**
```
2024-01-21 11:39:54.351 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sensor.py", line 349, in clear_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    if customize := hass.data.get(DATA_CUSTOMIZE):
                    ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
2024-01-21 11:41:14.517 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 715, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 675, in _send_frame
    self._write(header + mask + message)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 702, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2024-01-21 11:48:12.064 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sensor.py", line 349, in clear_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    if customize := hass.data.get(DATA_CUSTOMIZE):
                    ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
2024-01-21 11:48:12.168 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sensor.py", line 349, in clear_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    if customize := hass.data.get(DATA_CUSTOMIZE):
                    ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
2024-01-21 11:48:12.236 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sensor.py", line 349, in clear_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    if customize := hass.data.get(DATA_CUSTOMIZE):
                    ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
2024-01-21 11:50:32.559 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sensor.py", line 349, in clear_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    if customize := hass.data.get(DATA_CUSTOMIZE):
                    ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
2024-01-21 11:50:32.584 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sensor.py", line 349, in clear_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    if customize := hass.data.get(DATA_CUSTOMIZE):
                    ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
```
**Known issues:**

```
2024-01-21 11:50:31 [D] LOCAL mode start
2024-01-21 11:50:32 [D] 1001f10a72 <= Local3 | 192.168.1.174:8081 | {'percentageControl': 0, 'calibState': False, 'triggerType': 2, 'lightSwitch': 'off', 'fwVersion': '1.3.1', 'rssi': -47} | 95
2024-01-21 11:50:32 [D] 1001f10a72 <= Local3 | 192.168.1.174:8081 | {'percentageControl': 0, 'calibState': False, 'triggerType': 2, 'lightSwitch': 'off', 'fwVersion': '1.3.1', 'rssi': -47} | 95
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.6.0
