### ISSUE TITLE
HA 2024.1.5 upgrade, now the sonoff integration errors, cannot uninstall

### ISSUE THREAD

**Issue by johnynfulleffect** [AlexxIT/SonoffLAN#1335]
Had the latest version of the integration installed on 2023.11 Home Assistant and all working fine.  Upgraded to 2024.1.5 and now I see the integration has this error on restart of HA:

```
Logger: homeassistant.setup
Source: setup.py:251
First occurred: January 29, 2024 at 4:47:07 PM (1 occurrences)
Last logged: January 29, 2024 at 4:47:07 PM

Setup failed for custom integration 'sonoff': Unable to import component: Exception importing custom_components.sonoff
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/sonoff/__init__.py", line 28, in <module>
    from .core import devices as core_devices
  File "/config/custom_components/sonoff/core/devices.py", line 102, in <module>
    PULSEWIDTH = spec(XPulseWidth, param="pulseWidth", enabled=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sonoff/core/devices.py", line 88, in spec
    return type(cls.__name__, (cls,), {**cls.__dict__, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in __init__
    wrap_attr(cls, property_name)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in wrap_attr
    raise TypeError(f"Can't override {attr_name} in subclass")
TypeError: Can't override _attr_native_max_value in subclass

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 830, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.sonoff

```

I cannot even delete it to install it again.  When I try and add the integration again, i get his error right away:

`Config flow could not be loaded: {"message":"Invalid handler specified"}`

When i delete the integration, I restart HA, and this long error above still appears in the notifications.

**Comment by ph1nt** [comment]
Logger: homeassistant.loader
Source: loader.py:842
First occurred: 17:49:32 (1 occurrences)
Last logged: 17:49:32

Unexpected exception importing platform custom_components.sonoff.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/sonoff/__init__.py", line 28, in <module>
    from .core import devices as core_devices
  File "/config/custom_components/sonoff/core/devices.py", line 104, in <module>
    PULSEWIDTH = spec(XPulseWidth, param="pulseWidth", enabled=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sonoff/core/devices.py", line 90, in spec
    return type(cls.__name__, (cls,), {**cls.__dict__, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in __init__
    wrap_attr(cls, property_name)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in wrap_attr
    raise TypeError(f"Can't override {attr_name} in subclass")
TypeError: Can't override _attr_native_min_value in subclass

**Comment by johnynfulleffect** [comment]
I was able to resolve this by exec'ing into my docker container, deleting the dir under ~/config/custom_components/sonoff, then when I restarted HA, I was able to delete the integration.  Then I installed it fresh from HACS and I'm back up and running!
