### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by josephny** [AlexxIT/SonoffLAN#1338]
My sonoff integration has stopped working, for no reason that I can determine.

I have read the issues here, and the posts/threads elsewhere, I've made the async app=1 changes, tried both auto and cloud logins, but can't get it to work.

I can confirm that I can log into my account from the ewelink web site.

Running Proxmox with:
HAOS 11.5
Core 2024.1.6

Here is the debug:
```
2024-02-06 09:55:40 [D] SysInfo: {'installation_type': 'Home Assistant OS', 'version': '2024.1.6', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.11.6', 'docker': True, 'arch': 'x86_64', 'timezone': 'America/New_York', 'os_name': 'Linux', 'os_version': '6.1.74-haos', 'user': 'root', 'supervisor': '2024.01.1', 'host_os': 'Home Assistant OS 11.5', 'docker_version': '24.0.7', 'chassis': 'vm', 'sonoff_version': '3.5.4 (a4a8c5f)'}
2024-02-06 09:56:11 [W] Can't login with mode: auto|  File "/config/custom_components/sonoff/__init__.py", line 207, in async_setup_entry|    await registry.cloud.login(username, password)|TimeoutError|
```
And the Log:
```
Logger: custom_components.sonoff
Source: custom_components/sonoff/__init__.py:207
Integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](http://mtdale.dyndns.org:8123/api/sonoff/cf5eaee3-15df-4e98-90d3-d15b835de0fd))
First occurred: 9:56:11 AM (6 occurrences)
Last logged: 10:01:21 AM

Can't login with mode: auto
Traceback (most recent call last):
  File "/config/custom_components/sonoff/__init__.py", line 207, in async_setup_entry
    await registry.cloud.login(username, password)
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 145, in login
    r = await self.session.post(
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 504, in _request
    with timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
```

I am lost as to how to continue troubleshooting.

Any help would sure be appreciated.

**Comment by Mike-kk-de** [comment]
same for me after Update to HAOS 11.5

Error:
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 16:44:44 (1 occurrences)
Last logged: 16:44:44

Setup failed for custom integration 'sonoff': Unable to import component: Exception importing custom_components.sonoff
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/sonoff/__init__.py", line 28, in <module>
    from .core import devices as core_devices
  File "/config/custom_components/sonoff/core/devices.py", line 104, in <module>
    PULSEWIDTH = spec(XPulseWidth, param="pulseWidth", enabled=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sonoff/core/devices.py", line 90, in spec
    return type(cls.__name__, (cls,), {**cls.__dict__, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in __init__
    wrap_attr(cls, property_name)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in wrap_attr
    raise TypeError(f"Can't override {attr_name} in subclass")
TypeError: Can't override _attr_native_step in subclass

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 830, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.sonoff

**Comment by josephny** [comment]
It's quite frustrating.

I have come to depend on the Sonoff devices.

I have about 29 of these devices in places.

**Comment by mike-kk-dd** [comment]
i downgraded to last working Version.
You can do that in Terminal with:

ha core update --version 2023.12.3

sonoff is working again...

**Comment by josephny** [comment]
I followed your lead and am now on 2023.12.3, but still doesn't work.

I'm still using 11.5 -- could that be a problem?

**Comment by mike-kk-dd** [comment]
these are my Versions and it works:
Core 2023.12.3
Supervisor 2024.01.1
Operating System 11.5
Frontend  20231208.2

**Comment by josephny** [comment]
I reboot several times and now it is working.

Thank you again so much!

This was a good lesson about upgrading:  Proceed with Caution.

**Comment by AlexxIT** [comment]
@josephny yes. You have network problems. Not related to this integration.
But @mike-kk-dd has a real problem. That should be fixed. Better to create separate issue for it.

**Comment by asteinarson** [comment]
I got the error containing `XPulseWidth...` after upgrading to HomeAssistant 24.01 - and restarting with previous version of SonoffLAN (which was 3.5.2). 
By upgrading also SonoffLAN (to 3.5.4) and restarting HA - it went away. All Sonoff devices are visible and functional again.

**Comment by mike-kk-dd** [comment]
maybe a stupid question, but how can i simply update Sonoff to 3.5.4?

**Comment by asteinarson** [comment]
You have to download that version - as a Zip is easiest. Look for the
version tags - here on GitHub - and try to find the download.

Then, you have to go into the config director of your HA. Then various
extensions are located in subfolder ``custom_components``.

Shut down HA, ove old Sonoff module out of the way (best to move, not to
delete). Then expand the zip (or rather the right part of it) into this
folder.

Best if you get your head around each step - and just not follow blindly.

**Comment by AlexxIT** [comment]
Shut down is not necessary step.

**Comment by KevinFromUpThere** [comment]
Thanks @asteinarson that fixed me too!  Wife happy again that all my automated nonsense is working again.

**Comment by AlexxIT** [comment]
Close this because simple network issue. Not related to integration
