### ISSUE TITLE
Stopped working cloud connect error 

### ISSUE THREAD

**Issue by Mikuchck** [AlexxIT/SonoffLAN#135]
IT was working fine before upgrade to 0.110

The hass log says

```
2020-05-30 22:29:07 INFO (SyncWorker_5) [homeassistant.loader] Loaded notify from homeassistant.components.notify
2020-05-30 22:29:07 ERROR (MainThread) [custom_components.sonoff.sonoff_cloud] Login error: {'error': 401, 'msg': 'pwd err'}
2020-05-30 22:29:07 WARNING (MainThread) [custom_components.sonoff] Can't connect to eWeLink Cloud
2020-05-30 22:29:07 ERROR (MainThread) [homeassistant.setup] Error during setup of component sonoff
Traceback (most recent call last):
 File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in _async_setup_component
hass, processed_config
File "/config/custom_components/sonoff/__init__.py", line 218, in async_setup
for deviceid, device in registry.devices.items():
AttributeError: 'NoneType' object has no attribute 'items'
2020-05-30 22:29:07 INFO (MainThread) [homeassistant.components.sensor] Not adding entity HP DeskJet 2600 series Uptime because it's disabled
```

**Comment by AlexxIT** [comment]
Add setting `mode: local`. It will help.
You have the wrong ewelink password.
The new version connects to cloud by default.
Please read breaking changes 2.0:
https://github.com/AlexxIT/SonoffLAN
