### ISSUE TITLE
Unable to load device status after running for a period of time

### ISSUE THREAD

**Issue by ZBXallen** [AlexxIT/SonoffLAN#1381]
Unable to load device status after running for a period of time.

The physical device in sonoff is displayed as unavailable.
I tried restarting the network, deleting and adding a sonoff account, but it didn't work. The following is the error message re-added.

Only by restarting ha can it return to normal. 
Here I have checked `/config/.storge/sonoff` and `/config/custom_components/sonoff` and there is no change.
```
2024-04-12 09:58:50.172 WARNING (MainThread) [custom_components.sonoff] Can't load devices
Traceback (most recent call last):
  File "/config/custom_components/sonoff/__init__.py", line 243, in internal_normal_setup
    devices = await registry.cloud.get_devices(homes)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 220, in get_devices
    raise Exception(resp["msg"])
Exception: cannot found access token info
2024-04-12 09:58:50.635 ERROR (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud WS exception
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 352, in connect
    raise Exception(resp)
Exception: {'error': 406, 'reason': 'Authentication Failed', 'apikey': 'fc2a49e7-519f-41f3-b720-38074ebfecaa', 'sequence': '1712887130590', 'actionName': 'userOnline'}
2024-04-12 09:59:06.066 ERROR (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud WS exception
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 352, in connect
    raise Exception(resp)
Exception: {'error': 406, 'reason': 'Authentication Failed', 'apikey': 'fc2a49e7-519f-41f3-b720-38074ebfecaa', 'sequence': '1712887146023', 'actionName': 'userOnline'}
2024-04-12 10:00:06.516 ERROR (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud WS exception
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 352, in connect
    raise Exception(resp)
Exception: {'error': 406, 'reason': 'Authentication Failed', 'apikey': 'fc2a49e7-519f-41f3-b720-38074ebfecaa', 'sequence': '1712887206470', 'actionName': 'userOnline'}
```

**Comment by AlexxIT** [comment]
Authentication Failed can happened if you use same user/pass in another place
