### ISSUE TITLE
Not able to setup device in HA

### ISSUE THREAD

**Issue by yfyap69** [AlexxIT/SonoffLAN#1391]
Having problem to setup 2 devices in HA. Device was working fine befor update HA core from 2024.3 to 2024.4 and HA OS from 12.0 to 12.2. Sonff LAN version earlier was 3.6.0. Tried downgrade HA Core back to 2024.3 & HA OS 12.0 but does not work. Also tried upgrade Sonoff LAN to 3.7.2 also does not work. Devices are working fine in Ewelinks apps. See logs as per below:
```
Logger: custom_components.sonoff.core.ewelink
Source: custom_components/sonoff/core/ewelink/__init__.py:60
Integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: 10:58:21 (2 occurrences)
Last logged: 10:58:21

1001fe638c !! can't setup device
1001dfded1 !! can't setup device
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 60, in setup_devices
    entities += [cls(self, device) for cls in get_spec(device)]
                 ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sonoff/sensor.py", line 98, in __init__
    self.report_mint, self.report_maxt, self.report_delta = reporting
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by AlexxIT** [comment]
You have errors in this config
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#preventing-db-size-growth
