### ISSUE TITLE
WARNING in logs after update of HA to 2024.6.4

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [AlexxIT/SonoffLAN#1438]
After I did do a update to HA 2024.6.4 I get the following warning in my logs

Logger: homeassistant.util.loop
Source: util/loop.py:84
First occurred: 15:25:53 (23 occurrences)
Last logged: 15:25:53

Detected blocking call to open inside the event loop by custom integration 'sonoff' at custom_components/sonoff/core/xutils.py, line 20: with open(path, "rb") as f: (offender: /config/custom_components/sonoff/core/xutils.py, line 20: with open(path, "rb") as f:), please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 89, in get_integration_info data = await registration.info_callback(hass) File "/config/custom_components/sonoff/system_health.py", line 45, in system_health_info "version": f"{integration.version} ({xutils.source_hash()})", File "/config/custom_components/sonoff/core/xutils.py", line 20, in source_hash with open(path, "rb") as f:

**Comment by smarthomefamilyverrips** [comment]
duplicate of #1426
