### ISSUE TITLE
Wait response key error

### ISSUE THREAD

**Issue by niraviry** [AlexxIT/SonoffLAN#151]
I am aware to the fact that the original POW is not in the list but it works with errors from time to time. I use version 0.110.4.
I have moved to this integration due to the but in the other implementation which causes the frontend to stop responding. Now it is OK except for this issue.
What I get is as follows:

```
Logger: homeassistant.helpers.entity
Source: custom_components/sonoff/sonoff_cloud.py:51
First occurred: 3 ביוני 2020, 21:01:36 (381 occurrences)
Last logged: 21:46:55

Update for switch.sonoff_10006d13b3 fails
Update for switch.sonoff_100023fe07 fails
Update for switch.sonoff_100023c302 fails
Update for switch.sonoff_100023fd48 fails
Update for switch.sonoff_100023f9b4 fails
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 48, in _wait_response
    await asyncio.wait_for(self._waiters[sequence], timeout)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/sonoff/switch.py", line 107, in async_update
    await self.registry.send(self.deviceid, params)
  File "/config/custom_components/sonoff/sonoff_main.py", line 174, in send
    state['cloud'] = await self.cloud.send(deviceid, params, seq)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 298, in send
    return await self._wait_response(sequence)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 51, in _wait_response
    self._waiters.pop(sequence)
KeyError: '1591207291033'
```

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.1.3
