### ISSUE TITLE
All broken ?

### ISSUE THREAD

**Issue by thomasvanhorde** [AlexxIT/SonoffLAN#1549]
Hi,

All is broken in HA ?

2024-12-19 17:01:03.945 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.cloud] CLOUD change state old=True, new=None
2024-12-19 17:01:04.186 DEBUG (MainThread) [custom_components.sonoff] 27 devices loaded from Cloud
2024-12-19 17:01:04.222 DEBUG (MainThread) [custom_components.sonoff] AUTO mode start
2024-12-19 17:01:04.554 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.cloud] CLOUD change state old=None, new=True

0 entities in HA.

Thanks

**Comment by Maocx** [comment]
Was broken yesterday for me as well. I just reloaded the plugin and my switches came back online.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#issues

**Comment by schaefsteven** [comment]
May or may not be the same issue, but it stopped working for me too. I only have one device. It worked fine for about a month, and then went unavailable. It's still online and works through the ewelink app, but not Home Assistant. 

I deleted the integration and re-added it, and this time it didn't pull in any devices. 

Debug info: 

Check the number of online devices on the System Health page:
```
Sonoff
Version | 3.8.1 (ffa7e22)
Cloud devices online | 0 / 0
Local devices online | 0 / 0
```

Check warning and errors on the Logs page:
These are from before I re-installed: 
```
This error originated from a custom integration.

Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/core/ewelink/cloud.py:580
integration: Sonoff (documentation, issues)
First occurred: January 16, 2025 at 1:37:11 AM (149 occurrences)
Last logged: 10:29:45 AM

You logged in from another place, read more https://github.com/AlexxIT/SonoffLAN#configuration
```
```
This error originated from a custom integration.

Logger: custom_components.sonoff
Source: custom_components/sonoff/__init__.py:216
integration: Sonoff (documentation, issues)
First occurred: January 16, 2025 at 7:38:38 PM (4 occurrences)
Last logged: 10:25:57 AM

Can't load devices
Traceback (most recent call last):
  File "/config/custom_components/sonoff/__init__.py", line 216, in async_setup_entry
    devices = await registry.cloud.get_devices(homes)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 436, in get_devices
    raise Exception(resp["msg"])
Exception: access token expired
```

**That access token expired looks like a problem to me?**

Check debug logs on the Debug page:
```
2025-01-21 09:36:53.525 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.cloud] CLOUD change state old=True, new=None
2025-01-21 09:36:53.605 DEBUG (MainThread) [custom_components.sonoff] 1 devices loaded from Cloud
2025-01-21 09:36:53.607 DEBUG (MainThread) [custom_components.sonoff] AUTO mode start
2025-01-21 09:36:54.299 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.cloud] CLOUD change state old=None, new=True

```

Share integration diagnostics (supported from Hass v2022.2):
Not working on my HA install for some reason, can't download it, getting a 401.

**Comment by schaefsteven** [comment]
I updated Home Assistant to version 2025.1.3 and it started working again. Any other users having issues, I recommend updating if you can.
