### ISSUE TITLE
TypeError: the JSON object must be str, bytes or bytearray, not ServerTimeoutError

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/SonoffLAN#1550]
This error originated from a custom integration.
```
Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/core/ewelink/cloud.py:543
integration: Sonoff (documentation, issues)
First occurred: 14:53:50 (1 occurrences)
Last logged: 14:53:50

Cloud processing error
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 543, in run_forever
    resp = json.loads(msg.data)
  File "/usr/local/lib/python3.13/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
                    f'not {s.__class__.__name__}')
TypeError: the JSON object must be str, bytes or bytearray, not ServerTimeoutError
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.8.2
