### ISSUE TITLE
Log Errors: Sonoff LAN 2.1.4 running in Home Assistant 0.111.0

### ISSUE THREAD

**Issue by RodneyCapron** [AlexxIT/SonoffLAN#162]
Hello @AlexxIT ,

I am using Sonoff LAN version 2.1.4 (local only mode) running in Home Assistant 0.111.0 and have noticed the following errors in my log.

```
2020-06-11 13:53:06 WARNING (MainThread) [homeassistant.setup] Setup of sonoff is taking over 10 seconds.

2020-06-11 14:40:29 ERROR (MainThread) [custom_components.sonoff.sonoff_local] 1000aa8f2a => Local4 | {'cmd': 'info'}
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_local.py", line 268, in send
    json=payload, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None

2020-06-11 15:27:26 WARNING (MainThread) [custom_components.sonoff.sonoff_local] 1000aa8f2a => Local4 | {'cmd': 'info'} !! Cannot connect to host 10.10.100.208:8081 ssl:None [Connect call failed ('10.10.100.208', 8081)]
```
Everything appears to be working correctly but I wanted to mention it in case there is a fix that needs to be made to the component.

Thank you very much for all your work on this!! I am currently using it for 4 Sonoff S55 Switches in my Garden for various things and it works great. :)

Best regards,
Rodney

**Comment by AlexxIT** [comment]
I hope fixed in https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.1.5

**Comment by RodneyCapron** [comment]
Thank you, Alexx! :)
