### ISSUE TITLE
Stopped working after update

### ISSUE THREAD

**Issue by leonardodvr** [AlexxIT/SonoffLAN#165]
Hello Alexx. I updated to home assistant 0.111.4 and sonoff stopped working. I also replaced my router so I'm not sure if this is caused by the IP's changing. I already restarted the router and home assistant with no success. I'm getting: The following integrations and platforms could not be set up: sonoff

I also removed the sonoff file from the config folder thinking that maybe they needed to refresh. I reinstalled the sonoff integration in HACS. No success. 

I'll appreciate any help. 

Leo

**Comment by leonardodvr** [comment]
This is the log for the error: 
Log Details (ERROR)
Logger: homeassistant.setup
Source: custom_components/sonoff/sonoff_cloud.py:250
First occurred: 9:18:34 AM (1 occurrences)
Last logged: 9:18:34 AM

Error during setup of component sonoff
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 190, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/sonoff/__init__.py", line 90, in async_setup
    config[CONF_PASSWORD]):
  File "/config/custom_components/sonoff/sonoff_main.py", line 122, in cloud_login
    return await self.cloud.login(username, password)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 250, in login
    self._apikey = resp['user']['apikey']
KeyError: 'user'

**Comment by leonardodvr** [comment]
Damn. As soon as I added the log error I noticed my problem. Sorry. Closing.
