### ISSUE TITLE
new chinese ewelink support switch SA-025-3C (use CKW04 chip) not working well - delay and sometimes no response

### ISSUE THREAD

**Issue by stephenyhb** [AlexxIT/SonoffLAN#176]
```
2020-06-26 19:07:25 ERROR (MainThread) [custom_components.sonoff.sonoff_local] 1000d06c79 => Local4 | {'cmd': 'info'}
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_local.py", line 270, in send
    json=payload, headers=LOCAL_HEADERS, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None
2020-06-26 19:07:26 DEBUG (MainThread) [custom_components.sonoff.sonoff_cloud] 1000d06c79 <= Cloud3 | {'action': 'sysmsg', 'deviceid': '1000d06c79', 'apikey': '208fb0f1-8d48-416e-ae4a-cdda91ae0cc0', 'ts': 0, 'params': {'online': True}}
2020-06-26 19:07:26 DEBUG (MainThread) [custom_components.sonoff.sonoff_cloud] 1000d06c79 <= Cloud3 | {'action': 'update', 'deviceid': '1000d06c79', 'apikey': 'bea17a3c-44a1-432d-adfb-abc50afd31d8', 'userAgent': 'device', 'd_seq': 62410, 'ts': 0, 'params': {'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'on', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'lock': 0, 'sledOnline': 'on', 'staMac': '44:5D:5E:40:41:D2', 'rssi': -46}, 'from': 'device'}
2020-06-26 19:07:30 DEBUG (MainThread) [custom_components.sonoff.sonoff_local] 1000d06c79 => Local4 | Check offline with timeout 20s

**debug log**

2020-06-26 18:57:46  DEBUG    main          SysInfo: {'version': '0.111.4', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.7.7', 'docker': True, 'arch': 'x86_64', 'os_name': 'Linux', 'os_version': '5.6.0-0.bpo.2-amd64', 'supervisor': '227', 'host_os': 'Debian GNU/Linux 10 (buster)', 'chassis': 'desktop', 'docker_version': '19.03.12'}

2020-06-26 18:57:46  DEBUG    main          AUTO mode start

2020-06-26 18:57:49  DEBUG    sonoff_cloud  Redirect to region: cn

2020-06-26 18:57:52  DEBUG    sonoff_cloud  1 devices loaded from the Cloud Server

2020-06-26 18:57:52  DEBUG    main          1000d06c79 == Init   | {'uiid': 3, 'extra': {'manufacturer': 'coolkit', 'model': 'CKW04-3C', 'sw_version': 'CKA-D01-GL v3.3.2'}, 'params': {'bindInfos': {'miot': ['...'], 'gaction': ['...']}, 'version': 8, 'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'on', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'lock': 0, 'sledOnline': 'on', 'staMac': '...', 'rssi': -53, 'fwVersion': '3.3.2', 'partnerApikey': '...', 'selfApikey': '123', 'cloud': 'online'}}

2020-06-26 18:57:53  DEBUG    sonoff_local  1000d06c79 <= Local1 | {'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'on', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'sledOnline': 'on', 'staMac': '...', 'rssi': -50} | 32

2020-06-26 18:57:53  DEBUG    sonoff_cloud  Cloud init: {'error': 0, 'apikey': '...', 'config': {'hb': 1, 'hbInterval': 145}, 'sequence': '1593169073714'}

2020-06-26 18:58:24  DEBUG    sonoff_local  1000d06c79 => Local4 | {'switches': [{'outlet': 0, 'switch': 'off'}]} !! Timeout 1

2020-06-26 18:58:24  DEBUG    sonoff_cloud  1000d06c79 => Cloud4 | {'switches': [{'outlet': 0, 'switch': 'off'}]} | 1593169103550

2020-06-26 18:58:25  DEBUG    sonoff_local  1000d06c79 <= Local3 | {'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'on', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 
'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'sledOnline': 'on', 'staMac': '...', 'rssi': -52} | 33

2020-06-26 18:58:25  DEBUG    sonoff_cloud  1000d06c79 <= Cloud3 | {'error': 0, 'deviceid': '1000d06c79', 'apikey': '...', 'sequence': '1593169103550'}

2020-06-26 18:58:25  DEBUG    sonoff_cloud  1000d06c79 => Cloud5 | Force update sequence: 1593169105509

2020-06-26 18:58:25  DEBUG    sonoff_cloud  1000d06c79 <= Cloud3 | {'error': 0, 'deviceid': '1000d06c79', 'apikey': '...', 'sequence': '1593169105509', 'params': {'bindInfos': {'miot': ['...'], 'gaction': ['...']}, 'version': 8, 'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'on', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'lock': 0, 'sledOnline': 'on', 'staMac': '...', 'rssi': -53, 'fwVersion': '3.3.2', 'partnerApikey': '...', 'selfApikey': '123'}}

2020-06-26 18:58:25  DEBUG    sonoff_local  1000d06c79 => Local4 | {'switches': [{'outlet': 0, 'switch': 'on'}]} <= {'sequence': '1593169105769', 'seq': 34, 'error': 0}

2020-06-26 18:58:26  DEBUG    sonoff_cloud  1000d06c79 <= Cloud3 | {'action': 'update', 'deviceid': '1000d06c79', 'apikey': '...', 'userAgent': 'device', 'd_seq': 34, 'ts': 0, 'params': {'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'on', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'selfApikey': '123'}, 'from': 'device'}

2020-06-26 18:58:26  DEBUG    sonoff_local  1000d06c79 <= Local3 | {'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'on', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'sledOnline': 'on', 'staMac': '...', 'rssi': -52} | 34

2020-06-26 18:58:27  DEBUG    sonoff_local  1000d06c79 => Local4 | {'switches': [{'outlet': 1, 'switch': 'on'}]} <= {'sequence': '1593169107271', 'seq': 35, 'error': 0}

2020-06-26 18:58:27  DEBUG    sonoff_local  1000d06c79 <= Local3 | {'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'on', 'outlet': 1}, {'switch': 'on', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'sledOnline': 'on', 'staMac': '...', 'rssi': -51} | 35

2020-06-26 18:58:27  DEBUG    sonoff_cloud  1000d06c79 <= Cloud3 | {'action': 'update', 'deviceid': '1000d06c79', 'apikey': '...', 'userAgent': 'device', 'd_seq': 35, 'ts': 0, 'params': {'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'on', 'outlet': 1}, {'switch': 'on', 'outlet': 2}, {'switch': 'off', 
'outlet': 3}], 'selfApikey': '123'}, 'from': 'device'}

2020-06-26 18:58:31  DEBUG    sonoff_local  1000d06c79 => Local4 | {'switches': [{'outlet': 1, 'switch': 'off'}]} <= {'sequence': '1593169110985', 'seq': 36, 'error': 0}

2020-06-26 18:58:31  DEBUG    sonoff_local  1000d06c79 <= Local3 | {'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'on', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'sledOnline': 'on', 'staMac': '...', 'rssi': -48} | 36

2020-06-26 18:58:31  DEBUG    sonoff_cloud  1000d06c79 <= Cloud3 | {'action': 'update', 'deviceid': '1000d06c79', 'apikey': '...', 'userAgent': 'device', 'd_seq': 36, 'ts': 0, 'params': {'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'on', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'selfApikey': '123'}, 'from': 'device'}

2020-06-26 18:58:32  DEBUG    sonoff_local  1000d06c79 => Local4 | {'switches': [{'outlet': 2, 'switch': 'off'}]} <= {'sequence': '1593169112086', 'seq': 37, 'error': 0}

2020-06-26 18:58:32  DEBUG    sonoff_local  1000d06c79 <= Local3 | {'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'sledOnline': 'on', 'staMac': '...', 'rssi': -52} | 37

2020-06-26 18:58:33  DEBUG    sonoff_cloud  1000d06c79 <= Cloud3 | {'action': 'update', 'deviceid': '1000d06c79', 'apikey': '...', 'userAgent': 'device', 'd_seq': 37, 'ts': 0, 'params': {'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'selfApikey': '123'}, 'from': 'device'}

2020-06-26 18:58:34  DEBUG    sonoff_local  1000d06c79 => Local4 | {'switches': [{'outlet': 2, 'switch': 'on'}]} !! Timeout 1

2020-06-26 18:58:34  DEBUG    sonoff_cloud  1000d06c79 => Cloud4 | {'switches': [{'outlet': 2, 'switch': 'on'}]} | 1593169113367

2020-06-26 18:58:35  DEBUG    sonoff_local  1000d06c79 <= Local3 | {'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'on', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'sledOnline': 'on', 'staMac': '...', 'rssi': -52} | 38

2020-06-26 18:58:35  DEBUG    sonoff_cloud  1000d06c79 <= Cloud3 | {'error': 0, 'deviceid': '1000d06c79', 'apikey': '...', 'sequence': '1593169113367'}

2020-06-26 18:58:35  DEBUG    sonoff_cloud  1000d06c79 => Cloud5 | Force update sequence: 1593169115556

2020-06-26 18:58:35  DEBUG    sonoff_cloud  1000d06c79 <= Cloud3 | {'error': 0, 'deviceid': '1000d06c79', 'apikey': '...', 'sequence': '1593169115556', 'params': {'bindInfos': {'miot': ['...'], 'gaction': ['...']}, 'version': 8, 'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'on', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'lock': 0, 'sledOnline': 'on', 'staMac': '...', 'rssi': -53, 'fwVersion': '3.3.2', 'partnerApikey': '...', 'selfApikey': '123'}}
```

any suggestion or help ?

**Comment by AlexxIT** [comment]
I think your device has a poor wifi connection. Nothing unusual.

**Comment by stephenyhb** [comment]
Thanks for the reply.
But the switch is only 10 feet from the router.
rssi is -4x to -5x, is that not good enough ?



stephenyhb@outlook.com
 
From: Alex X
Date: 2020-06-27 16:58
To: AlexxIT/SonoffLAN
CC: stephenyhb; Author
Subject: Re: [AlexxIT/SonoffLAN] new chinese ewelink support switch SA-025-3C (use CKW04 chip) not working well - delay and sometimes no response (#176)
I think your device has a poor wifi connection. Nothing unusual.

**Comment by stephenyhb** [comment]
Can you teach me how to setup sonoff DW2-wi-fi in homeassistant ?  Many thanks.



stephenyhb@outlook.com
 
From: Alex X
Date: 2020-06-27 16:58
To: AlexxIT/SonoffLAN
CC: stephenyhb; Author
Subject: Re: [AlexxIT/SonoffLAN] new chinese ewelink support switch SA-025-3C (use CKW04 chip) not working well - delay and sometimes no response (#176)
I think your device has a poor wifi connection. Nothing unusual.

**Comment by AlexxIT** [comment]
You may have a lot of wifi devices. The router can not stand.
You need only add DW2 in ewelink account.

**Comment by AlexxIT** [comment]
Reopen issue if problem still actual

**Comment by heheda2033** [comment]
Hello AlexxIT.

Thank you so much for making this project

My device is also SA-025-3C, and this problem also occurs. In the configuration file "mode: local", there is also a delay and sometimes no response. When using "ewelink APP", even if it is on a 4G network, the problem will not appear. The second delay or no response at all, and this problem will occur in the HASS switch.

I don’t know much about HASS. What information do I need to provide to help troubleshoot this problem?

**Comment by AlexxIT** [comment]
Why you using mode local?
