### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by max5962** [AlexxIT/SonoffLAN#218]
Hello.

I installed your plugin with have successfully.
Configured it in full auto (only login and password) and nothing appears :

- no sonoff.json
- no cloud connection (ngrep show nothing)

```
2020-08-17 23:17:25 DEBUG (MainThread) [homeassistant.setup] Dependency sonoff will wait for ['zeroconf']
2020-08-17 23:17:27 INFO (MainThread) [homeassistant.setup] Setting up sonoff
2020-08-17 23:17:27 DEBUG (MainThread) [custom_components.sonoff] AUTO mode start
2020-0
2020-08-17 23:17:27 DEBUG (Thread-7) [zeroconf] Sending (37 bytes #1) <DNSOutgoing:{multicast=True, flags=0, questions=[question[ptr,in,_ewelink._tcp.local.]], answers=[], authorities=[], additionals=[]}> as b'\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x08_ewelink\x04_tcp\x05local\x00\x00\x0c\x00\x01'...
2020-08-17 23:17:27 DEBUG (zeroconf-Engine-139677554195232) [zeroconf] Received from '127.0.0.1':5353 (socket 9): <DNSIncoming:{id=0, flags=0, n_q=1, n_ans=0, n_auth=0, n_add=0, questions=[question[ptr,in,_ewelink._tcp.local.]], answers=[]}> (37 bytes) as [b'\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x08_ewelink\x04_tcp\x05local\x00\x00\x0c\x00\x01']
202

```

It seems trying local mode (that will not work because I use hass in a container without net-network)

Any idea ?

Thnaks

**Comment by AlexxIT** [comment]
I don't know. It should show something about login and load devices list.

**Comment by homecb** [comment]
> Same issue here.

Update: 

Running HASS.IO on Virtualbox. 

Added `mode: cloud` to config and devices now showing in entity list. 

However,  SonoffLAN does not show in Configuration > Integrations.

**Comment by AlexxIT** [comment]
SonoffLAN don't support GUI config yet.

**Comment by homecb** [comment]
> SonoffLAN don't support GUI config yet. 

Thanks for the info. Not an issue for me, actually. 

And big thanks for your work.

**Comment by AlexxIT** [comment]
Is the problem still relevant?

**Comment by homecb** [comment]
No longer for me.

**Comment by AlexxIT** [comment]
@max5962 ?

**Comment by max5962** [comment]
Hello @AlexxIT ,
still not working for me but i'm still debugging my issue :)
I change my container network ( remove home assistant from a private network in order to understand mdns request )

**Comment by AlexxIT** [comment]
@max5962 in auto mode component should use cloud+local connection. Do you have indents in the config?

**Comment by balbulator** [comment]
AlexxIT, у меня схожая проблема. Я добавил новое физическое устройство, но добавить его в НА не могу, пробовал разные режимы, mode: cloud / local. Удалял файл .sonoff.json,  новый не появлялся, устройства стали недоступными. 
Поставил так:
`sonoff:
  username: anisimovss@gmail.com
  password: hpc51833`
Это тоже не помогло добавить новое устройство.
Есть идеи?

**Comment by AlexxIT** [comment]
@balbulator нужно смотреть логи. Файл должен появиться

**Comment by balbulator** [comment]
> @balbulator нужно смотреть логи. Файл должен появиться

Логи Home Assistant?
```
`2021-01-18 20:46:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-18 20:46:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-18 20:46:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for xiaomi_gateway3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-18 20:46:18 WARNING (MainThread) [homeassistant.components.http] The 'base_url' option is deprecated, please remove it from your configuration
2021-01-18 20:46:21 WARNING (MainThread) [homeassistant.components.lovelace] Resources need to be specified in your configuration.yaml. Please see the docs
2021-01-18 20:46:26 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:26 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:26 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:26 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:26 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:26 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:27 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:27 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:27 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:27 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:27 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:27 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:27 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:27 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:27 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:27 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:27 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:27 ERROR (MainThread) [homeassistant.components.switch] The tuya platform for the switch integration does not support platform setup. Please remove it from your config.
2021-01-18 20:46:27 ERROR (MainThread) [homeassistant.components.switch] The tuya platform for the switch integration does not support platform setup. Please remove it from your config.
2021-01-18 20:46:27 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for rpi_power which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-18 20:46:29 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for rhvoice which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-18 20:46:29 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:30 WARNING (MainThread) [homeassistant.components.uptime.sensor] The 'unit_of_measurement' option is deprecated, please remove it from your configuration
2021-01-18 20:46:30 WARNING (MainThread) [homeassistant.components.template.sensor] The 'entity_id' option is deprecated, please remove it from your configuration
2021-01-18 20:46:30 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for x720 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-18 20:46:31 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2021-01-18 20:46:31 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 5 seconds
2021-01-18 20:46:33 WARNING (MainThread) [homeassistant.components.broadlink.remote] The remote platform is deprecated, please remove it from your configuration
2021-01-18 20:46:33 WARNING (MainThread) [homeassistant.components.broadlink.remote] The remote platform is deprecated, please remove it from your configuration
2021-01-18 20:46:33 WARNING (MainThread) [homeassistant.setup] Setup of hacs is taking over 10 seconds.
2021-01-18 20:46:38 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform xiaomi_miio is taking over 10 seconds.
2021-01-18 20:46:38 WARNING (MainThread) [homeassistant.components.vacuum] Setup of vacuum platform xiaomi_miio is taking over 10 seconds.
2021-01-18 20:46:40 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 10 seconds
2021-01-18 20:46:40 WARNING (MainThread) [homeassistant.components.upnp] Wanted UPnP/IGD device with UDN/ST "uuid:167f3dc0-1dd2-11b2-ada8-c0a0bb8c4a93"/"urn:schemas-upnp-org:device:InternetGatewayDevice:1" not found, aborting
2021-01-18 20:46:40 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 5 seconds
2021-01-18 20:46:40 WARNING (MainThread) [homeassistant.components.upnp] Wanted UPnP/IGD device with UDN/ST "uuid:3F815285-AB5A-88E0-AA44-1CBDB9A81D68"/"urn:schemas-upnp-org:device:InternetGatewayDevice:1" not found, aborting
2021-01-18 20:46:40 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 5 seconds
2021-01-18 20:46:41 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Huawei Home Gateway for upnp
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/upnp/__init__.py", line 116, in async_setup_entry
device = await async_discover_and_construct(hass, udn, st)
File "/usr/src/homeassistant/homeassistant/components/upnp/__init__.py", line 81, in async_discover_and_construct
return await Device.async_create_device(hass, location)
File "/usr/src/homeassistant/homeassistant/components/upnp/device.py", line 74, in async_create_device
upnp_device = await factory.async_create_device(ssdp_location)
File "/usr/local/lib/python3.8/site-packages/async_upnp_client/client_factory.py", line 52, in async_create_device
root = await self._async_get_url_xml(description_url)
File "/usr/local/lib/python3.8/site-packages/async_upnp_client/client_factory.py", line 290, in _async_get_url_xml
await self.requester.async_http_request('GET', url)
File "/usr/local/lib/python3.8/site-packages/async_upnp_client/client.py", line 66, in async_http_request
await self.async_do_http_request(method,
File "/usr/local/lib/python3.8/site-packages/async_upnp_client/aiohttp.py", line 103, in async_do_http_request
async with self._session.request(method, url, headers=headers, data=body) as response:
File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
self._resp = await self._coro
File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
await resp.start(conn)
File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
message, payload = await self._protocol.read() # type: ignore
File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 604, in read
await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
2021-01-18 20:46:41 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ (as_timestamp(states.sensor.snapshot_backup.attributes["last_snapshot"])) | timestamp_custom("%d.%m.%Y %H:%M") }}")
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 353, in async_render
render_result = compiled.render(kwargs)
File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
reraise(*rewrite_traceback_stack(source=source))
File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
raise value.with_traceback(tb)
File "<template>", line 1, in top-level template code
File "/usr/local/lib/python3.8/site-packages/jinja2/sandbox.py", line 384, in getitem
return obj[argument]
jinja2.exceptions.UndefinedError: 'None' has no attribute 'attributes'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 462, in async_render_to_info
render_info._result = self.async_render(variables, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 355, in async_render
raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'attributes'
2021-01-18 20:46:41 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template("{{ (as_timestamp(states.sensor.snapshot_backup.attributes["last_snapshot"])) | timestamp_custom("%d.%m.%Y %H:%M") }}")' for attribute '_state' in entity 'sensor.last_google_backup_train'
2021-01-18 20:46:41 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ states.sensor.snapshot_backup.attributes["snapshots_in_google_drive"] }}")
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 353, in async_render
render_result = compiled.render(kwargs)
File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
reraise(*rewrite_traceback_stack(source=source))
File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
raise value.with_traceback(tb)
File "<template>", line 1, in top-level template code
File "/usr/local/lib/python3.8/site-packages/jinja2/sandbox.py", line 384, in getitem
return obj[argument]
jinja2.exceptions.UndefinedError: 'None' has no attribute 'attributes'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 462, in async_render_to_info
render_info._result = self.async_render(variables, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 355, in async_render
raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'attributes'
2021-01-18 20:46:41 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template("{{ states.sensor.snapshot_backup.attributes["snapshots_in_google_drive"] }}")' for attribute '_state' in entity 'sensor.snapshots_in_google_drive_train'
2021-01-18 20:46:41 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ states.sensor.snapshot_backup.attributes["snapshots_in_hassio"] }}")
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 353, in async_render
render_result = compiled.render(kwargs)
File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
reraise(*rewrite_traceback_stack(source=source))
File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
raise value.with_traceback(tb)
File "<template>", line 1, in top-level template code
File "/usr/local/lib/python3.8/site-packages/jinja2/sandbox.py", line 384, in getitem
return obj[argument]
jinja2.exceptions.UndefinedError: 'None' has no attribute 'attributes'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 462, in async_render_to_info
render_info._result = self.async_render(variables, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 355, in async_render
raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'attributes'
2021-01-18 20:46:41 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template("{{ states.sensor.snapshot_backup.attributes["snapshots_in_hassio"] }}")' for attribute '_state' in entity 'sensor.snapshots_in_hassio_train'
2021-01-18 20:46:46 WARNING (MainThread) [custom_components.hacs] You have custom-components/sensor.rpi_power installed with HACS this repository has been removed, please consider removing it. Removal reason (removal)
2021-01-18 20:46:47 WARNING (MainThread) [custom_components.hacs] custom-components/sensor.rpi_power - Repository is archived.
2021-01-18 20:46:53 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 20 seconds
2021-01-18 20:46:55 WARNING (MainThread) [homeassistant.components.upnp] Wanted UPnP/IGD device with UDN/ST "uuid:167f3dc0-1dd2-11b2-ada8-c0a0bb8c4a93"/"urn:schemas-upnp-org:device:InternetGatewayDevice:1" not found, aborting
2021-01-18 20:46:55 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 10 seconds
2021-01-18 20:46:55 WARNING (MainThread) [homeassistant.components.upnp] Wanted UPnP/IGD device with UDN/ST "uuid:3F815285-AB5A-88E0-AA44-1CBDB9A81D68"/"urn:schemas-upnp-org:device:InternetGatewayDevice:1" not found, aborting
2021-01-18 20:46:55 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 10 seconds
2021-01-18 20:47:15 WARNING (MainThread) [homeassistant.components.upnp] Wanted UPnP/IGD device with UDN/ST "uuid:167f3dc0-1dd2-11b2-ada8-c0a0bb8c4a93"/"urn:schemas-upnp-org:device:InternetGatewayDevice:1" not found, aborting
2021-01-18 20:47:15 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 20 seconds
2021-01-18 20:47:15 WARNING (MainThread) [homeassistant.components.upnp] Wanted UPnP/IGD device with UDN/ST "uuid:3F815285-AB5A-88E0-AA44-1CBDB9A81D68"/"urn:schemas-upnp-org:device:InternetGatewayDevice:1" not found, aborting
2021-01-18 20:47:15 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 20 seconds
2021-01-18 20:47:16 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 40 seconds`

```

**Comment by balbulator** [comment]
Может быть проблема, что НА работает через duckdns?

**Comment by balbulator** [comment]
Вопрос снимается, разобрался. Проблема в том, что я прописал в конфиге ссылку на файл, а в файле еще раз указал "sonoff:"
Убрал из файла первую строчку "sonoff:" и все заработало
Благодарю за попытку помочь
