### ISSUE TITLE
ZigBee Bridge

### ISSUE THREAD

**Issue by dojopol** [AlexxIT/SonoffLAN#289]
I have a lot of switch all works.
I addes zigbee bridge + some sensors and I got such error

Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:162
Integration: Sonoff (documentation)
First occurred: 11:02:45 (87 occurrences)
Last logged: 12:55:04

Cloud WS exception: '1000fc5a22'
Cloud WS exception: 'a480003db2'
Cloud WS exception: 'a480003db3'
Cloud WS exception: 'a480003db4'
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 234, in _connect
    await self._process_ws_msg(resp)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 162, in _process_ws_msg
    device = self.devices[deviceid]
KeyError: '1000fc5a22'

What can I get it?

**Comment by dojopol** [comment]
I managed

**Comment by dojopol** [comment]
I turn on debug , some restarts and is ok now.
