### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by wishie** [AlexxIT/SonoffLAN#298]
I've been using this integration for months without issue, but over the last few days, ive had lots of issues with cloud devices (Zigbee etc) and the logs shows the following:

````
Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:147 
Integration: Sonoff (documentation) 
First occurred: 8:24:18 PM (2 occurrences) 
Last logged: 8:24:18 PM

Coolkit API error: Cannot connect to host eu-api.coolkit.cc:8080 ssl:default [Name does not resolve]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 964, in _create_direct_connection
    hosts = await asyncio.shield(self._resolve_host(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 829, in _resolve_host
    addrs = await \
  File "/usr/local/lib/python3.8/site-packages/aiohttp/resolver.py", line 29, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 147, in _api
    r = await coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host eu-api.coolkit.cc:8080 ssl:default [Name does not resolve]
````

**Comment by AlexxIT** [comment]
Name does not resolve => problem with Internet/DNS

**Comment by wishie** [comment]
I thought that, but if I login to the HA machine, it can ping/resolve it just fine..

**Comment by wishie** [comment]
I have some strange things going on, but I think it is a local network issue.
