### ISSUE TITLE
Error during setup of sonoff component

### ISSUE THREAD

**Issue by santosonit** [AlexxIT/SonoffLAN#306]
Hi there,

Ive been trying to get this Sonoff 4CH V2.0 to be discovered, but this is stopping me...

Got my account setup alright on ewelink and my configuration.yaml file is as follows:

sonoff:
    username: username@gmail.com
    password: password
    reload: always

Here's the log:
`
Logger: homeassistant.setup
Source: custom_components/sonoff/sonoff_cloud.py:296
First occurred: 3:07:08 PM (1 occurrences)
Last logged: 3:07:08 PM

Error during setup of component sonoff
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/sonoff/__init__.py", line 102, in async_setup
    if await registry.cloud_login(config[CONF_USERNAME],
  File "/config/custom_components/sonoff/sonoff_main.py", line 110, in cloud_login
    return await self.cloud.login(username, password)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 296, in login
    self._apikey = resp['user']['apikey']
KeyError: 'user'
`

I've tried installing different versions of the integration - all of them give me the error above.

If anyone could point me to the right direction, that'd be appreciated.

Cheers,

**Comment by thynotai** [comment]
I have a Sonoff Basic R3.  Same problem.  It works in the Ewelink app but can't get it working in Home Assistant.

Sonoff LAN V2.3.2
HA Core 2020.12.1
HA OS 4.2

configuration.yaml file entry:
sonoff:
  username: myusername@yahoo.com
  password: mypassword

The error log:

Logger: homeassistant.setup
Source: custom_components/sonoff/sonoff_cloud.py:296
First occurred: 8:40:10 PM (1 occurrences)
Last logged: 8:40:10 PM
Error during setup of component sonoff

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/sonoff/__init__.py", line 102, in async_setup
    if await registry.cloud_login(config[CONF_USERNAME],
  File "/config/custom_components/sonoff/sonoff_main.py", line 110, in cloud_login
    return await self.cloud.login(username, password)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 296, in login
    self._apikey = resp['user']['apikey']
KeyError: 'user'

**Comment by thynotai** [comment]
Shame and embarrassment > The password was wrong in configuration.yaml.   It works now

**Comment by AlexxIT** [comment]
Probably fixed in latest master-version
