### ISSUE TITLE
Uncaught Thread Exception

### ISSUE THREAD

**Issue by trannamhung** [AlexxIT/SonoffLAN#333]
Hi,

I am using Sonoff Pow R2 and add it to Home Assistant (Hass). However, the switch often goes disabled after a short time. If I restart Hass, it comes available then unavailable gain. Here is the logs from Hass.

Logger: root
Source: custom_components/sonoff/sonoff_local.py:185
First occurred: 8:44:26 AM (1 occurrences)
Last logged: 8:44:26 AM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1750, in run
    self._service_state_changed.fire(
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1508, in fire
    h(**kwargs)
  File "/config/custom_components/sonoff/sonoff_local.py", line 185, in _zeroconf_handler
    state = json.loads(data)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 188 (char 187)

**Comment by AlexxIT** [comment]
Please goto file `/config/custom_components/sonoff/sonoff_local.py` and add line:

    _LOGGER.warning(data)

before line 185:

    state = json.loads(data)

And then show logs when error occured

**Comment by trannamhung** [comment]
Logger: custom_components.sonoff.sonoff_local
Source: custom_components/sonoff/sonoff_local.py:184
Integration: Sonoff (documentation, issues)
First occurred: 9:02:03 AM (68 occurrences)
Last logged: 9:03:20 AM

    b'{"alarmVValue":[-1,-1],"alarmCValue":[-1,-1],"alarmPValue":[-1,-1],"switch":"on","startup":"on","pulse":"off","pulseWidth":500,"sledOnline":"on","power":42.72,"voltage":229.48,"current":0.20,"ssid":"Uknown","bssid":"88:d2:74:ff:55:8b"}'
    b'{"alarmVValue":[-1,-1],"alarmCValue":[-1,-1],"alarmPValue":[-1,-1],"switch":"on","startup":"on","pulse":"off","pulseWidth":500,"sledOnline":"on","power":42.77,"voltage":229.09,"current":0.20,"ssid":"Uknown","bssid":"88:d2:74:ff:55:8b"}'
    b'{"alarmVValue":[-1,-1],"alarmCValue":[-1,-1],"alarmPValue":[-1,-1],"switch":"on","startup":"on","pulse":"off","pulseWidth":500,"sledOnline":"on","power":42.91,"voltage":228.95,"current":0.20,"ssid":"Uknown","bssid":"88:d2:74:ff:55:8b"}'
    b'{"alarmVValue":[-1,-1],"alarmCValue":[-1,-1],"alarmPValue":[-1,-1],"switch":"on","startup":"on","pulse":"off","pulseWidth":500,"sledOnline":"on","power":42.87,"voltage":229.29,"current":0.20,"ssid":"Uknown","bssid":"88:d2:74:ff:55:8b"}'
    b'{"alarmVValue":[-1076222718,-1076222718],"alarmCValue":[-1076222718,-1076222718],"alarmPValue":[-1076222718,-1076222718],"switch":"on","startup":"on","pulse":"off","pulseWidth":2147483647.-2147483549,"sledOnline":"on","power":2147483647.-2147483549,"voltage":2147483647.-2147483549,"current":0.20,"ssid":"xxxxxx","bssid":"xx:xx:xx:xx:xx:xx"}'

**Comment by trannamhung** [comment]
I don't see the voltage and power updated. I set they refreshed every 1s.

**Comment by trannamhung** [comment]
Here is my configuration.yaml for Sonoff Pow R2.

sonoff:
  sensors: [temperature, humidity, power, current, voltage, rssi]
  force_update: [temperature, humidity, power, current, voltage, rssi]
  scan_interval: '00:00:01'  # (optional) default 5 minutes
  devices:
    xxx:
      devicekey: xxx
      name: Master Fan Switch

**Comment by AlexxIT** [comment]
1 second is to low interval. If you using auto mode - you can remove any `force_update`. With cloud connection POW will send data update in real time.

**Comment by trannamhung** [comment]
Dear Alex.

Thanks for your feedback. I just wonder how to set auto mode? I just want to use local LAN only- no cloud.

In addition, I want to set scan_interval = 1s because I want to base on the voltage to set the status of my fan. For instance, if the current >= 0.1 A --> fan on, else off.

In general, I am facing with 2 issues: 

1. My power consumption do not works. Here is the configuration.

- platform: template
    sensors:
      sonoff_today_consumption:
        friendly_name: Today consumpion
        unit_of_measurement: kWh
        value_template: "{{ state_attr('switch.sonoff_xxx', 'consumption').0 }}"
      sonoff_ten_days_consumption:
        friendly_name: 10 days consumpion
        unit_of_measurement: kWh
        value_template: "{% set p=state_attr('switch.sonoff_xxx', 'consumption') %}{{ p[:10]|sum if p }}" 

2. My Sonoff Pow R2 often unavailable.

Many thanks for your help!

**Comment by AlexxIT** [comment]
Consumption loads from cloud

**Comment by AlexxIT** [comment]
Fixed in latest release

**Comment by trannamhung** [comment]
Thanks Alex!
