### ISSUE TITLE
Error while receiving local data

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/SonoffLAN#352]
From [community](https://community.home-assistant.io/t/control-sonoff-devices-with-ewelink-original-firmware-over-lan-and-or-cloud/167567/146?u=alexxit)

```
Logger: root
Source: custom_components/sonoff/sonoff_local.py:178
First occurred: 7:27:14 AM (1 occurrences)
Last logged: 7:27:14 AM
Uncaught thread exception

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1755, in run
    self._service_state_changed.fire(
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1513, in fire
    h(**kwargs)
  File "/config/custom_components/sonoff/sonoff_local.py", line 178, in _zeroconf_handler
    if data.startswith(b'{"rf'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by AlexxIT** [comment]
Fixed in latest release
