### ISSUE TITLE
Evry start HA - error in log 

### ISSUE THREAD

**Issue by enigmaspb** [AlexxIT/SonoffLAN#367]
Evry start/restart of ha i see in log this error and all work normal . 

```
2021-02-04 07:32:48 ERROR (Sonoff_LAN) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/homeassistant/lib/python3.8/site-packages/zeroconf/__init__.py", line 1755, in run
    self._service_state_changed.fire(
  File "/opt/homeassistant/lib/python3.8/site-packages/zeroconf/__init__.py", line 1513, in fire
    h(**kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/sonoff/sonoff_local.py", line 178, in _zeroconf_handler
    if data.startswith(b'{"rf'):
```

**Comment by AlexxIT** [comment]
Show your config

**Comment by enigmaspb** [comment]
```
sonoff:
  username: !secret sonoff_login
  password: !secret saures_password
  reload: always  
  scan_interval: '00:01:00' 
  devices:
    100XXXXXXX:
      sensors: [power, current, voltage, rssi]
      force_update: True
    100XXXXXXX:
      sensors: [power, current, voltage, rssi]
      force_update: True
```

**Comment by elchanly** [comment]
Had the same problem. @enigmaspb try to overwrite files manually at folder custom_components, and then restart home assistant.

**Comment by enigmaspb** [comment]
confirmed ! 
I download git version (git clone) and overwrite all files in custom_components/sonoff 
and clean sonoff/__pycache__
restart ha and no any errors in log .
Big thks !

**Comment by AlexxIT** [comment]
Yes, it was fixed in latest beta
