### ISSUE TITLE
Light Bulb B02 is not working with last update

### ISSUE THREAD

**Issue by marianobntz** [AlexxIT/SonoffLAN#390]
The filament light bulb is failing to register in HA with this error:

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 421, in _async_add_entity
capabilities=entity.capability_attributes,
File "/config/custom_components/sonoff/light.py", line 608, in capability_attributes
ATTR_MIN_MIREDS: round(self._min_mireds),
TypeError: type NoneType doesn't define round method

I can help debugging with this lamp if needed.

**Comment by AlexxIT** [comment]
Will fix it

**Comment by marianobntz** [comment]
By changing the _min_mireds and _max_mireds to 0 instead on None I was able to get them appear in HA, but operations fail to execute. If I change the status in ewelink, the status is reflected in HA.
The brightness changes in ewelink are properly shown in HA, but the color temperature do not appear in HA.
Color effects like bright, reading show up in HA properly, but changes in HA do not work

**Comment by marianobntz** [comment]
Turn off work from HA, turn ON do not work.
This is the log for turn on...

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/sonoff/sonoff_main.py:154
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: February 16, 2021, 9:07:17 PM (12 occurrences)
Last logged: 12:10:40 PM

[140556118507280] coroutine raised StopIteration
[140555882906912] coroutine raised StopIteration
[140555913336576] coroutine raised StopIteration
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_local.py", line 270, in send
    command = data.get('cmd') or next(iter(data))
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 233, in async_handle_light_on_service
    await light.async_turn_on(**params)
  File "/config/custom_components/sonoff/light.py", line 645, in async_turn_on
    await self.registry.send(self.deviceid, payload)
  File "/config/custom_components/sonoff/sonoff_main.py", line 154, in send
    state['local'] = await self.local.send(deviceid, params, seq, 1)
RuntimeError: coroutine raised StopIteration`

**Comment by AlexxIT** [comment]
Is is work in latest beta? If don't - show error log again.

**Comment by AlexxIT** [comment]
Also you can share your device to my account sonofflan@gmail.com

**Comment by marianobntz** [comment]
> Is is work in latest beta? If don't - show error log again.

How do I install a beta? I do not see the update available in HACS.

What country are you? I believe I need the country + email to share, right?

**Comment by AlexxIT** [comment]
In HACS you should select option reinstall.
County Russia

**Comment by marianobntz** [comment]
on startup I got 
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 424, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/config/custom_components/sonoff/light.py", line 608, in capability_attributes
    ATTR_MIN_MIREDS: round(self._min_mireds),
TypeError: type NoneType doesn't define __round__ method
`

**Comment by marianobntz** [comment]
and we cannot share devices to people in other countries. I am in Argentina.

**Comment by AlexxIT** [comment]
Oh, try latest master version. From same reinstall window drop down menu

**Comment by marianobntz** [comment]
with master version the system recognized the lights from start, I was able to see the status, turn on and change the preset.
But turning on, changing brightness or color raised exceptions.

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/sonoff/sonoff_main.py:154
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:13:28 AM (9 occurrences)
Last logged: 10:24:39 AM

[140532541265808] coroutine raised StopIteration
[140532548238592] coroutine raised StopIteration
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_local.py", line 275, in send
    command = data.get('cmd') or next(iter(data))
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 642, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 679, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 235, in async_handle_light_on_service
    await light.async_turn_on(**params)
  File "/config/custom_components/sonoff/light.py", line 642, in async_turn_on
    await self.registry.send(self.deviceid, payload)
  File "/config/custom_components/sonoff/sonoff_main.py", line 154, in send
    state['local'] = await self.local.send(deviceid, params, seq, 1)
RuntimeError: coroutine raised StopIteration`

**Comment by AlexxIT** [comment]
Can you show bulb info from sonoff.json file in your config folder? You can remove all private data.

**Comment by marianobntz** [comment]
just installed 2.4.0 and it seems to be working fine. it takes some time to reflect but it works.

**Comment by marianobntz** [comment]
The only thing that is not read properly is the color temperature, I will open a different issue for it.
