### ISSUE TITLE
Sonoff Bulb B-02-B-A60 doesnt have attributes

### ISSUE THREAD

**Issue by minskmail** [AlexxIT/SonoffLAN#394]
Sonoff Bulb B-02-B-A60 doesnt have attributes like brightness & color temp. Recognized like switch. by default.
If I change it to light via configuration, nothing changes except domain name (switch to light)

![image](https://user-images.githubusercontent.com/25284132/108439463-5d250200-7262-11eb-96d2-0560d7d688cc.png)
![image](https://user-images.githubusercontent.com/25284132/108439597-a5dcbb00-7262-11eb-9f97-e164edd25eb1.png)

**Comment by AlexxIT** [comment]
Have you tried latest beta?

**Comment by minskmail** [comment]
> Have you tried latest beta?

v2.4b1 doesnt recognises at all.  v2.4b0 just like switch same as latest stable version

**Comment by minskmail** [comment]
some logs on v2.4b1

```
2021-02-19 11:16:53 ERROR (MainThread) [homeassistant.components.light] Error adding entities for domain light with platform sonoff
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 421, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/config/custom_components/sonoff/light.py", line 608, in capability_attributes
    ATTR_MIN_MIREDS: round(self._min_mireds),
TypeError: type NoneType doesn't define __round__ method
2021-02-19 11:16:53 ERROR (MainThread) [homeassistant.components.light] Error while setting up sonoff platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 206, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 421, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/config/custom_components/sonoff/light.py", line 608, in capability_attributes
    ATTR_MIN_MIREDS: round(self._min_mireds),
TypeError: type NoneType doesn't define __round__ method
```

**Comment by jellevervloessem** [comment]
Latest version fixed it for me!

**Comment by minskmail** [comment]
> Latest version 2.4 fixed it for me!

In general, yes. But still there is an issue with color temp. In Developer Tools for color temp reported values range 
from 153 (for warm) to **-148** (for cool)
![image](https://user-images.githubusercontent.com/25284132/110822834-87d30b00-82a2-11eb-8428-77641d0cd0b6.png)
![image](https://user-images.githubusercontent.com/25284132/110823057-c49f0200-82a2-11eb-9add-2f1fca10a841.png)

at the same time in lovelace range of color temp from 153 to 454

![image](https://user-images.githubusercontent.com/25284132/110823705-6de5f800-82a3-11eb-8af0-348435b40f83.png)
![image](https://user-images.githubusercontent.com/25284132/110824653-4e030400-82a4-11eb-84e5-d3213c1a3d50.png)

So if you change colortemp in lovelace it always shows value 153

**Comment by minskmail** [comment]
Fixed
