### ISSUE TITLE
Sonoff ZB Bridge causing errors 

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/SonoffLAN#404]
After adding ZB Bridge in Ewelink - HA Core log contains:

```
2021-02-27 16:23:40 ERROR (MainThread) [custom_components.sonoff.sonoff_cloud] Cloud WS exception: '100103696c'
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 234, in _connect
    await self._process_ws_msg(resp)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 162, in _process_ws_msg
    device = self.devices[deviceid]
KeyError: '100103696c'
2021-02-27 16:26:20 ERROR (MainThread) [custom_components.sonoff.sonoff_cloud] Cloud WS exception: '100103696c'
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 234, in _connect
    await self._process_ws_msg(resp)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 162, in _process_ws_msg
    device = self.devices[deviceid]
KeyError: '100103696c'
```
100103696c  - ID of ZBBridge.

**Comment by Masterz69** [comment]
![image](https://user-images.githubusercontent.com/15225823/109398126-63db0580-7943-11eb-9fb6-131309525c50.png)

**Comment by AlexxIT** [comment]
Probably fixed in latest master-version
