### ISSUE TITLE
ZB Bridge child device - still online in HA after removed in Ewelink

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/SonoffLAN#417]
Done: Sonoff ZB Bridge - child device added and then removed.

It appears in HA:
![image](https://user-images.githubusercontent.com/15225823/110203222-928e3a00-7e75-11eb-9173-5790d963f8f5.png)
That is very fine, measurements come in.

After child device removed from ZB Bridge, it disppears in Ewelink, but still show "cloud: online" in HA:
![image](https://user-images.githubusercontent.com/15225823/110203244-bcdff780-7e75-11eb-9c0a-917f91fffb64.png)
After 30 minutes at moment.

Core log contains:
2021-03-06 11:43:10 ERROR (MainThread) [custom_components.sonoff.sonoff_cloud] Cloud WS exception: 'a48000d1f2'
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 234, in _connect
    await self._process_ws_msg(resp)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 162, in _process_ws_msg
    device = self.devices[deviceid]
KeyError: 'a48000d1f2'
2021-03-06 11:43:30 ERROR (MainThread) [custom_components.sonoff.sonoff_cloud] Cloud WS exception: 'a48000d1f2'
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 234, in _connect
    await self._process_ws_msg(resp)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 162, in _process_ws_msg
    device = self.devices[deviceid]
KeyError: 'a48000d1f2'

**Comment by AlexxIT** [comment]
Same as #404
