### ISSUE TITLE
Offline device causing log entries

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/SonoffLAN#419]
It not causing any real issues.
As it devce statuses are updated very well.
I really appreciate it - online/offline devices shown in HA accordingly and very fast.

But may be there is something to fix:

2021-03-09 09:39:29 ERROR (MainThread) [custom_components.sonoff.sonoff_local] 10010a4da0 => Local4 | {'cmd': 'info'}
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_local.py", line 280, in send
    r = await self.session.post(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

After recent HA restarts they appeared: 
2021-03-09 03:25:51 ERROR (MainThread) [custom_components.sonoff.sonoff_local] 10010a4da0 => Local4 | {'cmd': 'info'}
2021-03-09 09:39:29 ERROR (MainThread) [custom_components.sonoff.sonoff_local] 10010a4da0 => Local4 | {'cmd': 'info'}

**Comment by AlexxIT** [comment]
Do you use latest component version?
