### ISSUE TITLE
I caint get Sonoff LAN to work

### ISSUE THREAD

**Issue by tonyfitzs** [AlexxIT/SonoffLAN#438]
Hi Alex, I have just installed Sonoff LAN, but I am unable to get it to work. I keep getting an error but the error dosnt tell me much useful. 

```
Logger: homeassistant.setup
Source: custom_components/sonoff/sonoff_cloud.py:298
First occurred: 7:23:41 PM (1 occurrences)
Last logged: 7:23:41 PM

Error during setup of component sonoff
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/sonoff/__init__.py", line 102, in async_setup
    if await registry.cloud_login(config[CONF_USERNAME],
  File "/config/custom_components/sonoff/sonoff_main.py", line 117, in cloud_login
    return await self.cloud.login(username, password)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 298, in login
    self._apikey = resp['user']['apikey']
KeyError: 'user'
```

based on what I can determin (but I am not a developer) it looks like its looking for an API key, I dont know where to find this or set it up. are you able to shed any light?

Im useing Home Assitant Core version 2021.3.4 supervisor-2021.03.6 running on a ProxMox VM. 

I have turned on Debug mode and this is what is reported

2021-03-24 19:23:34  DEBUG    main          SysInfo: {'version': '2021.3.4', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.8.7', 'docker': True, 'arch': 'x86_64', 'os_name': 'Linux', 'os_version': '5.4.99', 'supervisor': '2021.03.6', 'host_os': 'Home Assistant OS 5.12', 'docker_version': '19.03.13', 'chassis': 'vm'}
2021-03-24 19:23:34  DEBUG    main          CLOUD mode start
2021-03-24 19:23:38  DEBUG    sonoff_cloud  Redirect to region: us

**Comment by andrus2049** [comment]
You probably need to fill your Sonoff cloud account data in configuration.yaml.

See:
https://github.com/AlexxIT/SonoffLAN#cloud-only-mode

**Comment by AlexxIT** [comment]
Show your config

**Comment by tonyfitzs** [comment]
as per the instructions I am using a secret file for the username and password 

sonoff:
  username: !secret sonuser
  password: !secret sonpwrd
  mode: cloud
  debug: True
  reload: always

**Comment by tonyfitzs** [comment]
stupid markup..... didnt show indents properly trying again....


sonoff:
  username: !secret sonuser
  password: !secret sonpwrd
  mode: cloud
  debug: True
  reload: always

**Comment by tonyfitzs** [comment]
`sonoff:
  username: !secret sonuser
  password: !secret sonpwrd
  mode: cloud
  debug: True
  reload: always`

**Comment by andrus2049** [comment]
_reload: always_  
should be used only when 
_mode: local_

**Comment by AlexxIT** [comment]
@tonyfitzs check this #386
Maybe you have same problem

**Comment by tonyfitzs** [comment]
it dosnt apear so. if I click on either link i get this result...

Welcome to OpenResty!
If you see this page, the OpenResty web platform is successfully installed and working. Further configuration is required.

For online documentation and support please refer to openresty.org.
Commercial support is available at openresty.com.

Thank you for flying OpenResty.

**Comment by AlexxIT** [comment]
Probably fixed in latest master-version
