### ISSUE TITLE
Error adding sonoff micro

### ISSUE THREAD

**Issue by antoweb** [AlexxIT/SonoffLAN#466]
I have added two sonoff micro to account. Added the following lines to configuration.yaml

1000xxxxxx:
  device_class: switch
  name: Firestick Camera
1000xxxxxx:
  device_class: switch
  name: Firestick Cameretta
After restart no device in HA and in log following error:

2021-04-12 11:05:58 ERROR (MainThread) [homeassistant.components.switch] Error while setting up sonoff platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 213, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 514, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 546, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/sonoff/switch.py", line 44, in async_added_to_hass
device = self._init()
File "/config/custom_components/sonoff/sonoff_main.py", line 242, in _init
self._update_handler(state, attrs)
File "/config/custom_components/sonoff/switch.py", line 51, in _update_handler
self._is_on = any(self._is_on_list(state))
File "/config/custom_components/sonoff/sonoff_main.py", line 259, in _is_on_list
return [state['switch'] == 'on']
KeyError: 'switch'

**Comment by antoweb** [comment]
Solved. For micro i have to insert _1 also if is only 1 channel like this:

1000xxxx_1:
device_class: switch
name: Firestick Camera
1000xxxx_1:
device_class: switch
name: Firestick Cameretta

**Comment by AlexxIT** [comment]
Switch is device class by default
