### ISSUE TITLE
Issues setting Sonoff Zigbee Bridge and Zigbee devices.

### ISSUE THREAD

**Issue by leoheck** [AlexxIT/SonoffLAN#470]
Hi @AlexxIT I am trying to setup this HACS integration with my Sonoff devices (Zigbee Bridge, Temperature Sensor, Presence Sensor, Door Sensor)

I double-checked and I am using the right user/password. But I'm still seeing this. Not sure what it means, since I just started to use Home Assistant a couple of days ago.

I am running this on a Raspberry PI, with Raspbian 10 (I'm still using Python 3.7.3, I am not sure if this can be the issue here)
I installed the Home Assistant Core and HACS integration.

```
Apr 13 14:47:32 hass hass[3562]: 2021-04-13 14:47:32 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
Apr 13 14:47:32 hass hass[3562]: 2021-04-13 14:47:32 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
Apr 13 14:47:47 hass hass[3562]: 2021-04-13 14:47:47 ERROR (MainThread) [homeassistant.setup] Error during setup of component sonoff
Apr 13 14:47:47 hass hass[3562]: Traceback (most recent call last):
Apr 13 14:47:47 hass hass[3562]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 213, in _async_setup_component
Apr 13 14:47:47 hass hass[3562]:     result = await task
Apr 13 14:47:47 hass hass[3562]:   File "/home/homeassistant/.homeassistant/custom_components/sonoff/__init__.py", line 103, in async_setup
Apr 13 14:47:47 hass hass[3562]:     config[CONF_PASSWORD]):
Apr 13 14:47:47 hass hass[3562]:   File "/home/homeassistant/.homeassistant/custom_components/sonoff/sonoff_main.py", line 117, in cloud_login
Apr 13 14:47:47 hass hass[3562]:     return await self.cloud.login(username, password)
Apr 13 14:47:47 hass hass[3562]:   File "/home/homeassistant/.homeassistant/custom_components/sonoff/sonoff_cloud.py", line 298, in login
Apr 13 14:47:47 hass hass[3562]:     self._apikey = resp['user']['apikey']
Apr 13 14:47:47 hass hass[3562]: KeyError: 'user'
```

Do you have any idea what I am doing wrong? 
Thank you.

Edit: This is what I have on my `configuration.yaml` config file.

```
sonoff:
  username: mymail@gmail.com
  password: mypassword
```

These are the version of the integrations
- HACS version 1.11.3
- SonoffLan version 2.4.3

**Comment by leoheck** [comment]
It looks like it was a problem with the credentials. Maybe something happened during copy and paste.

**Comment by leoheck** [comment]
@AlexxIT one last question.

My devices are:
- ZBBridge (Zigbee Bridge)
- ZBMini (Smart Switch)
- SNZB-02 (Temperature/Humidity Sensor)
- SNZB-03 (Motion Sensor)
- SNZB-04 (Door Sensor)

Where should I see these devices?
Should I add them manually on `configuration.yaml` or Home Assistant will list them somewhere?
I don't know how to proceed to find/see these devices.

**Comment by leoheck** [comment]
Oh, I am seeing sensors on logbook.
![image](https://user-images.githubusercontent.com/1277920/114574725-e0097e00-9c4f-11eb-9313-2b5bc73614be.png)
