### ISSUE TITLE
Cloud WS exception: invalid state

### ISSUE THREAD

**Issue by AlexanderZoom** [AlexxIT/SonoffLAN#477]
Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:76
Integration: Sonoff (documentation, issues)
First occurred: 4:10:13 (1 occurrences)
Last logged: 4:10:13

Cloud WS exception: invalid state
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 237, in _connect
    await self._process_ws_msg(resp)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 410, in _process_ws_msg
    await self._cloud_process_ws_msg(data)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 156, in _process_ws_msg
    await self._set_response(data)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 76, in _set_response
    self._waiters[sequence].set_result(result)
asyncio.exceptions.InvalidStateError: invalid state

**Comment by Gferretta** [comment]
Idem

**Comment by AlexxIT** [comment]
Are you sure you're using the latest version of the component?

**Comment by Gferretta** [comment]
> Are you sure you're using the latest version of the component?

Hi Alex
In my case, Yes. Lastest release.

**Comment by Gferretta** [comment]
![Screenshot_20210427-092330_Home Assistant.jpg](https://user-images.githubusercontent.com/65413059/116240783-997d4e80-a73a-11eb-8c28-28f97ace21ea.jpg)

**Comment by urielz** [comment]
Reporting the same error on core-2021.5.5:

```
This error originated from a custom integration.

Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:76
Integration: Sonoff (documentation, issues)
First occurred: 5:41:58 AM (1 occurrences)
Last logged: 5:41:58 AM

Cloud WS exception: invalid state
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 237, in _connect
    await self._process_ws_msg(resp)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 417, in _process_ws_msg
    await self._cloud_process_ws_msg(data)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 156, in _process_ws_msg
    await self._set_response(data)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 76, in _set_response
    self._waiters[sequence].set_result(result)
asyncio.exceptions.InvalidStateError: invalid state
```

**Comment by chinyaolin** [comment]
same issue
Sonoff LAN version : 2.4.6
HA version : core-2021.6.3 (Home Assistant OS 5.13)

`Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:76
Integration: Sonoff (documentation, issues)
First occurred: 2021年6月8日 23:59:05 (2 occurrences)
Last logged: 2021年6月9日 13:59:19

Cloud WS exception: invalid state
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 237, in _connect
    await self._process_ws_msg(resp)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 417, in _process_ws_msg
    await self._cloud_process_ws_msg(data)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 156, in _process_ws_msg
    await self._set_response(data)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 76, in _set_response
    self._waiters[sequence].set_result(result)
asyncio.exceptions.InvalidStateError: invalid state`

**Comment by chinyaolin** [comment]
> same issue
> Sonoff LAN version : 2.4.6
> HA version : core-2021.6.3 (Home Assistant OS 5.13)
> 
> ```
> Logger: custom_components.sonoff.sonoff_cloud
> Source: custom_components/sonoff/sonoff_cloud.py:76
> Integration: Sonoff (documentation, issues)
> First occurred: 2021年6月8日 23:59:05 (2 occurrences)
> Last logged: 2021年6月9日 13:59:19
> 
> Cloud WS exception: invalid state
> Traceback (most recent call last):
>   File "/config/custom_components/sonoff/sonoff_cloud.py", line 237, in _connect
>     await self._process_ws_msg(resp)
>   File "/config/custom_components/sonoff/sonoff_cloud.py", line 417, in _process_ws_msg
>     await self._cloud_process_ws_msg(data)
>   File "/config/custom_components/sonoff/sonoff_cloud.py", line 156, in _process_ws_msg
>     await self._set_response(data)
>   File "/config/custom_components/sonoff/sonoff_cloud.py", line 76, in _set_response
>     self._waiters[sequence].set_result(result)
> asyncio.exceptions.InvalidStateError: invalid state
> ```

After login with my mobile APP (eWelink) and restart HA, everything goes fine, no more error

**Comment by Gferretta** [comment]
HA 2021.7.2
SonoffLan 2.4.6

issue continues.

**Comment by Gferretta** [comment]
Hi

In HA 2021.8.3 this issues stay.

**Comment by ega2002** [comment]
As of Home Assistant 2021.9.5, issue still present

**Comment by Gferretta** [comment]
> As of Home Assistant 2021.9.5, issue still present (latest SonoffLAN and POW R2 firmware).

Yes
Error Still present.   :(

**Comment by TTLucian** [comment]
HA Core 2021.12.2. Same error:
```
Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:76
Integration: Sonoff (documentation, issues)
First occurred: 01:58:24 (1 occurrences)
Last logged: 01:58:24

Cloud WS exception: invalid state
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 237, in _connect
    await self._process_ws_msg(resp)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 417, in _process_ws_msg
    await self._cloud_process_ws_msg(data)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 156, in _process_ws_msg
    await self._set_response(data)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 76, in _set_response
    self._waiters[sequence].set_result(result)
asyncio.exceptions.InvalidStateError: invalid state
```

**Comment by khaisilk1910** [comment]
![IMG_20220320_160909](https://user-images.githubusercontent.com/3167468/160281060-cd21ee51-c873-4c8a-b121-1379f7625977.jpg)
Me too

**Comment by khaisilk1910** [comment]
![Screenshot_2022-03-27-19-19-04-582_io homeassistant companion android](https://user-images.githubusercontent.com/3167468/160281085-be9b4367-816e-4f42-b1a0-6261eddfa030.jpg)
Me too.

**Comment by sipimokus** [comment]
Same issue:

```
Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:76
Integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: 2022. április 6. 23:04:00 (11 occurrences)
Last logged: 08:36:00

Cloud WS exception: invalid state
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 237, in _connect
    await self._process_ws_msg(resp)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 410, in _process_ws_msg
    await self._cloud_process_ws_msg(data)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 156, in _process_ws_msg
    await self._set_response(data)
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 76, in _set_response
    self._waiters[sequence].set_result(result)
asyncio.exceptions.InvalidStateError: invalid state
```

HA: core-2022.3.8
SonoffLan: v2.4.3

Fresh install both.

**Comment by AlexxIT** [comment]
Fixed in latest master-version. Will be in next release.
