### ISSUE TITLE
Install fails on HA 2021.6.6: bad configuration in sonoff initialisation

### ISSUE THREAD

**Issue by preeve9534** [AlexxIT/SonoffLAN#540]
Log error:

ogger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:518
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8 July 2021, 21:01:28 (1 occurrences)
Last logged: 8 July 2021, 21:01:28

[1865689072] The system cannot restart because the configuration is not valid: Component error: sonoff - Integration 'sonoff' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 518, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Component error: sonoff - Integration 'sonoff' not found.

**Comment by AlexxIT** [comment]
Maybe you using very old component version?

**Comment by preeve9534** [comment]
Hi Alex. Latest Release on GitHub.

**Comment by AlexxIT** [comment]
Maybe you have other errors in log. Which describe why the component cannot start.

**Comment by preeve9534** [comment]
Hi again Alex. There were no other errors in the log, other than with the Kodi component.

But, I did two consecutive hard reboots of the machine hosting my HA installation and the component now works. One reboot was not enough. Might be worth adding to the documentation that an HA configuration-> restart may not be enough to get the component working.

Thanks for your help.
