### ISSUE TITLE
.sonoff.json file does not restore after adding new devices

### ISSUE THREAD

**Issue by tgribble** [AlexxIT/SonoffLAN#554]
hello

thanks for the great component.

i have 10+ sonoff switches in the house working ok. all are up to fw 3.5.1 ( sonoff basics ) . 
i have added a sonoff minir2 fw 3.6.0 to the house. 
ewelink is ver 4.13 ( apple iphone )
SonoffLAN ver 2.4.6

issue is i deleted the .sonoff.json as per instructions and restart HA, but the .sonoff.json file does not regenerate 

my config file ( sonoff ) is:
```
sonoff:
  username: !secret sonoff_email
  password: !secret sonoff_password
```
i think my issue is similar to #https://github.com/AlexxIT/SonoffLAN/issues/202 which i am not sure if it was resolved as it closed before resolution

i have checked and rechecked my username and password which are fine on the ewelink app to sign in

any help would be good as i cant use HA to access the new minir2 at the moment and have more to install

thankyou

**Comment by tgribble** [comment]
checked log files
3 issues for sonoff
hoping this will help to diagnose?

thanks 

**Can't connect to eWeLink Cloud**
4:59:10 – (WARNING) Sonoff (custom integration)
Logger: custom_components.sonoff
Source: custom_components/sonoff/__init__.py:107
Integration: Sonoff (documentation, issues)
First occurred: 4:59:10 (1 occurrences)
Last logged: 4:59:10

**Login error: None**
4:59:10 – (ERROR) Sonoff (custom integration)
Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:289
Integration: Sonoff (documentation, issues)
First occurred: 4:59:10 (1 occurrences)
Last logged: 4:59:10

**Coolkit API error: Cannot connect to host eu-api.coolkit.cc:8080 ssl:default [Connect call failed ('::', 8080, 0, 0)]
4:59:10 – (ERROR) Sonoff (custom integration)**
Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:148
Integration: Sonoff (documentation, issues)
First occurred: 4:59:10 (1 occurrences)
Last logged: 4:59:10

Coolkit API error: Cannot connect to host eu-api.coolkit.cc:8080 ssl:default [Connect call failed ('::', 8080, 0, 0)]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('::', 8080, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 148, in _api
    r = await coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host eu-api.coolkit.cc:8080 ssl:default [Connect call failed ('::', 8080, 0, 0)]

**Comment by AlexxIT** [comment]
Maybe you have problem with internet on your Hass server. Or wrong DNS settings.

**Comment by tgribble** [comment]
Well done. Thanks. I run pihole on my server and DNS serve to it on my router. 

The issue was as you suspected the DNS problem. I disabled pihole and deleted the .sonoff.json file and restarted HA and the update went perfectly. 

Thankyou
