### ISSUE TITLE
HA can't start after putting sonoff in custom_components

### ISSUE THREAD

**Issue by JJJason1133** [AlexxIT/SonoffLAN#56]
Really need your help, thanks! 
What i did:
1. Putting "sonoff" folder in custom_components
2. Adding sonoff setting in the configuration.yaml file of HA, only add "usrname" and "password" 
Then I restarted the hass service, it just failed 

The log said:

2020-03-09 00:34:12 ERROR (Thread-5) [concurrent.futures] exception calling callback for <Future at 0x683ca8f0 state=finished returned int>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 463, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 618, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2020-03-09 00:34:12 ERROR (Thread-21) [concurrent.futures] exception calling callback for <Future at 0x684f8a90 state=finished returned list>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 463, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 618, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by JJJason1133** [comment]
After I updating my python and HA version to the latest, this problem solved.
