### ISSUE TITLE
basicr3 (ошибка питона)

### ISSUE THREAD

**Issue by dmabl** [AlexxIT/SonoffLAN#57]
При запуске
Exception in thread zeroconf-ServiceBrowser_eWeLink_100090a12f._ewelink._tcp.local.:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/site-packages/zeroconf/__init__.py", line 1483, in run
    handler(self.zc)
  File "/usr/local/lib/python3.7/site-packages/zeroconf/__init__.py", line 1423, in <lambda>
    zeroconf=zeroconf, service_type=self.type, name=name, state_change=state_change
  File "/usr/local/lib/python3.7/site-packages/zeroconf/__init__.py", line 1301, in fire
    h(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/zeroconf/__init__.py", line 1400, in on_change
    listener.update_service(*args)
  File "/config/custom_components/sonoff/__init__.py", line 313, in update_service
    if self._seq == properties['seq']:
KeyError: 'seq'
Включение/выключение работает, но состояние не изменяется (при включении переходит на 1-2сек во вкл а потом опять выкл)

**Comment by AlexxIT** [comment]
А обновления прошивки на устройство нет в приложении ewelink?

**Comment by dmabl** [comment]
Было, все заработало, спасибо
