### ISSUE TITLE
Unexpected error importing sonoff/recorder.py

### ISSUE THREAD

**Issue by pomah86** [AlexxIT/SonoffLAN#571]
Hi, I have been receiving the following error message in the logs:

```
Unexpected error importing sonoff/recorder.py
6:29:20 – (FEL) loader.py - Meddelandet inträffade först 6:29:20 och har hänt 5 gånger
```

When expanding it looks like this:

```
Logger: homeassistant.helpers.integration_platform
Source: loader.py:503
First occurred: 6:29:20 (5 occurrences)
Last logged: 6:29:20
Unexpected error importing sonoff/recorder.py
Unexpected error importing sonoff/system_health.py
Unexpected error importing sonoff/group.py
Unexpected error importing sonoff/logbook.py
Unexpected error importing sonoff/media_source.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.Sonoff.recorder'
```

As far as I can see there is no file named "recorder.py" in my custom components folder so I would get the error, but I would not know if there even should be a file like that there, or if it is an error with "loader.py".

**Comment by AlexxIT** [comment]
There are no such files in the integration

**Comment by HarvsG** [comment]
Seems to happen if the parent folder of the custom component differs from the name of the custom component in manifest.json
