### ISSUE TITLE
local mode suddenly stopped working

### ISSUE THREAD

**Issue by Tuxie** [AlexxIT/SonoffLAN#648]
Yesterday at 12pm (noon) CET, all my sonoff TH10s suddenly stopped working:
![image](https://user-images.githubusercontent.com/218697/144706702-90f3b5d0-a4b0-4f5f-b4a8-ff0155125086.png)
After restarting, this is all that ever appears in the debug log:
```
2021-12-04 11:38:44  DEBUG    main          SysInfo: {'version': '2021.11.5', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.9.7', 'docker': True, 'user': 'root', 'arch': 'aarch64', 'os_name': 'Linux', 'os_version': '5.10.75', 'supervisor': '2021.10.8', 'host_os': 'Home Assistant OS 6.6', 'docker_version': '20.10.8', 'chassis': 'embedded'}
2021-12-04 11:38:44  DEBUG    main          LOCAL mode start
2021-12-04 11:38:48  DEBUG    sonoff_cloud  5 devices loaded from the Cloud Server
2021-12-04 11:38:48  DEBUG    main          Init force_update for attributes: {'humidity', 'rssi', 'temperature'}
2021-12-04 11:38:48  DEBUG    main          Init auto sensors for: ['temperature', 'humidity', 'power', 'current', 'voltage', 'rssi', 'current_1', 'current_2', 'voltage_1', 'voltage_2', 'power_1', 'power_2']
```

I am using SonoffLAN `7fb7eb6` via HACS.
This is my `configuration.yaml`. The setup worked great for months until it suddenly died while I was doing nothing.
```
sonoff:
  mode: local
  debug: true
  scan_interval: "00:00:30"
  force_update: [temperature, humidity, rssi]
  username: !secret sonoff_username
  password: !secret sonoff_password
  sensors: [temperature, humidity, power, current, voltage, rssi]
  reload: always
```

The TH10s seem to be working in the eWeLink app and I can ping them. They are on fw 3.5.0 (and were the whole time).
If I remove `mode: local` I get data again, but only from the cloud according to the debug log.

What can I try? Where should I look?

**Comment by SunilKhusal** [comment]
Not too sure if related to the above, but I too am getting an error and the integration has stopped working. I get the following error:

```
This error originated from a custom integration.

Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:148
Integration: Sonoff (documentation, issues)
First occurred: 12:50:37 AM (1 occurrences)
Last logged: 12:50:37 AM

Coolkit API error: [Errno 1] [RSA] RSA lib (_ssl.c:2633)
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 148, in _api
    r = await coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 1] [RSA] RSA lib (_ssl.c:2633)
```

and also the following error:

```
ogger: homeassistant.setup
Source: custom_components/sonoff/sonoff_cloud.py:313
Integration: Sonoff (documentation, issues)
First occurred: 12:50:37 AM (1 occurrences)
Last logged: 12:50:37 AM

Error during setup of component sonoff
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 254, in _async_setup_component
    result = await task
  File "/config/custom_components/sonoff/__init__.py", line 104, in async_setup
    await registry.cloud_load_devices(cachefile)
  File "/config/custom_components/sonoff/sonoff_main.py", line 122, in cloud_load_devices
    newdevices = await self.cloud.load_devices()
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 313, in load_devices
    if resp['error'] == 0:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by AlexeiBaranov** [comment]
I have the same issue. In local mode, TH10 temperature sensors is unavailable. Cloud mode works fine - it allows me to see temperature. Sonoff debug shows temperature in both modes

Local mode:

```
Manufacturer SONOFF 
Model TH10
Sw version PSA-BHA-GL v3.5.0
Local online
Rssi -56
2021-12-19 00:32:59  DEBUG    switch        Refresh device state 1001190c76
2021-12-19 00:32:59  DEBUG    sonoff_cloud  1001190c76 => Cloud4 | {'_query': 'on'} | 1639863179695
2021-12-19 00:32:59  DEBUG    sonoff_cloud  1001190c76 <= Cloud3 | {'error': 0, 'deviceid': '1001190c76', ... 'sensorType': 'DS18B20', 'currentHumidity': 'unavailable', 'currentTemperature': '25.8', 'mainSwitch': 'off', 'deviceType': 'normal', 'only_device': {'ota': 'success'}, 'ssid': '...', 'bssid': '...'}}
```

Cloud mode:
```
Manufacturer SONOFF
Model TH10
Sw version PSA-BHA-GL v3.5.0
Cloud online
Rssi -56
Temperature 25.1
2021-12-19 00:48:41  DEBUG    switch        Refresh device state 1001190c76
2021-12-19 00:48:41  DEBUG    sonoff_cloud  1001190c76 => Cloud4 | {'_query': 'on'} | 1639864121290
2021-12-19 00:48:41  DEBUG    sonoff_cloud  1001190c76 <= Cloud3 | {'error': 0, 'deviceid': '1001190c76', ... 'sensorType': 'DS18B20', 'currentHumidity': 'unavailable', 'currentTemperature': '25.1', 'mainSwitch': 'off', 'deviceType': 'normal', 'only_device': {'ota': 'success'}, 'ssid': '...', 'bssid': '...'}}
```

**Comment by AlexeiBaranov** [comment]
UPD: My issue was related with https://github.com/AlexxIT/SonoffLAN/issues/527
Seems like the solution still not included in the latest release. Manually updated sonoff_local.py from github and issue disappeared

**Comment by mrb13676** [comment]
I think I still have the same problem. Have corrected the sonoff_local.py with the version in Master from GitHub. Still got a straight-line temp reading. 
How do I access the debug mode to see?

**Comment by Tuxie** [comment]
It started to work again after updating and restarting my network gear. No changes to any settings anywhere. 5 APs, 5 switches, 1 router, all UniFi.

**Comment by AlexeiBaranov** [comment]
> I think I still have the same problem. Have corrected the sonoff_local.py with the version in Master from GitHub. Still got a straight-line temp reading. How do I access the debug mode to see?
Debug mode is described here:
https://github.com/AlexxIT/SonoffLAN#component-debug-mode
Just add `debug: True` under `sonoff:`

**Comment by AlexxIT** [comment]
It's best not use mode local if you have some problems with your LAN setup
