### ISSUE TITLE
Cannot connect to host eu-api.coolkit.cc:8080

### ISSUE THREAD

**Issue by DJ-L1GhTeR** [AlexxIT/SonoffLAN#653]
2021-12-13 20:01:44 WARNING (MainThread) [homeassistant.setup] Setup of sonoff is taking over 10 seconds.
2021-12-13 20:02:07 ERROR (MainThread) [custom_components.sonoff.sonoff_cloud] Coolkit API error: Cannot connect to host eu-api.coolkit.cc:8080 ssl:default [Connect call failed ('52.57.118.192', 8080)]
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore # noqa
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
return await fut
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('52.57.118.192', 8080)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/sonoff/sonoff_cloud.py", line 148, in _api
r = await coro
File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
conn = await self._connector.connect(
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
proto = await self._create_connection(req, traces, timeout)
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
_, proto = await self._create_direct_connection(req, traces, timeout)
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
raise last_exc
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
transp, proto = await self._wrap_create_connection(
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host eu-api.coolkit.cc:8080 ssl:default [Connect call failed ('52.57.118.192', 8080)]
2021-12-13 20:02:07 ERROR (MainThread) [custom_components.sonoff.sonoff_cloud] Login error: None
2021-12-13 20:02:07 WARNING (MainThread) [custom_components.sonoff] Can't connect to eWeLink Cloud

**Comment by stu1811** [comment]
I have the same issue. I can't ping eu-api.coolkit.cc. I can ping cn-api.coolkit.cc. How do you set your region? I tried `api_region`

**Comment by stu1811** [comment]
@DJ-L1GhTeR if you change line 104 in custom_components/sonoff/sonoff_cloud.py from ` _baseurl = 'https://eu-api.coolkit.cc:8080/` to ` _baseurl = 'https://us-api.coolkit.cc:8080/` it connects.

**Comment by AlexxIT** [comment]
Check new beta-version:
https://github.com/AlexxIT/SonoffLAN/releases

It using new ewelink cloud API

**Comment by sm0ke21** [comment]
Having the same issue. Not working on v.3.3.1 and against master (as of 09/11/2022).

**Comment by AlexxIT** [comment]
@sm0ke21 you have not same issue. You already using new API.
