### ISSUE TITLE
Sonoff devices suddenly unavailable

### ISSUE THREAD

**Issue by Gabber2222** [AlexxIT/SonoffLAN#661]
Dear, since this morning with New update HA all my devices are unavailable. I restarted everything, but nothing works...

**Comment by AlexxIT** [comment]
Any details?

**Comment by Gabber2222** [comment]
I hope this will help.   
  
Thanks in advance!   
  
My regards   
  

  

  

  
  
  
  
  
>

**Comment by Gabber2222** [comment]
More info :
  

  
  
Deze fout is ontstaan door een aangepaste integratie.
  

  
Logger: custom_components.hacs
  
Source: custom_components/hacs/helpers/functions/get_list_from_default.py:35
  
Integration: HACS (documentation, issues)
  
First occurred: 21:12:03 (2 occurrences)
  
Last logged: 21:12:03
  

  
Timeout of 20 reached while waiting for https://api.github.com/repos/hacs/default/contents/theme
  
Timeout of 20 reached while waiting for https://api.github.com/repos/hacs/default/contents/plugin
  
  

  
And   
  

  

  
  
Deze fout is ontstaan door een aangepaste integratie.
  

  
Logger: custom_components.sonoff.sonoff_cloud
  
Source: custom_components/sonoff/sonoff_cloud.py:149
  
Integration: Sonoff (documentation, issues)
  
First occurred: 21:11:30 (1 occurrences)
  
Last logged: 21:11:30
  

  
Coolkit API error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://eu-api.coolkit.cc:8080/api/user/login')
  
Traceback (most recent call last):
  
   File "/config/custom_components/sonoff/sonoff_cloud.py", line 149, in _api
  
       return await r.json()
  
   File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
  
       raise ContentTypeError(
  
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://eu-api.coolkit.cc:8080/api/user/login')
  
  

  

  
Thank you!   
  

  

  

  
  
  
  
>

**Comment by Pirol62** [comment]
Same here since this morning.
This is the log:
````
2021-12-29 15:34:41 ERROR (MainThread) [custom_components.sonoff.sonoff_cloud] Coolkit API error: [Errno 1] [RSA] RSA lib (_ssl.c:2633)
Traceback (most recent call last):
File "/config/custom_components/sonoff/sonoff_cloud.py", line 148, in _api
r = await coro
File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
await resp.start(conn)
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 890, in start
message, payload = await self._protocol.read() # type: ignore
File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 604, in read
await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 1] [RSA] RSA lib (_ssl.c:2633)
2021-12-29 15:34:41 ERROR (MainThread) [homeassistant.setup] Error during setup of component sonoff
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 254, in _async_setup_component
result = await task
File "/config/custom_components/sonoff/__init__.py", line 104, in async_setup
await registry.cloud_load_devices(cachefile)
File "/config/custom_components/sonoff/sonoff_main.py", line 122, in cloud_load_devices
newdevices = await self.cloud.load_devices()
File "/config/custom_components/sonoff/sonoff_cloud.py", line 313, in load_devices
if resp['error'] == 0:
TypeError: 'NoneType' object is not subscriptable
````

**Comment by DravenSA** [comment]
Most annoying, but hope this helps fix the problem

2021-12-30 12:58:12 ERROR (MainThread) [custom_components.sonoff.sonoff_cloud] Coolkit API error: Cannot connect to host eu-api.coolkit.cc:8080 ssl:default [Connect call failed ('52.57.118.192', 8080)]
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore[return-value] # noqa
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
return await fut
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('52.57.118.192', 8080)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/sonoff/sonoff_cloud.py", line 148, in _api
r = await coro
File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
conn = await self._connector.connect(
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
proto = await self._create_connection(req, traces, timeout)
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
_, proto = await self._create_direct_connection(req, traces, timeout)
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
raise last_exc
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
transp, proto = await self._wrap_create_connection(
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host eu-api.coolkit.cc:8080 ssl:default [Connect call failed ('52.57.118.192', 8080)]
2021-12-30 12:58:12 ERROR (MainThread) [custom_components.sonoff.sonoff_cloud] Login error: None

**Comment by Pirol62** [comment]
After a restart today, sonoff is available again. At least here everythings fine.

**Comment by Gabber2222** [comment]
Removed sonoff lan on hacs, reinstalled it, restarted hassio, still nothing... Feeling Sad...

**Comment by TTLucian** [comment]
Same here. This just happened today:
```
This error originated from a custom integration.

Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:148
Integration: Sonoff (documentation, issues)
First occurred: 16:26:37 (1 occurrences)
Last logged: 16:26:37

Coolkit API error: Cannot connect to host eu-api.coolkit.cc:8080 ssl:default [Connect call failed ('52.57.118.192', 8080)]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('52.57.118.192', 8080)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 148, in _api
    r = await coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host eu-api.coolkit.cc:8080 ssl:default [Connect call failed ('52.57.118.192', 8080)]
```
```
This error originated from a custom integration.

Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:289
Integration: Sonoff (documentation, issues)
First occurred: 16:26:37 (1 occurrences)
Last logged: 16:26:37

Login error: None
```

**Comment by AlexxIT** [comment]
Check new beta-version:
https://github.com/AlexxIT/SonoffLAN/releases

It using new ewelink cloud API
