### ISSUE TITLE
EU servers down

### ISSUE THREAD

**Issue by Pirol62** [AlexxIT/SonoffLAN#678]
HA 2021.11.5
Component 2.4.6

Since two days, I receive these errors in log:
````
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:149
Integration: Sonoff (documentation, issues)
First occurred: 09:01:48 (1 occurrences)
Last logged: 09:01:48

Coolkit API error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://eu-api.coolkit.cc:8080/dispatch/app')
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 149, in _api
    return await r.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://eu-api.coolkit.cc:8080/dispatch/app')
````
and
````
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:228
Integration: Sonoff (documentation, issues)
First occurred: 09:35:15 (1 occurrences)
Last logged: 09:35:15

Cloud WS exception: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 228, in _connect
    resp = json.loads(msg.data)
  File "/usr/local/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
````

And sometimes i have a notification: 
````
Cloud mode cannot work simultaneously with two copies of component
````

I definately use only one HA instance and I have the latest android app version.
The switches are working normal.

**Comment by tlalos** [comment]
Me too i have a similar problem.
I have 2 accounts one for mobile ewelink and one for ha.
Everything was working fine but from yesterday i got warnings that account work simultaenously and the sonoff sensors not working anymore.

HA version:2021.12.9

**Comment by gilder0** [comment]
I have the same problems, this is due to cloud servers capacity problems. I wrote to support via eWelink and got a reply from them that they are working on solving the problem and restarting the servers.

**Comment by Cippo2019** [comment]
> I have the same problems, this is due to cloud servers capacity problems. I wrote to support via eWelink and got a reply from them that they are working on solving the problem and restarting the servers.

Yes... excatly...problem on servers in cloud :)   cross our fingers

**Comment by bramdan** [comment]
Same here.. last couple of days I’ve been getting weird warnings in the log about having 2 instances (I only have one) and devices were a bit finicky, and yesterday they started dying one by one.
I couldn’t even reset and pair some of them.

Weirdly enough they do work (mostly…) from the mobile app but the sonoff integration throws API errors when trying to initialize devices in boot, init passes and all devices are fetched but subsequent calls and commands  fail with malformed json errors.

Hope they sort it out soon, will be a PITA to replace 10 in wall devices😳

**Comment by flo071** [comment]
Well, maybe local only mode would fix this problem. If this persists longer today, I will try this option. Seems to be only a cloud side problem.

**Comment by Cippo2019** [comment]
I think that maybe it will disappear after work on ewlink cloud side..
just wait for now.

**Comment by aferraz** [comment]
Same for me.

**Comment by gilder0** [comment]
But maybe it would be possible to distinguish these kinds of error and at least not generate a problem notification while the lan mode is working ?

**Comment by Olimatou** [comment]
Same here :

Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:149
Integration: Sonoff (documentation, issues)
First occurred: 12:29:32 (2 occurrences)
Last logged: 12:29:32

Coolkit API error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://eu-api.coolkit.cc:8080/dispatch/app')
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 149, in _api
    return await r.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://eu-api.coolkit.cc:8080/dispatch/app')

**Comment by trippelb** [comment]
Same issue here,

Tried mode: local, however this would not solve avaliablity of temperature sensors on TH16 :/

**Comment by Psychoses** [comment]
it's ewelink side. a simple "html 502 bad gateway response" on https://eu-api.coolkit.cc:8080/dispatch/app

there is some post on "Sonoff / ITEAD Customer Care Center" forum too.
https://support.itead.cc/support/discussions/forums/1000228729

**Comment by tlalos** [comment]
Some sensors have started to work again. Maybe they are fixing now..

**Comment by Psychoses** [comment]
yeah, all are fixed seems few min. Now https://eu-api.coolkit.cc:8080/dispatch/app give us the expected json file.
Have a nice day guys.

**Comment by AlexxIT** [comment]
EU servers are broken. Pay no attention to notification.

**Comment by jon-daemon** [comment]
I was getting the same error:
```
Cloud mode cannot work simultaneously with two copies of component
```
and I decided to create a second account for ha (using the same with ewelink until now).
Now I get this error:
```
Cloud WS exception: 'online'
Traceback (most recent call last):
  File "/home/hass/.homeassistant/custom_components/sonoff/sonoff_cloud.py", line 237, in _connect
    await self._process_ws_msg(resp)
  File "/home/hass/.homeassistant/custom_components/sonoff/sonoff_cloud.py", line 173, in _process_ws_msg
    elif device['online'] is False:
KeyError: 'online'
```
Is this related with the EU servers issue?

My switches were blinking twice (no communication with server) until today. Now they are working fine with ewelink but they are not available as entities in HA.

**Comment by Pirol62** [comment]
I kept my account and did not create a second one. Everythings fine since they brought back their servers yesterday.
No more issues detected since almost one day.

**Comment by fuxing-at** [comment]
> EU servers are broken. Pay no attention to notification.

I mentioned, but obviously the server are back up.
So I tried again with the second account without success.
'
The existing entities are offline and no new one are beeing created.
The log says:
sonoff_cloud 0 devices loaded from the Cloud Server
INFO sonoff_local 10001b7091 <= Local1 | No devicekey for device
...
'

**Comment by Pirol62** [comment]
no more errors since the servers are back. I'm closing this.

**Comment by fuxing-at** [comment]
> no more errors since the servers are back. I'm closing this.

I'm still facing the same issue.
2022-01-18 14:43:06  DEBUG    main          SysInfo: {'version': '2021.12.9', 'dev': False, 'hassio': False, 'virtualenv': False, 'python_version': '3.9.7', 'docker': True, 'arch': 'x86_64', 'os_name': 'Linux', 'os_version': '5.4.x', 'user': 'root'}
2022-01-18 14:43:06  DEBUG    main          AUTO mode start
2022-01-18 14:43:10  DEBUG    sonoff_cloud  0 devices loaded from the Cloud Server
2022-01-18 14:43:10  INFO     sonoff_local  1000345b7b <= Local1 | No devicekey for device
2022-01-18 14:43:10  INFO     sonoff_local  10004d7c18 <= Local1 | No devicekey for device
2022-01-18 14:43:10  INFO     sonoff_local  10008c8ad3 <= Local1 | No devicekey for device
2022-01-18 14:43:10  INFO     sonoff_local  10007f0862 <= Local1 | No devicekey for device
2022-01-18 14:43:10  INFO     sonoff_local  10001b7091 <= Local1 | No devicekey for device
2022-01-18 14:43:10  INFO     sonoff_local  1000495095 <= Local1 | No devicekey for device
2022-01-18 14:43:10  INFO     sonoff_local  10004d7ca5 <= Local1 | No devicekey for device
2022-01-18 14:43:10  INFO     sonoff_local  1000342134 <= Local1 | No devicekey for device
2022-01-18 14:43:10  INFO     sonoff_local  10008c941d <= Local1 | No devicekey for device
2022-01-18 14:43:10  INFO     sonoff_local  1000343256 <= Local1 | No devicekey for device
2022-01-18 14:43:10  INFO     sonoff_local  10003471e8 <= Local1 | No devicekey for device
2022-01-18 14:43:10  INFO     sonoff_local  10007f0cf4 <= Local1 | No devicekey for device
2022-01-18 14:43:10  INFO     sonoff_local  1000362dcd <= Local1 | No devicekey for device
2022-01-18 14:43:10  INFO     sonoff_local  100021bece <= Local1 | No devicekey for device
2022-01-18 14:43:10  DEBUG    sonoff_cloud  Cloud init: {'error': 0, 'apikey': '...', 'config': {'hb': 1, 'hbInterval': 145}, 'sequence': '1642513390792'}
2022-01-18 14:43:21  INFO     sonoff_local  100048f42c <= Local1 | No devicekey for device

.sonoff.json:
{}

Is there anything I've done wrong?
Or any Idea how I can switch to a different account?

**Comment by AlexxIT** [comment]
@fuxing-at Maybe the cloud responded with an empty list because of a bug. Try restarting HA

**Comment by fuxing-at** [comment]
I changed the credentials in configuration, than deleted the ".sonoff.json" and than restarted HA.
When using the credentials of my main account, everything works fine...
