### ISSUE TITLE
Integration 'sonoff' not found.

### ISSUE THREAD

**Issue by SomebodySysop** [AlexxIT/SonoffLAN#682]
Just downloaded SonoffLAN, attempting to integrate with HA core-2021.12.9.  Installed as container using Docker.  First question: Does this project work with HA installed as container (from: https://lindevs.com/install-home-assistant-in-docker-on-ubuntu )?

If so, 

My config directory is /etc/homeassistant

Installed under above directory:  custom_components/sonoff

With this inserted into configuration.yaml:

```
sonoff:
  username: my ewelink app email
  password:  my ewelink app password
  mode: local
  reload: always

```
What am I missing?

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/homeassistant/__init__.py:170
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:57:48 AM (4 occurrences)
Last logged: 12:58:09 AM

[281473236117824] The system cannot restart because the configuration is not valid: Integration error: sonoff - Integration 'sonoff' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 733, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 170, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Integration error: sonoff - Integration 'sonoff' not found.
```

**Comment by Matioz** [comment]
@SomebodySysop  have you restarted homeassistant between putting sonoff to custom_components and adding sonoff entry to config?

**Comment by SomebodySysop** [comment]
> @SomebodySysop have you restarted homeassistant between putting sonoff to custom_components and adding sonoff entry to config?

I switched reels and installed HA OS instead.  It picked up all my sonoff devices automatically.  Thanks for the response!

**Comment by AlexxIT** [comment]
@SomebodySysop it's better to use HACS for installing custom components

**Comment by AlexxIT** [comment]
Please reopen issue if problem still actual
