### ISSUE TITLE
All my devices are offline after update

### ISSUE THREAD

**Issue by Marmoulak** [AlexxIT/SonoffLAN#765]
Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/core/ewelink/__init__.py:127
Integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: 1:51:07 PM (150 occurrences)
Last logged: 1:56:55 PM
Cloud WS exception

Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 252, in _connect
    await self._process_ws_msg(resp)
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 292, in _process_ws_msg
    self.dispatcher_send(SIGNAL_UPDATE, data)
  File "/config/custom_components/sonoff/core/ewelink/base.py", line 25, in dispatcher_send
    handler(*args, **kwargs)
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 127, in cloud_update
    elif device["online"] is False:
KeyError: 'online'

AND

Logger: homeassistant.components.automation.call_service_sonoff_update_consumption
Source: components/automation/__init__.py:519
Integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 1:51:08 PM (1 occurrences)
Last logged: 1:51:08 PM
Error while executing automation automation.call_service_sonoff_update_consumption: Unable to find service sonoff.update_consumption

**Comment by AlexxIT** [comment]
Consumption service deprecated.

**Comment by AlexxIT** [comment]
Do you have `sonoff > devices` section in YAML file?

**Comment by Marmoulak** [comment]
not for devices only RFbridge, the rest comes automatically. 

username: !secret EwelinkEmail
password: !secret EwelinkPWS
debug: false
force_update: [temperature, power]
scan_interval: "00:05:00" # (optional) default 5 minutes
sensors: [temperature, humidity, power, current, voltage, dw1, dw2, consumption]
rfbridge:
  MDLivingroom: # sensor name in eWeLink application
    device_class: motion
    timeout: 60 # optional (default 120), timeout in seconds for auto turn off
  MDLivingroom2: # sensor name in eWeLink application
    device_class: motion
    timeout: 60 # optional (default 120), timeout in seconds for auto turn off
  MDAltan: # sensor name in eWeLink application
    device_class: motion
    timeout: 60 # optional (default 120), timeout in seconds for auto turn off
.
.
.

**Comment by Marmoulak** [comment]
I have rolled back to previous version and works again.

**Comment by Apeiv** [comment]
I had the same bug and i'm rolling back to last stable.

**Comment by AlexxIT** [comment]
Maybe you both have DIY enabled devices? That still present in ewelink app.
Or you have some local devices don't connected to your Hass ewelink account?

**Comment by Apeiv** [comment]
No I have only device that work from HA and the admin account that I use is only used in home assistant

**Comment by AlexxIT** [comment]
I can fix a bug very quickly. I just don't understand how to make the same situation happen

**Comment by petr1885a** [comment]
I have the same problem only with the difference that everything works in versions 2.x, but I get an import error.
There is no import error in version 3.x, but **some** devices are offline but I can see them online in the ewelink application. The ewelink manager account is only used for HA and I use other shared accounts for the ewelink application

![scr01](https://user-images.githubusercontent.com/91090189/165147840-4de68524-fba5-41d4-9ff6-2dd234493f14.jpg)

![scr02](https://user-images.githubusercontent.com/91090189/165147681-fc0417c0-9b07-401d-a427-c86499db32bf.jpg)
.

**Comment by AlexxIT** [comment]
You showing error from 2nd version Integration. It can't connect to old ewelink API. New version using new ewelink API

**Comment by Apeiv** [comment]
ok, I found the error, in ewelink I had set 2 "houses" the integration "imports" only the first one and not the second one.

**Comment by Apeiv** [comment]
@AlexxIT thanks for your work, now i had delete second home.

**Comment by AlexxIT** [comment]
@Apeiv I will try to support multiple homes :)

**Comment by AlexxIT** [comment]
Multiple homes support added to latest beta:
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.0rc4

**Comment by Marmoulak** [comment]
> @Marmoulak are you also using multiple Homes in ewelink app?
> 
> @Apeiv Integration import not "first one". It imports "active" one. The last open Home in ewelink app.
I have only one Home.

**Comment by Marmoulak** [comment]
I just update to v3.0rc4 and everything works. Thanks, nice work.
