### ISSUE TITLE
Sonoff B05-B turning off issue

### ISSUE THREAD

**Issue by buni** [AlexxIT/SonoffLAN#773]
Hello, I've recently bough a couple of the above mentioned light bulbs, but I've run into a bit of an issue.
Essentially turning them off (turning them on works) via HA doesn't work, I tried to dig into the logs but they don't make a whole lot of sense to me.  
Happy to help with debugging/solving the problem, and also apologies if it is a known issue.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/entity.py:1013
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 11:49:54 PM (4 occurrences)
Last logged: 11:53:52 PM

    [3869989736]
    [3826296816]

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 513, in async_handle_light_off_service
    await light.async_turn_off(**filter_turn_off_params(light, params))
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1017, in async_turn_off
    await self.hass.async_add_executor_job(ft.partial(self.turn_off, **kwargs))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in turn_off
    raise NotImplementedError()
NotImplementedError
```
![image](https://user-images.githubusercontent.com/4800712/165391443-21e7671d-564d-411d-8c96-8dda466153e7.png)

**Comment by fabiobrolo** [comment]
I´m having the same issue using v3.0rc4.

**Comment by AlexxIT** [comment]
Fixed in latest master-version
