### ISSUE TITLE
After upgrade to 3.0.1, the eWelink KING-Q4 KingArt Windows Curtain devices can not be used. 

### ISSUE THREAD

**Issue by ilkanaev** [AlexxIT/SonoffLAN#791]
Hello,
After upgrade to 3.0.1, the eWelink KING-Q4 KingArt Windows Curtain devices can not be used. 
As far as i know, these supports the cloud mode only.
i have 4 devices and all of them shown as disconnected/not available.

Thanks,
Yossi

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#debug-page

**Comment by ilkanaev** [comment]
Hello Alex,
Please find following the requested information.

Thank you in advance,
Yossi

**1 - Info page**
#####################################################################################
## System Health

version | core-2022.4.7
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103-v7l+
arch | armv7l
timezone | Asia/Jerusalem

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4872
Installed Version | 1.24.5
Stage | running
Available Repositories | 1027
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Raspbian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.14
disk_total | 117.1 GB
disk_used | 8.8 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Terminal & SSH (9.3.0), ESPHome (2022.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 6
mode | storage

</details>

<details><summary>Sonoff</summary>

version | 3.0.1
-- | --
cloud_online | 14 / 17
local_online | 10 / 10
debug | failed to load: 

</details>

**2 - System Log**
#####################################################################################
2022-05-02 07:56:35 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration xiaomi_gateway3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-02 07:56:35 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-02 07:56:35 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-02 07:56:35 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-02 07:56:45 ERROR (MainThread) [homeassistant.components.webostv] The 'webostv' option near /config/configuration.yaml:2 has been removed, please remove it from your configuration
2022-05-02 07:56:49 WARNING (MainThread) [homeassistant.config_entries] Config entry 'HP DeskJet 3700 series [F195C1]' for ipp integration not ready yet: Invalid response from API: Error occurred while communicating with IPP server.; Retrying in background
2022-05-02 07:56:52 ERROR (MainThread) [custom_components.sonoff.core.entity] Can't init device: {'name': 'Karin Curtain Ritgh', 'deviceid': '1001486960', 'apikey': 'b37f61cf-3628-4bd8-89d4-a3ef5728774b', 'extra': {'uiid': 11, 'description': '20210827005', 'brandId': '59ba53ad86b3ab5e3ae68596', 'apmac': 'd0:27:02:90:d0:11', 'mac': 'd0:27:02:90:d0:10', 'ui': '电动窗帘', 'modelInfo': '5b83d2114a6b22f51544b4d5', 'model': 'PSF-BTA-GL', 'manufacturer': '深圳市彪王科技有限公司', 'chipid': '00492B2F', 'staMac': 'E8:DB:84:49:2B:2F'}, 'brandName': 'KingArt', 'brandLogo': 'https://as-ota.coolkit.cc/logo/w9sMg5WxAWp0o9OBeqyH0rcOJKEVKaKi.png', 'showBrand': True, 'productModel': 'KING-Q4', 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '6011c2cca4a1540007c388f0', 'index': -16, 'members': []}, 'shareTo': [], 'devicekey': 'ff01742e-8ce5-4ea3-9773-3935cb3b57c9', 'online': True, 'params': {'bindInfos': {}, 'version': 8, 'only_device': {'ota': 'success'}, 'switch': 'on', 'setclose': 0, 'sledOnline': 'on', 'ssid': 'Just an Idiot', 'bssid': 'b0:bb:e5:70:4a:14', 'rssi': -81, 'fwVersion': '3.4.2', 'staMac': 'E8:DB:84:49:2B:2F'}, 'isSupportGroup': False, 'isSupportedOnMP': True, 'deviceFeature': {}}
Traceback (most recent call last):
File "/config/custom_components/sonoff/core/entity.py", line 82, in __init__
self.internal_update(params)
File "/config/custom_components/sonoff/core/entity.py", line 100, in internal_update
self.set_state(params)
File "/config/custom_components/sonoff/cover.py", line 44, in set_state
self._attr_is_closing = pos < self._attr_current_cover_position
TypeError: '<' not supported between instances of 'int' and 'NoneType'
2022-05-02 07:56:52 ERROR (MainThread) [custom_components.sonoff.core.entity] Can't init device: {'name': 'Karin Curtain Left', 'deviceid': '1001486ac0', 'apikey': 'b37f61cf-3628-4bd8-89d4-a3ef5728774b', 'extra': {'uiid': 11, 'description': '20210827005', 'brandId': '59ba53ad86b3ab5e3ae68596', 'apmac': 'd0:27:02:90:d2:d1', 'mac': 'd0:27:02:90:d2:d0', 'ui': '电动窗帘', 'modelInfo': '5b83d2114a6b22f51544b4d5', 'model': 'PSF-BTA-GL', 'manufacturer': '深圳市彪王科技有限公司', 'chipid': '00492238', 'staMac': 'E8:DB:84:49:22:38'}, 'brandName': 'KingArt', 'brandLogo': 'https://as-ota.coolkit.cc/logo/w9sMg5WxAWp0o9OBeqyH0rcOJKEVKaKi.png', 'showBrand': True, 'productModel': 'KING-Q4', 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '6011c2cca4a1540007c388f0', 'index': -15, 'members': []}, 'shareTo': [], 'devicekey': '698b47e3-720d-47e3-a30c-4efdb6049aac', 'online': True, 'params': {'bindInfos': {}, 'version': 8, 'only_device': {'ota': 'success'}, 'switch': 'on', 'setclose': 0, 'sledOnline': 'on', 'ssid': 'Just an Idiot', 'bssid': 'b0:bb:e5:70:4a:14', 'rssi': -85, 'fwVersion': '3.4.2', 'staMac': 'E8:DB:84:49:22:38'}, 'isSupportGroup': False, 'isSupportedOnMP': True, 'deviceFeature': {}}
Traceback (most recent call last):
File "/config/custom_components/sonoff/core/entity.py", line 82, in __init__
self.internal_update(params)
File "/config/custom_components/sonoff/core/entity.py", line 100, in internal_update
self.set_state(params)
File "/config/custom_components/sonoff/cover.py", line 44, in set_state
self._attr_is_closing = pos < self._attr_current_cover_position
TypeError: '<' not supported between instances of 'int' and 'NoneType'
2022-05-02 07:56:52 ERROR (MainThread) [custom_components.sonoff.core.entity] Can't init device: {'name': 'Спальня шторы правая', 'deviceid': '100100613e', 'apikey': 'b37f61cf-3628-4bd8-89d4-a3ef5728774b', 'extra': {'uiid': 11, 'description': '20201012001', 'brandId': '59ba53ad86b3ab5e3ae68596', 'apmac': 'd0:27:02:00:bf:cd', 'mac': 'd0:27:02:00:bf:cc', 'ui': '电动窗帘', 'modelInfo': '5b83d2114a6b22f51544b4d5', 'model': 'PSF-BTA-GL', 'manufacturer': '深圳市彪王科技有限公司', 'chipid': '000ED5A0', 'staMac': '24:A1:60:0E:D5:A0'}, 'brandName': 'KingArt', 'brandLogo': 'https://as-ota.coolkit.cc/logo/w9sMg5WxAWp0o9OBeqyH0rcOJKEVKaKi.png', 'showBrand': True, 'productModel': 'KING-Q4', 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '6011c2cca4a1540007c388f0', 'index': -2, 'roomid': '6011c2cca4a1540007c388ee'}, 'shareTo': [], 'devicekey': '19d04d75-d5c7-4d6c-9b77-84ec3d9eb5e1', 'online': True, 'params': {'version': 8, 'only_device': {'ota': 'success'}, 'switch': 'on', 'setclose': 0, 'sledOnline': 'on', 'ssid': 'Just an Idiot', 'bssid': '20:b0:01:36:30:d9', 'rssi': -55, 'fwVersion': '3.4.2', 'staMac': '24:A1:60:0E:D5:A0'}, 'isSupportGroup': False, 'isSupportedOnMP': True, 'deviceFeature': {}}
Traceback (most recent call last):
File "/config/custom_components/sonoff/core/entity.py", line 82, in __init__
self.internal_update(params)
File "/config/custom_components/sonoff/core/entity.py", line 100, in internal_update
self.set_state(params)
File "/config/custom_components/sonoff/cover.py", line 44, in set_state
self._attr_is_closing = pos < self._attr_current_cover_position
TypeError: '<' not supported between instances of 'int' and 'NoneType'
2022-05-02 07:56:52 ERROR (MainThread) [custom_components.sonoff.core.entity] Can't init device: {'name': 'Спальня шторы левая', 'deviceid': '10010064fc', 'apikey': 'b37f61cf-3628-4bd8-89d4-a3ef5728774b', 'extra': {'uiid': 11, 'description': '20201012001', 'brandId': '59ba53ad86b3ab5e3ae68596', 'apmac': 'd0:27:02:00:c7:49', 'mac': 'd0:27:02:00:c7:48', 'ui': '电动窗帘', 'modelInfo': '5b83d2114a6b22f51544b4d5', 'model': 'PSF-BTA-GL', 'manufacturer': '深圳市彪王科技有限公司', 'chipid': '000E0419', 'staMac': '24:A1:60:0E:04:19'}, 'brandName': 'KingArt', 'brandLogo': 'https://as-ota.coolkit.cc/logo/w9sMg5WxAWp0o9OBeqyH0rcOJKEVKaKi.png', 'showBrand': True, 'productModel': 'KING-Q4', 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '6011c2cca4a1540007c388f0', 'index': -1, 'roomid': '6011c2cca4a1540007c388ee'}, 'shareTo': [], 'devicekey': '98778081-b177-412f-bf06-479257ce37d0', 'online': True, 'params': {'version': 8, 'only_device': {'ota': 'success'}, 'switch': 'on', 'setclose': 0, 'sledOnline': 'on', 'ssid': 'Just an Idiot', 'bssid': '20:b0:01:36:30:d9', 'rssi': -67, 'fwVersion': '3.4.2', 'staMac': '24:A1:60:0E:04:19'}, 'isSupportGroup': False, 'isSupportedOnMP': True, 'deviceFeature': {}}
Traceback (most recent call last):
File "/config/custom_components/sonoff/core/entity.py", line 82, in __init__
self.internal_update(params)
File "/config/custom_components/sonoff/core/entity.py", line 100, in internal_update
self.set_state(params)
File "/config/custom_components/sonoff/cover.py", line 44, in set_state
self._attr_is_closing = pos < self._attr_current_cover_position
TypeError: '<' not supported between instances of 'int' and 'NoneType'


**3 - Sonoff Debug information**
#####################################################################################
2022-05-02 07:56:46 [D] SysInfo: {'installation_type': 'Home Assistant Supervised', 'version': '2022.4.7', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.9.9', 'docker': True, 'arch': 'armv7l', 'timezone': 'Asia/Jerusalem', 'os_name': 'Linux', 'os_version': '5.10.103-v7l+', 'user': 'root', 'supervisor': '2022.04.0', 'host_os': 'Raspbian GNU/Linux 10 (buster)', 'docker_version': '20.10.14', 'chassis': '', 'sonoff_version': '3.0.1'}
2022-05-02 07:56:52 [D] 17 devices loaded from Cloud
2022-05-02 07:56:52 [D] 1001486960 UIID 0011 | {'version': 8, 'only_device': {'ota': 'success'}, 'switch': 'on', 'setclose': 0, 'sledOnline': 'on', 'rssi': -81, 'fwVersion': '3.4.2'}
2022-05-02 07:56:52 [E] Can't init device: {'name': 'Karin Curtain Ritgh', 'deviceid': '1001486960', 'apikey': 'b37f61cf-3628-4bd8-89d4-a3ef5728774b', 'extra': {'uiid': 11, 'description': '20210827005', 'brandId': '59ba53ad86b3ab5e3ae68596', 'apmac': 'd0:27:02:90:d0:11', 'mac': 'd0:27:02:90:d0:10', 'ui': '电动窗帘', 'modelInfo': '5b83d2114a6b22f51544b4d5', 'model': 'PSF-BTA-GL', 'manufacturer': '深圳市彪王科技有限公司', 'chipid': '00492B2F', 'staMac': 'E8:DB:84:49:2B:2F'}, 'brandName': 'KingArt', 'brandLogo': 'https://as-ota.coolkit.cc/logo/w9sMg5WxAWp0o9OBeqyH0rcOJKEVKaKi.png', 'showBrand': True, 'productModel': 'KING-Q4', 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '6011c2cca4a1540007c388f0', 'index': -16, 'members': []}, 'shareTo': [], 'devicekey': 'ff01742e-8ce5-4ea3-9773-3935cb3b57c9', 'online': True, 'params': {'bindInfos': {}, 'version': 8, 'only_device': {'ota': 'success'}, 'switch': 'on', 'setclose': 0, 'sledOnline': 'on', 'ssid': 'Just an Idiot', 'bssid': 'b0:bb:e5:70:4a:14', 'rssi': -81, 'fwVersion': '3.4.2', 'staMac': 'E8:DB:84:49:2B:2F'}, 'isSupportGroup': False, 'isSupportedOnMP': True, 'deviceFeature': {}}|  File "/config/custom_components/sonoff/core/entity.py", line 82, in __init__|    self.internal_update(params)|TypeError: '<' not supported between instances of 'int' and 'NoneType'|
2022-05-02 07:56:52 [D] 1001486ac0 UIID 0011 | {'version': 8, 'only_device': {'ota': 'success'}, 'switch': 'on', 'setclose': 0, 'sledOnline': 'on', 'rssi': -85, 'fwVersion': '3.4.2'}
2022-05-02 07:56:52 [E] Can't init device: {'name': 'Karin Curtain Left', 'deviceid': '1001486ac0', 'apikey': 'b37f61cf-3628-4bd8-89d4-a3ef5728774b', 'extra': {'uiid': 11, 'description': '20210827005', 'brandId': '59ba53ad86b3ab5e3ae68596', 'apmac': 'd0:27:02:90:d2:d1', 'mac': 'd0:27:02:90:d2:d0', 'ui': '电动窗帘', 'modelInfo': '5b83d2114a6b22f51544b4d5', 'model': 'PSF-BTA-GL', 'manufacturer': '深圳市彪王科技有限公司', 'chipid': '00492238', 'staMac': 'E8:DB:84:49:22:38'}, 'brandName': 'KingArt', 'brandLogo': 'https://as-ota.coolkit.cc/logo/w9sMg5WxAWp0o9OBeqyH0rcOJKEVKaKi.png', 'showBrand': True, 'productModel': 'KING-Q4', 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '6011c2cca4a1540007c388f0', 'index': -15, 'members': []}, 'shareTo': [], 'devicekey': '698b47e3-720d-47e3-a30c-4efdb6049aac', 'online': True, 'params': {'bindInfos': {}, 'version': 8, 'only_device': {'ota': 'success'}, 'switch': 'on', 'setclose': 0, 'sledOnline': 'on', 'ssid': 'Just an Idiot', 'bssid': 'b0:bb:e5:70:4a:14', 'rssi': -85, 'fwVersion': '3.4.2', 'staMac': 'E8:DB:84:49:22:38'}, 'isSupportGroup': False, 'isSupportedOnMP': True, 'deviceFeature': {}}|  File "/config/custom_components/sonoff/core/entity.py", line 82, in __init__|    self.internal_update(params)|TypeError: '<' not supported between instances of 'int' and 'NoneType'|
2022-05-02 07:56:52 [D] 100117f907 UIID 0001 | {'version': 8, 'sledOnline': 'on', 'switch': 'on', 'fwVersion': '3.6.0', 'rssi': -83, 'startup': 'off', 'init': 1, 'pulse': 'off', 'pulseWidth': 500, 'swMode': 2, 'swCtrlReverse': 'off'}
2022-05-02 07:56:52 [D] 1001183218 UIID 0001 | {'version': 8, 'sledOnline': 'on', 'switch': 'off', 'fwVersion': '3.6.0', 'rssi': -84, 'startup': 'off', 'init': 1, 'pulse': 'off', 'pulseWidth': 500, 'swMode': 2, 'swCtrlReverse': 'off'}
2022-05-02 07:56:52 [D] 10010f3009 UIID 0001 | {'version': 8, 'sledOnline': 'on', 'switch': 'on', 'fwVersion': '3.6.0', 'rssi': -82, 'startup': 'off', 'init': 1, 'pulse': 'off', 'pulseWidth': 500, 'swMode': 2, 'swCtrlReverse': 'off'}
2022-05-02 07:56:52 [D] 10010ebdd0 UIID 0001 | {'version': 8, 'sledOnline': 'on', 'switch': 'off', 'fwVersion': '3.6.0', 'rssi': -82, 'startup': 'off', 'init': 1, 'pulse': 'off', 'pulseWidth': 500, 'swMode': 2, 'swCtrlReverse': 'off'}
2022-05-02 07:56:52 [D] 1001027d64 UIID 0006 | {'version': 8, 'only_device': {'ota': 'success'}, 'sledOnline': 'on', 'switch': 'off', 'fwVersion': '3.5.1', 'rssi': -79, 'startup': 'off', 'init': 1, 'pulse': 'off', 'pulseWidth': 500}
2022-05-02 07:56:52 [D] 10010279c1 UIID 0006 | {'version': 8, 'only_device': {'ota': 'success'}, 'sledOnline': 'on', 'switch': 'off', 'fwVersion': '3.5.1', 'rssi': -53, 'startup': 'off', 'init': 1, 'pulse': 'off', 'pulseWidth': 500}
2022-05-02 07:56:52 [D] 1000bf17f8 UIID 0008 | {'version': 8, 'sledOnline': 'on', 'fwVersion': '3.5.1', 'rssi': -69, 'init': 1, 'lock': 0, 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'only_device': {'ota': 'success'}}
2022-05-02 07:56:52 [D] 10010279bd UIID 0006 | {'version': 8, 'only_device': {'ota': 'success'}, 'sledOnline': 'on', 'switch': 'off', 'fwVersion': '3.5.1', 'rssi': -67, 'startup': 'off', 'init': 1, 'pulse': 'off', 'pulseWidth': 500}
2022-05-02 07:56:52 [D] 100102741c UIID 0006 | {'version': 8, 'only_device': {'ota': 'success'}, 'sledOnline': 'on', 'switch': 'off', 'fwVersion': '3.5.1', 'rssi': -74, 'startup': 'off', 'init': 1, 'pulse': 'off', 'pulseWidth': 500}
2022-05-02 07:56:52 [D] 1000bf1529 UIID 0008 | {'version': 8, 'sledOnline': 'on', 'fwVersion': '3.4.1', 'rssi': -64, 'init': 1, 'lock': 0, 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}]}
2022-05-02 07:56:52 [D] 10010f7e87 UIID 0001 | {'version': 8, 'sledOnline': 'on', 'switch': 'off', 'fwVersion': '3.6.0', 'rssi': -77, 'startup': 'off', 'init': 1, 'pulse': 'off', 'pulseWidth': 500, 'swMode': 2, 'swCtrlReverse': 'off'}
2022-05-02 07:56:52 [D] 1000bf283b UIID 0008 | {'version': 8, 'sledOnline': 'on', 'fwVersion': '3.4.1', 'rssi': -74, 'init': 1, 'lock': 0, 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}]}
2022-05-02 07:56:52 [D] 100100613e UIID 0011 | {'version': 8, 'only_device': {'ota': 'success'}, 'switch': 'on', 'setclose': 0, 'sledOnline': 'on', 'rssi': -55, 'fwVersion': '3.4.2'}
2022-05-02 07:56:52 [E] Can't init device: {'name': 'Спальня шторы правая', 'deviceid': '100100613e', 'apikey': 'b37f61cf-3628-4bd8-89d4-a3ef5728774b', 'extra': {'uiid': 11, 'description': '20201012001', 'brandId': '59ba53ad86b3ab5e3ae68596', 'apmac': 'd0:27:02:00:bf:cd', 'mac': 'd0:27:02:00:bf:cc', 'ui': '电动窗帘', 'modelInfo': '5b83d2114a6b22f51544b4d5', 'model': 'PSF-BTA-GL', 'manufacturer': '深圳市彪王科技有限公司', 'chipid': '000ED5A0', 'staMac': '24:A1:60:0E:D5:A0'}, 'brandName': 'KingArt', 'brandLogo': 'https://as-ota.coolkit.cc/logo/w9sMg5WxAWp0o9OBeqyH0rcOJKEVKaKi.png', 'showBrand': True, 'productModel': 'KING-Q4', 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '6011c2cca4a1540007c388f0', 'index': -2, 'roomid': '6011c2cca4a1540007c388ee'}, 'shareTo': [], 'devicekey': '19d04d75-d5c7-4d6c-9b77-84ec3d9eb5e1', 'online': True, 'params': {'version': 8, 'only_device': {'ota': 'success'}, 'switch': 'on', 'setclose': 0, 'sledOnline': 'on', 'ssid': 'Just an Idiot', 'bssid': '20:b0:01:36:30:d9', 'rssi': -55, 'fwVersion': '3.4.2', 'staMac': '24:A1:60:0E:D5:A0'}, 'isSupportGroup': False, 'isSupportedOnMP': True, 'deviceFeature': {}}|  File "/config/custom_components/sonoff/core/entity.py", line 82, in __init__|    self.internal_update(params)|TypeError: '<' not supported between instances of 'int' and 'NoneType'|
2022-05-02 07:56:52 [D] 10010064fc UIID 0011 | {'version': 8, 'only_device': {'ota': 'success'}, 'switch': 'on', 'setclose': 0, 'sledOnline': 'on', 'rssi': -67, 'fwVersion': '3.4.2'}
2022-05-02 07:56:52 [E] Can't init device: {'name': 'Спальня шторы левая', 'deviceid': '10010064fc', 'apikey': 'b37f61cf-3628-4bd8-89d4-a3ef5728774b', 'extra': {'uiid': 11, 'description': '20201012001', 'brandId': '59ba53ad86b3ab5e3ae68596', 'apmac': 'd0:27:02:00:c7:49', 'mac': 'd0:27:02:00:c7:48', 'ui': '电动窗帘', 'modelInfo': '5b83d2114a6b22f51544b4d5', 'model': 'PSF-BTA-GL', 'manufacturer': '深圳市彪王科技有限公司', 'chipid': '000E0419', 'staMac': '24:A1:60:0E:04:19'}, 'brandName': 'KingArt', 'brandLogo': 'https://as-ota.coolkit.cc/logo/w9sMg5WxAWp0o9OBeqyH0rcOJKEVKaKi.png', 'showBrand': True, 'productModel': 'KING-Q4', 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '6011c2cca4a1540007c388f0', 'index': -1, 'roomid': '6011c2cca4a1540007c388ee'}, 'shareTo': [], 'devicekey': '98778081-b177-412f-bf06-479257ce37d0', 'online': True, 'params': {'version': 8, 'only_device': {'ota': 'success'}, 'switch': 'on', 'setclose': 0, 'sledOnline': 'on', 'ssid': 'Just an Idiot', 'bssid': '20:b0:01:36:30:d9', 'rssi': -67, 'fwVersion': '3.4.2', 'staMac': '24:A1:60:0E:04:19'}, 'isSupportGroup': False, 'isSupportedOnMP': True, 'deviceFeature': {}}|  File "/config/custom_components/sonoff/core/entity.py", line 82, in __init__|    self.internal_update(params)|TypeError: '<' not supported between instances of 'int' and 'NoneType'|
2022-05-02 07:56:52 [D] 1000cdf589 UIID 0015 | {'version': 8, 'sledOnline': 'on', 'init': 1, 'switch': 'off', 'fwVersion': '3.5.0', 'rssi': -93, 'startup': 'off', 'pulse': 'off', 'pulseWidth': 500, 'sensorType': 'AM2301', 'currentHumidity': '74', 'currentTemperature': '20.2', 'mainSwitch': 'off', 'deviceType': 'normal', 'only_device': {'ota': 'success'}}
2022-05-02 07:56:52 [D] AUTO mode start
2022-05-02 07:56:53 [D] 1000bf17f8 <= Local3 | {'sledOnline': 'on', 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}]} | 161
2022-05-02 07:56:53 [D] 1001027d64 <= Local3 | {'switch': 'off', 'startup': 'off', 'pulse': 'off', 'sledOnline': 'on', 'pulseWidth': 500, 'rssi': -79} | 2342
2022-05-02 07:56:53 [D] 10010279bd <= Local3 | {'switch': 'off', 'startup': 'off', 'pulse': 'off', 'sledOnline': 'on', 'pulseWidth': 500, 'rssi': -67} | 5272
2022-05-02 07:56:53 [D] 100102741c <= Local3 | {'switch': 'off', 'startup': 'off', 'pulse': 'off', 'pulseWidth': 500, 'rssi': -74} | 447
2022-05-02 07:56:53 [D] 10010f3009 <= Local3 | {'switch': 'on', 'startup': 'off', 'pulse': 'off', 'sledOnline': 'on', 'fwVersion': '3.6.0', 'pulseWidth': 500, 'rssi': -82} | 12052
2022-05-02 07:56:53 [D] 100117f907 <= Local3 | {'switch': 'on', 'startup': 'off', 'pulse': 'off', 'sledOnline': 'on', 'fwVersion': '3.6.0', 'pulseWidth': 500, 'rssi': -83} | 4263
2022-05-02 07:56:53 [D] 10010ebdd0 <= Local3 | {'switch': 'off', 'startup': 'off', 'pulse': 'off', 'sledOnline': 'on', 'fwVersion': '3.6.0', 'pulseWidth': 500, 'rssi': -82} | 731
2022-05-02 07:56:53 [D] 10010279c1 <= Local3 | {'switch': 'off', 'startup': 'off', 'pulse': 'off', 'sledOnline': 'on', 'pulseWidth': 500, 'rssi': -53} | 3060
2022-05-02 07:56:53 [D] 1001183218 <= Local3 | {'switch': 'off', 'startup': 'off', 'pulse': 'off', 'pulseWidth': 500, 'rssi': -84} | 3206
2022-05-02 07:56:53 [D] 1000cdf589 <= Local3 | {'mainSwitch': 'off', 'deviceType': 'normal', 'switch': 'off', 'startup': 'off', 'pulse': 'off', 'pulseWidth': 500, 'sledOnline': 'on', 'sensorType': 'AM2301', 'currentHumidity': '74', 'currentTemperature': '20.0'} | 29770
2022-05-02 07:56:56 [D] CLOUD False => True

**Comment by AlexxIT** [comment]
Same as #792
Fixed in latest master-version
