### ISSUE TITLE
Basic and Basic2 switches ´unavailable´ after update to 3.0.2

### ISSUE THREAD

**Issue by roelof-47** [AlexxIT/SonoffLAN#809]
Before the update the sonoff switches acted well. Still they work well via the Ewelink app.
I restored the old version.

**Comment by AlexxIT** [comment]
Install latest master version and get integration diagnostics (Hass v2022.2 and more):

Configuration > Integrations > Sonoff > 3 dots > Download diagnostics

**Comment by roelof-47** [comment]
Your suggested path to ´download diagnostics´ does not show a menu with this choice. See attached.
Translations of the menu: Change name, System specs, Documentation, Known problems, Reload, Disable, Delete




![menu sonoff integration](https://user-images.githubusercontent.com/98609074/166466463-fb5df278-51f4-475e-8f59-f46e99fb9140.PNG)

**Comment by roelof-47** [comment]
I have Core 2022.4.7 installed.

**Comment by AlexxIT** [comment]
HACS > SonoffLAN > Reinstall > master

**Comment by roelof-47** [comment]
O.k., I did install ´master´ version and restart the HA system. I checked again the path your earlier mentioned to find `download diagnosis´.
But nothing has changed. The menu options (as above) remain unchanged. No ´download diagnosis´.

**Comment by roelof-47** [comment]
I can provide you with the error message from the logbook.
...
Logger: homeassistant
Source: custom_components/sonoff/core/ewelink/__init__.py:44
Integration: Sonoff (documentation, issues)
First occurred: 18:21:55 (1 occurrences)
Last logged: 18:21:55
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/sonoff/__init__.py", line 201, in internal_normal_setup
    await internal_cache_setup(hass, entry, devices)
  File "/config/custom_components/sonoff/__init__.py", line 222, in internal_cache_setup
    registry.setup_devices(devices)
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 44, in setup_devices
    _LOGGER.debug(f"{deviceid} UIID {uiid:04} | %s", device["params"])
KeyError: 'params'
...

**Comment by AlexxIT** [comment]
Can change this lines:
https://github.com/AlexxIT/SonoffLAN/blob/cbac13599243bff969dd16654df800be69ee4a48/custom_components/sonoff/core/ewelink/cloud.py#L161-L163
to:
```python
            resp = await r.json()
            _LOGGER.error(resp)
            if resp["error"] != 0:
                raise Exception(resp["msg"])
```
And send response in logs to sonofflan@gmail.com
You have some strange type of device. Maybe it's shared group. I don't know.

**Comment by roelof-47** [comment]
I did send you response in logs.

**Comment by AlexxIT** [comment]
Problem with "Ext Grond zijkant". I never saw device without some state info. Is it works fine?

**Comment by AlexxIT** [comment]
Should be fixed in latest master version. Will be in next release.
