### ISSUE TITLE
DualR3 state closing opening is not updated

### ISSUE THREAD

**Issue by rexopl** [AlexxIT/SonoffLAN#917]
Hi, since about month sonoff addon stopped updating DualR3 status.
Calling services open_cover and close_cover works fine, but status of device is not changing.
So no option to detect state and revert button (close/open) function.
It doesn't matter what last status was saved - it does not refresh at all.
While checking logs and trying find problem i discovered that - state is updated only once when i click reload on SonOff component in settings, than it is not updating again.

Is stopped working after some updates.
I have full official and up-to-date hassio and HACS plugins.
Tried restarting few times. No logs related to this problem found.

**Comment by 20bart** [comment]
Hi, I have the same problem. I think since version 3. In the ewelink app it's working fine though.
When I switch the mode (auto/cloud/local) it updates once but after that it doesn't sync anymore.

**Comment by rexopl** [comment]
I created temporary solution:
Created pyscript (requires pyscript installed via HACS):
```
@service
def set_state(entity_id, value: str):
    state.set(entity_id, value)

```

And added extra action for button in switches section config 😅:
```
      turn_on:
          - service: cover.open_cover
            target:
              entity_id: cover.sonoff_100127439b
          - service: pyscript.set_state
            data:
                entity_id: cover.sonoff_100127439b
                value: opening
```

**Comment by 20bart** [comment]
[Debug logs.txt](https://github.com/AlexxIT/SonoffLAN/files/9184298/Debug.logs.txt)
[System Health.txt](https://github.com/AlexxIT/SonoffLAN/files/9184299/System.Health.txt)
[sonoff-138930c8454f4a2a5a40a24d8c8e293e-Rolluik-f2357000b9b967b5b55814298a1405ea.json.txt](https://github.com/AlexxIT/SonoffLAN/files/9184300/sonoff-138930c8454f4a2a5a40a24d8c8e293e-Rolluik-f2357000b9b967b5b55814298a1405ea.json.txt)
Hope it helps. If you need anything else, let me know.

**Comment by rexopl** [comment]
If you would like to switch to cover mode, you need to set in ewelink mode to motor.
It assures that only one output is available.
Personally I use it for 2 speed fans (rooms air condition/ventilation).
In this case both outputs enabled might burn out motor - so it is super useful :).

**Comment by 20bart** [comment]
Yes, I have it set to motor mode in ewelink app. Maybe important that I mentioned this aswel.

**Comment by BenoitRullez** [comment]
Hello all. I have the same problem, but please allow me to rephrase it with my own words and understanding.

DualR3 has 3 modes: switch / motor / energy metering.  I use mine in motor mode to manage an awning. (I guess that what everybody here is calling the cover mode is the motor mode on the Sonoff documentation).
The problem is that the position of the awning (a percentage, ranging from 0% = full in = fully retracted, to 100% = full out = fully extended) is not update in HA. The position is something calculated by the DualR3 after a bit of self-learning.
The position is continuously updated in eWelink but not at all in HA. The position command from HA ("open 40%") works well.

Actually I think the first problem is that in HA, the position is a secondary information of the device, and not one of the sensors of the device. 
The sensors i see in HA for the DualR3 are, for each of the 2 channels: voltage, power, ...
I haven't found yet how to call the position in the scripts, nor how to display it in the dashboard except as a secondary information of the device.

Would it be possible to have the position recognize as a sensor in HA when the DualR3 is in motor mode?

**Comment by BenoitRullez** [comment]
Mmm, very strange today, at the same time I added one new MINI to my sonoff integration, the DUALR3 that is managing my awning became unvailable.
It is still available and working correctly from eWelink.
In the logs I found this below.
Absolultly no idea if this is related to the issue of lack of awning position reporting. Probably not. 

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:102
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8 août 2022 à 13:00:54 (4 occurrences)
Last logged: 12:36:12

[3774634448] Error handling message: Unauthorized (unauthorized)
[4005302384] Error handling message: Unauthorized (unauthorized)
[3734876896] Error handling message: Unauthorized (unauthorized)
[3717429376] Error handling message: Unauthorized (unauthorized)

**Comment by BenoitRullez** [comment]
While we are on DUALR3 cover mode...

On the dashboard, the following code:
```
type: entities
entities:
  - entity: cover.sonoff_10014366de
    secondary_info: position
```
gives us 3 buttons: open, stop, and close. 
All the 3 buttons, including the stop button, give the exepected result with DUALR3 and cover.

However, in the automation editor, using the use interface, the only action available in the drop list for this device is to "set position".
In the YAML editor this action looks like that:
```
domain: cover
entity_id: cover.sonoff_10014366de
type: set_position
position: 0
```
Would it be possible to arrange the drop list to also propose Open, Stop, and Close action, on top of the Set_position action?
Maybe open and close are not the best words, extend and retract would be better for an awning, or up and down for a shutter.

Thanks a lot.

**Comment by sipimokus** [comment]
I think caught a potential bug in DualR3 in cover mode, maybe related for this issue:
https://github.com/AlexxIT/SonoffLAN/blob/7e3f82946d8360b93110f910033812869034cdc2/custom_components/sonoff/core/devices.py#L235
I tried copy this solution for NSPanel #919 fix, but I got this error message:
```
 Traceback (most recent call last):
   File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 51, in setup_devices
     entities += [cls(self, device) for cls in get_spec(device)]
   File "/config/custom_components/sonoff/core/devices.py", line 240, in get_spec
     # NSPanel Climate disable without switch configuration
 TypeError: argument of type 'int' is not iterable
```

The line number is "lie", if I use [] instead of () on line 235, don't get this error message.

**Comment by 20bart** [comment]
Thanks for the feed, but I have tried this solution by adjusting it manually, but it doesn't resolve the issue for not updating the position.

**Comment by FelisucoVFR** [comment]
Hi, I am using the R3 as a dual switch and I am getting the same lack of status update.
I have checked that disconnecting LAN mode at the eWeLink app the device stopped working (only by hand switch works of course). It seems any of my R3 are connecting to the cloud.

**Comment by antrema** [comment]
Hi, same status for me
No status update, position doesn't change in HA while I manipulate the covers
But covers work well with eWelink app

**Comment by ArekARCODE** [comment]
hi, i had this problem when dual R3 did not have internet connection, fixed internet connection of dual R3 and it works. looks like duals still need internet connection to report position to home assistant

**Comment by AlexxIT** [comment]
@20bart thanks for logs. This is same problem as #839
Fix already in master version. Will be in next release

**Comment by eddymar42** [comment]
It appears this issue has re-appeared in V3.3.1

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant

**Comment by FassRoller** [comment]
I have the same problem with Sonoff DW2….
