### ISSUE TITLE
how to fix [Error during setup of component sonoff]

### ISSUE THREAD

**Issue by pongdevelop** [AlexxIT/SonoffLAN#92]
Home Assistant 0.109.3
Python 3.7.7

2020-05-05 00:10:41 ERROR (MainThread) [homeassistant.setup] Error during setup of component sonoff
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/sonoff/__init__.py", line 53, in async_setup
    devices = utils.load_cache(filename)
  File "/config/custom_components/sonoff/utils.py", line 61, in load_cache
    return json.load(f)
  File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

**Comment by pongdevelop** [comment]
I can fix it myself.
thank you

**Comment by AlexxIT** [comment]
What was it? Maybe other users need help?
