### ISSUE TITLE
Cloud WS exception

### ISSUE THREAD

**Issue by sipimokus** [AlexxIT/SonoffLAN#920]
Dear Alexx!

I have an **important** problem.
My electrical measurement stops very often because of this error.

With AUTO or CLOUD mode too have a problem.

I caught this error:
```
Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/core/ewelink/cloud.py:317
Integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: 2022. július 24. 19:21:33 (1 occurrences)
Last logged: 2022. július 24. 19:21:33

Cloud WS exception
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 317, in connect
    if resp["error"] != 0:
KeyError: 'error'
```
```
2022-07-24 19:21:33 [E] Cloud WS exception|  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 317, in connect|    if resp["error"] != 0:|KeyError: 'error'|
2022-07-24 19:21:33 [D] CLOUD True => False
2022-07-25 08:58:50 [D] CLOUD False => False
```
![image](https://user-images.githubusercontent.com/1633489/180753982-210068fa-c25b-415c-973e-3164ffd541d4.png)

If I reloading the configuration, after is good (for some time).

I don't find service for call this reload.
The previous (old legacy 2.x) version had a `sonoff.update_consumption`, reintroducing something like this would be a problem?

HASS: 2022.7.6
Plugin: v3.1.0

Thank you!
Sipi

Update: I see now that there is a similar ticket, sorry for the duplication.
https://github.com/AlexxIT/SonoffLAN/issues/869

**Comment by sipimokus** [comment]
PR: https://github.com/AlexxIT/SonoffLAN/pull/964

**Comment by sipimokus** [comment]
I found another problem in the `XClimateNS` class.
The "problem" with the Home Assistant, I think earlier try getting the supported features than `set_state` is running.

I set default supported features, and (I hope) it will be changed later when state is refreshed. 

After this fix there are no more such error entries in the log.
PR: https://github.com/AlexxIT/SonoffLAN/pull/1001
